"""Governed NovaPay platform domains."""

from .repository import (
    NovaPayRecord,
    NovaPayRepository,
    PostgresNovaPayRepository,
    build_repository_from_environment,
    validate_database_runtime,
)
from .portal_suite import NovaPortalSuite
from .migration import migrate_legacy_monetary_state
from .service import NovaPayEcosystem
from .surfaces import build_app_surfaces, build_trust_surfaces
from .ecosystem_contract import novapay_ecosystem_contract

from .domain.fx import (
    CurrencyPair,
    ExchangeRate,
    ExchangeRateId,
    ExchangeRateSource,
    ExchangeRateStatus,
    ExchangeRateValue,
    FXMetadata,
    FXQuote,
    FXQuoteId,
    FXQuoteStatus,
    FXValidityWindow,
    RateSpread,
)

from .domain.currency import (
    STANDARD_CURRENCY_DEFINITIONS,
    CurrencyCountryCodes,
    CurrencyDefinition,
    CurrencyDefinitionId,
    CurrencyMetadata,
    CurrencyName,
    CurrencyRegistry,
    CurrencyRegistryId,
    CurrencyRoundingMode,
    CurrencyStatus,
    CurrencySymbol,
    CurrencyType,
    standard_currency_definitions,
    standard_currency_registry,
)

from .domain.balance_snapshot import (
    BalanceComponent,
    BalanceComponentType,
    BalanceReconciliation,
    BalanceSnapshot,
    BalanceSnapshotHistory,
    BalanceSnapshotHistoryId,
    BalanceSnapshotId,
    BalanceSnapshotMetadata,
    BalanceSnapshotStatus,
    BalanceSnapshotType,
    LedgerPosition,
)

__all__ = [
    "AuthorityKind",
    "BalanceComponent",
    "BalanceComponentType",
    "BalanceReconciliation",
    "BalanceSnapshot",
    "BalanceSnapshotHistory",
    "BalanceSnapshotHistoryId",
    "BalanceSnapshotId",
    "BalanceSnapshotMetadata",
    "BalanceSnapshotStatus",
    "BalanceSnapshotType",
    "CANONICAL_NOVAPAY_PACKAGE",
    "CAPABILITY_AUTHORITIES",
    "CapabilityAuthority",
    "CapabilityStatus",
    "Currency",
    "CurrencyCountryCodes",
    "CurrencyDefinition",
    "CurrencyDefinitionId",
    "CurrencyMetadata",
    "CurrencyName",
    "CurrencyPair",
    "CurrencyRegistry",
    "CurrencyRegistryId",
    "CurrencyRoundingMode",
    "CurrencyStatus",
    "CurrencySymbol",
    "CurrencyType",
    "Customer",
    "CustomerAddress",
    "CustomerContact",
    "CustomerId",
    "CustomerMetadata",
    "CustomerName",
    "CustomerPreferences",
    "CustomerStatus",
    "CustomerTier",
    "CustomerType",
    "DEFAULT_MINOR_UNITS",
    "ExchangeRate",
    "ExchangeRateId",
    "ExchangeRateSource",
    "ExchangeRateStatus",
    "ExchangeRateValue",
    "FXMetadata",
    "FXQuote",
    "FXQuoteId",
    "FXQuoteStatus",
    "FXValidityWindow",
    "FinancialAccount",
    "FinancialAccountId",
    "FinancialAccountMetadata",
    "FinancialAccountName",
    "FinancialAccountPurpose",
    "FinancialAccountRestrictions",
    "FinancialAccountStatus",
    "FinancialAccountTerms",
    "FinancialAccountType",
    "JournalEntry",
    "JournalEntryId",
    "JournalEntryMetadata",
    "JournalEntryStatus",
    "JournalEntryType",
    "LEGACY_PAYMENT_ENGINE",
    "LedgerAccount",
    "LedgerAccountId",
    "LedgerAccountMetadata",
    "LedgerAccountStatus",
    "LedgerAccountType",
    "LedgerPosition",
    "Money",
    "NOVAPAY_PRODUCT_OWNER",
    "NormalBalanceSide",
    "NovaPayEcosystem",
    "NovaPayRecord",
    "NovaPayRepository",
    "NovaPortalSuite",
    "PROHIBITED_DUPLICATION",
    "PostgresNovaPayRepository",
    "PostingLine",
    "PostingLineId",
    "PostingLineMetadata",
    "PostingSide",
    "RateSpread",
    "STANDARD_CURRENCY_DEFINITIONS",
    "Transaction",
    "TransactionDirection",
    "TransactionId",
    "TransactionMetadata",
    "TransactionStatus",
    "TransactionType",
    "Transfer",
    "TransferAccountReference",
    "TransferAmountBreakdown",
    "TransferBeneficiaryReference",
    "TransferCharge",
    "TransferDirection",
    "TransferFee",
    "TransferFeeType",
    "TransferFundingReference",
    "TransferId",
    "TransferInstruction",
    "TransferInstructionId",
    "TransferInstructionMetadata",
    "TransferMetadata",
    "TransferPartyReference",
    "TransferPricingMetadata",
    "TransferPriority",
    "TransferPurpose",
    "TransferReference",
    "TransferStatus",
    "TransferType",
    "Wallet",
    "WalletId",
    "WalletMetadata",
    "WalletStatus",
    "WalletType",
    "authority_for",
    "build_app_surfaces",
    "build_repository_from_environment",
    "build_trust_surfaces",
    "financial_source_of_truth",
    "freeze_money_payload",
    "migrate_legacy_monetary_state",
    "novapay_ecosystem_contract",
    "standard_currency_definitions",
    "standard_currency_registry",
    "validate_authority_map",
    "validate_database_runtime",
]
# NovaPay WP-001B authority exports
from .authority import (
    AuthorityKind,
    CapabilityAuthority,
    CapabilityStatus,
    CANONICAL_NOVAPAY_PACKAGE,
    CAPABILITY_AUTHORITIES,
    LEGACY_PAYMENT_ENGINE,
    NOVAPAY_PRODUCT_OWNER,
    PROHIBITED_DUPLICATION,
    authority_for,
    financial_source_of_truth,
    validate_authority_map,
)

# NovaPay WP-001C1 domain exports
from .domain import (
    Currency,
    DEFAULT_MINOR_UNITS,
    Money,
    freeze_money_payload,
)

# NovaPay WP-001C2 wallet exports
from .domain import (
    Wallet,
    WalletId,
    WalletMetadata,
    WalletStatus,
    WalletType,
)

# NovaPay WP-001C3 ledger account exports
from .domain import (
    LedgerAccount,
    LedgerAccountId,
    LedgerAccountMetadata,
    LedgerAccountStatus,
    LedgerAccountType,
    NormalBalanceSide,
)


# NovaPay WP-001C5 transaction exports
from .domain import (
    Transaction,
    TransactionDirection,
    TransactionId,
    TransactionMetadata,
    TransactionStatus,
    TransactionType,
)


# NovaPay WP-001C4 journal-entry exports
from .domain import (
    JournalEntry,
    JournalEntryId,
    JournalEntryMetadata,
    JournalEntryStatus,
    JournalEntryType,
    PostingLine,
    PostingLineId,
    PostingLineMetadata,
    PostingSide,
)
from .domain.customer import (
    Customer,
    CustomerAddress,
    CustomerContact,
    CustomerId,
    CustomerMetadata,
    CustomerName,
    CustomerPreferences,
    CustomerStatus,
    CustomerTier,
    CustomerType,
)
from .domain.financial_account import (
    FinancialAccount,
    FinancialAccountId,
    FinancialAccountMetadata,
    FinancialAccountName,
    FinancialAccountPurpose,
    FinancialAccountRestrictions,
    FinancialAccountStatus,
    FinancialAccountTerms,
    FinancialAccountType,
)

from .domain import (
    Transfer,
    TransferAccountReference,
    TransferAmountBreakdown,
    TransferBeneficiaryReference,
    TransferCharge,
    TransferDirection,
    TransferFee,
    TransferFeeType,
    TransferFundingReference,
    TransferId,
    TransferInstruction,
    TransferInstructionId,
    TransferInstructionMetadata,
    TransferMetadata,
    TransferPartyReference,
    TransferPricingMetadata,
    TransferPriority,
    TransferPurpose,
    TransferReference,
    TransferStatus,
    TransferType,
)
