import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "business",
  appName: "NovaID Business",
  packageId: "com.novatech.novaid.business",
  tagline: "Business identity, KYB, trust, and digital seal management.",
  trustTheme: "#1b8a6b",
  tabs: [
    { key: "dashboard", label: "Dashboard", description: "Business identity summary and KYB status." },
    { key: "company", label: "Company", description: "Company profile, directors, and tax data." },
    { key: "employees", label: "Employees", description: "Invite staff and manage access." },
    { key: "certificates", label: "Certificates", description: "Issue and review digital seals." },
    { key: "risk", label: "Risk", description: "Policy evaluation and risk reporting." },
    { key: "profile", label: "Profile", description: "Support, identity, and audit details." },
  ],
  actions: [
    { label: "Verify Business", detail: "Run KYB verification across registration and policy checks." },
    { label: "Add Director", detail: "Register a new director and update governance records." },
    { label: "Invite Employee", detail: "Send a secure invitation for employee provisioning." },
    { label: "Issue Certificate", detail: "Create a digital seal or business certificate." },
    { label: "View Digital Seal", detail: "Open the latest seal and replay proof." },
    { label: "Download KYB Report", detail: "Export a signed business verification package." },
  ],
  primaryFlow: [
    "KYB Request",
    "Director Verification",
    "Tax Validation",
    "Policy Evaluation",
    "Business Approved",
    "Digital Seal Issued",
  ],
  seed: {
    displayName: "Nova Holdings Pty",
    walletLabel: "Business identity vault",
    trustLevel: "Verified",
    identityScore: 94,
    credentialCount: 4,
    trustedDevices: 3,
    governmentIds: 2,
    certificateCount: 3,
    biometricVerified: true,
    passkeyEnabled: true,
    deviceTrustEnabled: true,
    recoveryEnabled: true,
    connectedApps: 6,
    loginHistory: 26,
  },
};
