import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "business",
  appName: "NovaID Business",
  packageId: "com.novatech.novaid.business",
  tagline: "Business identity, KYB, representatives, access, audit, and digital seal management.",
  trustTheme: "#1b8a6b",
  tabs: [
    { key: "overview", label: "Overview", description: "Business verification status, trust score, and alerts." },
    { key: "business-verify", label: "Business Verify", description: "Enter business details and complete KYB." },
    { key: "representatives", label: "Representatives", description: "Directors, beneficial owners, and authorized signers." },
    { key: "documents", label: "Documents", description: "Business documents, certificates, and renewals." },
    { key: "access", label: "Access", description: "Users, roles, permissions, and MFA." },
    { key: "audit", label: "Audit", description: "Audit trail, login activity, and verification events." },
    { key: "settings", label: "Settings", description: "Business profile, linked apps, and security settings." },
    { key: "dashboard", label: "Dashboard", description: "Legacy compatibility dashboard and KYB status." },
    { key: "company", label: "Company", description: "Legacy company profile, directors, and tax data." },
    { key: "employees", label: "Employees", description: "Legacy staff invite and access management." },
    { key: "certificates", label: "Certificates", description: "Legacy seal issuance and review." },
    { key: "risk", label: "Risk", description: "Legacy policy evaluation and risk reporting." },
    { key: "profile", label: "Profile", description: "Support, identity, and audit details." },
  ],
  actions: [
    { label: "View business verification status", detail: "Open the current KYB state and approval progress." },
    { label: "View business trust score", detail: "Show the business trust and compliance score." },
    { label: "View linked finance wallet", detail: "Open the connected business finance wallet surface." },
    { label: "View linked mobility operator", detail: "Review the linked mobility operator connection." },
    { label: "View compliance alerts", detail: "Inspect alerts tied to the business identity." },
    { label: "Export business profile", detail: "Export the current business identity profile." },
    { label: "Enter business details", detail: "Start the KYB intake flow with business details." },
    { label: "Upload business registration", detail: "Attach the business registration certificate." },
    { label: "Upload tax certificate", detail: "Attach the tax certificate or tax profile." },
    { label: "Verify business address", detail: "Validate the registered office address." },
    { label: "Verify business phone", detail: "Verify the business phone number with OTP." },
    { label: "Verify business email", detail: "Verify the business email address with a secure link." },
    { label: "Submit KYB review", detail: "Submit the verification pack for review." },
    { label: "Check KYB status", detail: "Refresh the KYB review state." },
    { label: "Add representative", detail: "Add an authorized representative to the profile." },
    { label: "Verify representative ID", detail: "Verify the representative's government ID." },
    { label: "Add beneficial owner", detail: "Record a beneficial owner where required." },
    { label: "Assign authorized signer", detail: "Assign signing authority to a representative." },
    { label: "Remove representative", detail: "Remove a representative from the profile." },
    { label: "View representative status", detail: "Inspect representative verification state." },
    { label: "Upload business document", detail: "Attach a supporting business document." },
    { label: "View documents", detail: "Review all uploaded business documents." },
    { label: "Replace document", detail: "Replace an outdated business document." },
    { label: "Renew expired document", detail: "Start a document renewal flow." },
    { label: "Download verification certificate", detail: "Export the current verification certificate." },
    { label: "Manage users", detail: "Manage business users and invites." },
    { label: "Manage roles", detail: "Manage business roles and access groups." },
    { label: "Manage permissions", detail: "Edit business permissions and controls." },
    { label: "Invite staff", detail: "Send a secure staff invitation." },
    { label: "Suspend user", detail: "Suspend a user account from the business profile." },
    { label: "Activate user", detail: "Reactivate a suspended user account." },
    { label: "Require MFA", detail: "Require MFA for protected business actions." },
    { label: "View audit trail", detail: "Inspect the business audit trail." },
    { label: "View login activity", detail: "Review login history and device activity." },
    { label: "View verification events", detail: "Review KYB and trust-related events." },
    { label: "View consent records", detail: "Review granted and revoked consent records." },
    { label: "Download audit report", detail: "Export a signed audit report." },
    { label: "Report suspicious access", detail: "Escalate suspicious access to review." },
    { label: "Edit business profile", detail: "Update the business profile details." },
    { label: "Manage organization details", detail: "Update organization information and settings." },
    { label: "Manage security settings", detail: "Adjust security controls and device rules." },
    { label: "Manage linked apps", detail: "Review connected services and integrations." },
    { label: "Notification settings", detail: "Adjust notification preferences." },
    { label: "Privacy settings", detail: "Update privacy and consent preferences." },
    { label: "Logout", detail: "End the business identity session." },
    { label: "Verify Business", detail: "Run KYB verification across registration and policy checks." },
    { label: "Add Director", detail: "Register a new director and update governance records." },
    { label: "Invite Employee", detail: "Send a secure invitation for employee provisioning." },
    { label: "Issue Certificate", detail: "Create a digital seal or business certificate." },
    { label: "View Digital Seal", detail: "Open the latest seal and replay proof." },
    { label: "Download KYB Report", detail: "Export a signed business verification package." },
  ],
  primaryFlow: [
    "KYB Request",
    "Director Verification",
    "Tax Validation",
    "Policy Evaluation",
    "Business Approved",
    "Digital Seal Issued",
  ],
  seed: {
    displayName: "Nova Holdings Pty",
    walletLabel: "Business identity vault",
    trustLevel: "Verified",
    identityScore: 94,
    credentialCount: 4,
    trustedDevices: 3,
    governmentIds: 2,
    certificateCount: 3,
    biometricVerified: true,
    passkeyEnabled: true,
    deviceTrustEnabled: true,
    recoveryEnabled: true,
    connectedApps: 6,
    loginHistory: 26,
  },
};
