# Generated by Django 5.2.14 on 2026-05-27 18:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("entry_hash", models.CharField(editable=False, max_length=64)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("epoch", models.IntegerField()),
                ("status", models.CharField(default="VALID", max_length=20)),
                ("invalid_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["timestamp", "id"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="afritech_au_timesta_106f04_idx"
                    ),
                    models.Index(fields=["epoch"], name="afritech_au_epoch_153038_idx"),
                    models.Index(
                        fields=["entry_hash"], name="afritech_au_entry_h_ac1f90_idx"
                    ),
                ],
            },
        ),
    ]
