# Generated by Django 5.2.14 on 2026-05-27 21:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afritech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("epoch", models.IntegerField(unique=True)),
                ("merkle_root", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["epoch"],
            },
        ),
    ]
