# Generated by Django 5.2.14 on 2026-05-27 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afritech", "0002_auditseal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditseal",
            options={
                "ordering": ["epoch"],
                "verbose_name": "Audit Seal",
                "verbose_name_plural": "Audit Seals",
            },
        ),
        migrations.AddField(
            model_name="auditseal",
            name="signature",
            field=models.TextField(
                blank=True,
                help_text="Base64-encoded signature of the Merkle root",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditseal",
            name="epoch",
            field=models.IntegerField(
                db_index=True,
                help_text="Logical time boundary for this seal",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditseal",
            name="merkle_root",
            field=models.CharField(
                help_text="SHA-256 Merkle root of audit logs", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="auditseal",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddIndex(
            model_name="auditseal",
            index=models.Index(fields=["epoch"], name="afritech_au_epoch_079e2e_idx"),
        ),
        migrations.AddIndex(
            model_name="auditseal",
            index=models.Index(
                fields=["timestamp"], name="afritech_au_timesta_ee76f7_idx"
            ),
        ),
    ]
