# Generated by Codex on 2026-06-05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afritech", "0003_alter_auditseal_options_auditseal_signature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_id", models.CharField(db_index=True, max_length=128)),
                ("device_id", models.CharField(db_index=True, max_length=128)),
                ("public_key", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["actor_id", "device_id"],
                "unique_together": {("actor_id", "device_id")},
            },
        ),
        migrations.CreateModel(
            name="EventRecord",
            fields=[
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("actor_id", models.CharField(db_index=True, max_length=128)),
                ("subject_id", models.CharField(db_index=True, max_length=128)),
                ("prev_hash", models.CharField(blank=True, max_length=128)),
                ("event_hash", models.CharField(db_index=True, max_length=128, unique=True)),
                ("payload", models.JSONField()),
                ("signature", models.JSONField()),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at", "event_id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("receipts", models.JSONField(default=dict)),
                ("witnesses", models.JSONField(default=list)),
                ("bundle_hash", models.CharField(db_index=True, max_length=128, unique=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="afritech.eventrecord")),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WitnessSignature",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verifier_node", models.CharField(db_index=True, max_length=128)),
                ("signature", models.TextField()),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="afritech.eventrecord")),
            ],
            options={
                "ordering": ["created_at", "id"],
                "unique_together": {("event", "verifier_node")},
            },
        ),
        migrations.AddIndex(
            model_name="eventrecord",
            index=models.Index(fields=["event_type"], name="afritech_ev_event_t_3415df_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrecord",
            index=models.Index(fields=["actor_id"], name="afritech_ev_actor_i_95389d_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrecord",
            index=models.Index(fields=["subject_id"], name="afritech_ev_subject_11c64d_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrecord",
            index=models.Index(fields=["created_at"], name="afritech_ev_created_7f6219_idx"),
        ),
    ]
