# AUTO-GENERATED — DO NOT EDIT
# Generated by compile_epoch.py

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


# ---------------------------------------------------------------------
# EPOCH TYPE
# ---------------------------------------------------------------------

class EpochType(Enum):
    """
    Constitutional epoch classification.
    """

    GENESIS = "GENESIS"
    EVOLUTION = "EVOLUTION"
    CORRECTION = "CORRECTION"
    NORMALIZATION = "NORMALIZATION"
    TERMINAL = "TERMINAL"


# ---------------------------------------------------------------------
# SEMANTIC EPOCH
# ---------------------------------------------------------------------

@dataclass(frozen=True)
class SemanticEpoch:
    """
    Compiled constitutional semantic epoch.

    This is the ONLY lawful carrier of epoch meaning.

    Generated deterministically from:

        epoch_semantics.yaml
    """

    number: int
    parent: int | None
    epoch_type: EpochType
    reseal_required: bool

    # -----------------------------------------------------------------
    # STRUCTURAL SANITY
    # -----------------------------------------------------------------

    def __post_init__(self) -> None:
        if not isinstance(self.number, int):
            raise TypeError(
                "SemanticEpoch.number must be int"
            )

        if self.number < 0:
            raise ValueError(
                "SemanticEpoch.number must be >= 0"
            )

        if self.number == 0 and self.parent is not None:
            raise ValueError(
                "Genesis epoch must not declare parent"
            )

        if self.number > 0:
            if not isinstance(self.parent, int):
                raise TypeError(
                    "Non-genesis epoch parent must be int"
                )

            if self.parent != self.number - 1:
                raise ValueError(
                    "Epoch parent continuity violated"
                )

        if not isinstance(
            self.epoch_type,
            EpochType,
        ):
            raise TypeError(
                "epoch_type must be EpochType"
            )

        if not isinstance(
            self.reseal_required,
            bool,
        ):
            raise TypeError(
                "reseal_required must be bool"
            )

    # -----------------------------------------------------------------
    # SERIALIZATION
    # -----------------------------------------------------------------

    def to_dict(self) -> dict:
        """
        Deterministic documentary projection.
        """

        return {
            "number": self.number,
            "parent": self.parent,
            "epoch_type": self.epoch_type.value,
            "reseal_required": self.reseal_required,
        }

    # -----------------------------------------------------------------
    # RECONSTRUCTION
    # -----------------------------------------------------------------

    @classmethod
    def from_dict(
        cls,
        data: dict,
    ) -> "SemanticEpoch":
        """
        Deterministic reconstruction surface.
        """

        return cls(
            number=data["number"],
            parent=data["parent"],
            epoch_type=EpochType(
                data["epoch_type"]
            ),
            reseal_required=data[
                "reseal_required"
            ],
        )

    # -----------------------------------------------------------------
    # DOCUMENTARY REPRESENTATION
    # -----------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            "SemanticEpoch("
            f"number={self.number}, "
            f"parent={self.parent}, "
            f"epoch_type={self.epoch_type.name}, "
            f"reseal_required={self.reseal_required}"
            ")"
        )