[pytest]

DJANGO_SETTINGS_MODULE = afriride_system.django_app.config.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = .

# ✅ CRITICAL: disable Django plugin for AFRIPower tests
addopts =
    --strict-markers
    --disable-warnings
    --maxfail=1
    -p no:django

testpaths =
    afritech/tests
    tests
    afriride_system/tests
    ecosystems/afriride/tests
