from __future__ import annotations

from enum import StrEnum


class CapabilityState(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    CONFIGURED = "CONFIGURED"
    EXECUTION_PENDING = "EXECUTION_PENDING"
    RUNNING = "RUNNING"
    EXECUTED = "EXECUTED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED = "VERIFIED"
    CERTIFICATION_PENDING = "CERTIFICATION_PENDING"
    CERTIFIED = "CERTIFIED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVED = "APPROVED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class EvidenceStatus(StrEnum):
    PENDING = "PENDING"
    COLLECTED = "COLLECTED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class Decision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    ABSTAIN = "ABSTAIN"


class VerificationDomain(StrEnum):
    OBSERVABILITY = "OBSERVABILITY"
    ACCESSIBILITY = "ACCESSIBILITY"
    VISUAL_REGRESSION = "VISUAL_REGRESSION"
    DIGITAL_UX_TWIN = "DIGITAL_UX_TWIN"
    QUALITY = "QUALITY"
    SECURITY = "SECURITY"
    PERFORMANCE = "PERFORMANCE"
    OPERATIONS = "OPERATIONS"
    UX = "UX"
    COMPLIANCE = "COMPLIANCE"
    RESILIENCE = "RESILIENCE"
    MOBILE_RELEASE = "MOBILE_RELEASE"


class PaymentState(StrEnum):
    DISABLED = "DISABLED"
    SANDBOX = "SANDBOX"
    PILOT_REAL = "PILOT_REAL"
    PRODUCTION_ELIGIBLE = "PRODUCTION_ELIGIBLE"
    ACTIVATION_AUTHORIZED = "ACTIVATION_AUTHORIZED"
    ENABLED = "ENABLED"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class GADecision(StrEnum):
    GA_BLOCKED = "GA_BLOCKED"
    GA_ELIGIBLE = "GA_ELIGIBLE"
    GA_AUTHORIZED = "GA_AUTHORIZED"
    GA_ACTIVE = "GA_ACTIVE"
    GA_REVOKED = "GA_REVOKED"
