import type { NovaPayRoleConfig } from "./roleApp";

export const legacyConsumerTabs = ["Home", "Pay", "Activity", "Cards", "Profile"] as const;
export const legacyConsumerFlows = ["Send Money", "Receive Money", "QR Pay", "Bank Transfer"] as const;

export const config: NovaPayRoleConfig = {
  appName: "NovaPay Consumer",
  role: "consumer",
  balanceLabel: "Wallet balance",
  balance: "AUD 2,480.50",
  tabs: ["Home", "Send", "Receive", "Wallet", "Payments", "History", "Profile"],
  primaryFlows: ["Send Money", "Receive Money", "Scan QR", "Pay merchant"],
  features: [
    "Wallet Balance", "Send Money", "Receive Money", "Scan QR", "Pay Merchant",
    "Pay Bill", "Buy Airtime/Data", "Transaction History", "Security Center", "Support",
    "NovaID Verification", "Dark Mode", "Accessibility", "Receipts", "Recurring Payments",
  ],
  sections: [
    {
      title: "Home",
      description: "Daily wallet overview and high-value actions.",
      buttons: [
        "View wallet balance",
        "Top up wallet",
        "Send money",
        "Receive money",
        "Scan QR",
        "Pay merchant",
        "Pay bill",
        "Buy airtime/data",
        "View recent transactions",
        "Open NovaID verification",
        "Open security center",
      ],
    },
    {
      title: "Send",
      description: "One-tap remittance and local transfers.",
      buttons: [
        "Send to NovaPay user",
        "Send to phone number",
        "Send to bank account",
        "Send to mobile money",
        "International transfer",
        "Choose recipient",
        "Enter amount",
        "Add note",
        "Review transfer",
        "Confirm transfer",
        "Cancel transfer",
        "Share receipt",
      ],
    },
    {
      title: "Receive",
      description: "Incoming payment and transfer handling.",
      buttons: [
        "Show QR code",
        "Request money",
        "Copy wallet ID",
        "Share payment link",
        "Receive from agent",
        "Receive from bank",
        "Confirm received payment",
      ],
    },
    {
      title: "Wallet",
      description: "Funding sources, limits, and wallet controls.",
      buttons: [
        "Top up",
        "Cash out",
        "Link bank account",
        "Link card",
        "Link mobile money",
        "Set default funding source",
        "View limits",
        "Upgrade wallet level",
        "Freeze wallet",
      ],
    },
    {
      title: "Payments",
      description: "Merchant, bill, airtime, and recurring payments.",
      buttons: [
        "Scan merchant QR",
        "Pay with QR",
        "Pay bill",
        "Buy airtime",
        "Buy data",
        "Pay school fees",
        "Pay utilities",
        "Schedule payment",
        "Manage recurring payments",
      ],
    },
    {
      title: "History",
      description: "Receipts, disputes, and exportable transaction records.",
      buttons: [
        "View transaction",
        "Download receipt",
        "Share receipt",
        "Report transaction",
        "Dispute transaction",
        "Filter history",
        "Export statement",
      ],
    },
    {
      title: "Profile",
      description: "Identity, security, and device management.",
      buttons: [
        "Edit profile",
        "Verify NovaID",
        "Upload ID",
        "Security settings",
        "Change PIN",
        "Enable biometric login",
        "Manage devices",
        "Language settings",
        "Notification settings",
        "Help and support",
        "Logout",
      ],
    },
  ],
};
