# afritech/proof/formal/generate_invariants_lean.py

"""
AfriTech Formal Invariant Generator (Lean)
==========================================

This generator produces Lean definitions AND theorem stubs
from the canonical compiled invariant semantic IR.

AUTHORITATIVE INPUT:
- afritech/constitution/compiled/invariants_ir.json

GENERATED OUTPUT (DO NOT EDIT):
- afritech/formal/generated/invariants.lean

CONSTITUTIONAL RULE:
Lean formalization MUST be derived mechanically from
Semantic IR. Handwritten invariant semantics are forbidden.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict, Any


# ---------------------------------------------------------------------
# PATHS (CANONICAL)
# ---------------------------------------------------------------------

ROOT = Path(__file__).resolve().parents[3]

IR_FILE = (
    ROOT
    / "afritech"
    / "constitution"
    / "compiled"
    / "invariants_ir.json"
)

OUTPUT_DIR = ROOT / "afritech" / "formal" / "generated"
OUTPUT_FILE = OUTPUT_DIR / "invariants.lean"


# ---------------------------------------------------------------------
# FAILURE HANDLING
# ---------------------------------------------------------------------

def fail(msg: str) -> None:
    print(f"[LEAN GENERATOR ERROR] {msg}", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------
# LOAD IR
# ---------------------------------------------------------------------

def load_ir() -> Dict[str, Any]:
    if not IR_FILE.exists():
        fail(f"Missing invariant semantic IR: {IR_FILE}")

    data = json.loads(IR_FILE.read_text(encoding="utf-8"))

    invariants = data.get("invariants")
    if not isinstance(invariants, dict):
        fail("Invariant IR missing 'invariants' mapping")

    return {
        "schema": data.get("schema"),
        "generated_at": data.get("generated_at"),
        "source_hash": data.get("source_hash"),
        "invariants": invariants,
    }


# ---------------------------------------------------------------------
# LEAN EMISSION HELPERS
# ---------------------------------------------------------------------

def lean_header(meta: Dict[str, Any]) -> str:
    return f"""
/-
AUTO-GENERATED FILE — DO NOT EDIT
=================================

This file was generated by:
  afritech/proof/formal/generate_invariants_lean.py

Source:
  afritech/constitution/compiled/invariants_ir.json

Generation time:
  {datetime.utcnow().isoformat()}Z

Source hash:
  {meta["source_hash"]}

Constitutional rule:
  All invariant semantics originate in Semantic IR.
  Handwritten Lean semantics are forbidden.
-/

namespace AfriTech
"""


def lean_footer() -> str:
    return """
end AfriTech
"""


def emit_invariant_type() -> str:
    return """
/-- Abstract type representing a constitutional invariant. -/
constant Invariant : Type
"""


def emit_invariant_constants(invariants: Dict[str, Any]) -> str:
    lines = [
        "/-- Canonical constitutional invariants (generated). -/",
    ]
    for inv_id in sorted(invariants.keys()):
        lines.append(f"constant {inv_id} : Invariant")
    return "\n".join(lines)


def emit_invariant_set(invariants: Dict[str, Any]) -> str:
    lines = [
        "",
        "/-- Set of all declared constitutional invariants. -/",
        "def AllInvariants : Set Invariant :=",
        "  {",
    ]
    for inv_id in sorted(invariants.keys()):
        lines.append(f"    {inv_id},")
    lines.append("  }")
    return "\n".join(lines)


def emit_invariant_theorems(invariants: Dict[str, Any]) -> str:
    lines = [
        "",
        "/-- Formal theorem stubs for constitutional invariants.",
        "These are placeholders and MUST be discharged in later phases. -/",
    ]

    for inv_id in sorted(invariants.keys()):
        theorem_name = inv_id.lower()
        lines.append(f"theorem {theorem_name} : True := by")
        lines.append("  trivial")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------
# MAIN GENERATION
# ---------------------------------------------------------------------

def main() -> None:
    meta = load_ir()
    invariants = meta["invariants"]

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    lean_code = "\n".join([
        lean_header(meta),
        emit_invariant_type(),
        emit_invariant_constants(invariants),
        emit_invariant_set(invariants),
        emit_invariant_theorems(invariants),
        lean_footer(),
    ])

    OUTPUT_FILE.write_text(lean_code.strip() + "\n", encoding="utf-8")

    print("[OK] Lean invariant definitions generated")
    print(f"     Invariants: {len(invariants)}")
    print(f"     Output: {OUTPUT_FILE.relative_to(ROOT)}")


# ---------------------------------------------------------------------
# ENTRYPOINT
# ---------------------------------------------------------------------

if __name__ == "__main__":
    main()