# afritech/proof/formal/generate_epoch_lean.py

"""
AfriTech Formal Epoch Generator (Lean)
=====================================

This generator produces Lean formal artifacts from the
canonical compiled epoch semantic IR.

AUTHORITATIVE INPUT:
- afritech/epoch/compiled/epoch_ir.json

GENERATED OUTPUT (DO NOT EDIT):
- afritech/formal/generated/epochs.lean

CONSTITUTIONAL RULE:
Epoch semantics MUST be derived mechanically from compiled IR.
No handwritten epoch meaning may exist in Lean.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List


# ---------------------------------------------------------------------
# PATHS (CANONICAL)
# ---------------------------------------------------------------------

ROOT = Path(__file__).resolve().parents[3]

IR_FILE = (
    ROOT
    / "afritech"
    / "epoch"
    / "compiled"
    / "epoch_ir.json"
)

OUTPUT_DIR = ROOT / "afritech" / "formal" / "generated"
OUTPUT_FILE = OUTPUT_DIR / "epochs.lean"


# ---------------------------------------------------------------------
# FAILURE HANDLING
# ---------------------------------------------------------------------

def fail(msg: str) -> None:
    print(f"[LEAN EPOCH GENERATOR ERROR] {msg}", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------
# LOAD IR
# ---------------------------------------------------------------------

def load_ir() -> Dict[str, Any]:
    if not IR_FILE.exists():
        fail(f"Missing epoch semantic IR: {IR_FILE}")

    data = json.loads(IR_FILE.read_text(encoding="utf-8"))

    required_keys = {
        "schema",
        "generated_at",
        "source_hash",
        "epoch_types",
        "transition_rules",
        "lineage",
    }

    missing = required_keys - data.keys()
    if missing:
        fail(f"Epoch IR missing required keys: {sorted(missing)}")

    return data


# ---------------------------------------------------------------------
# LEAN EMISSION HELPERS
# ---------------------------------------------------------------------

def lean_header(meta: Dict[str, Any]) -> str:
    return f"""
/-
AUTO-GENERATED FILE — DO NOT EDIT
================================

This file was generated by:
  afritech/proof/formal/generate_epoch_lean.py

Source:
  afritech/epoch/compiled/epoch_ir.json

Generation time:
  {datetime.utcnow().isoformat()}Z

Source hash:
  {meta["source_hash"]}

Constitutional rule:
  All epoch semantics originate in compiled Semantic IR.
  Handwritten epoch meaning in Lean is forbidden.
-/

namespace AfriTechEpoch
"""


def lean_footer() -> str:
    return """
end AfriTechEpoch
"""


def emit_epoch_type_enum(epoch_types: Dict[str, Any]) -> str:
    lines: List[str] = [
        "/-- Canonical constitutional epoch types (generated). -/",
        "inductive EpochType",
    ]

    for name in sorted(epoch_types.keys()):
        lines.append(f"  | {name}")

    return "\n".join(lines)


def emit_semantic_epoch_structure() -> str:
    return """
/-- Immutable semantic epoch structure (generated). -/
structure SemanticEpoch where
  number    : Nat
  parent    : Option Nat
  epochType : EpochType
  deriving Repr, DecidableEq
"""


def emit_transition_rules(transition_rules: Dict[str, Any]) -> str:
    lines: List[str] = [
        "/-- Allowed epoch transitions (generated). -/",
        "def AllowedEpochTransition : EpochType → EpochType → Prop",
    ]

    first = True
    for src, spec in transition_rules.items():
        for dst in spec.get("allowed_successors", []):
            prefix = "  |" if not first else "  |"
            lines.append(
                f"{prefix} EpochType.{src}, EpochType.{dst} => True"
            )
            first = False

    lines.append("  | _, _ => False")
    return "\n".join(lines)


def emit_epoch_lineage(lineage: Dict[str, Any]) -> str:
    epochs = lineage.get("epochs", [])

    lines: List[str] = [
        "/-- Declarative epoch lineage snapshot (generated). -/",
        "def EpochLineage : List SemanticEpoch :=",
        "  [",
    ]

    for e in epochs:
        parent = (
            f"(some {e['parent']})"
            if e["parent"] is not None
            else "none"
        )
        lines.append(
            f"    {{ number := {e['number']}, "
            f"parent := {parent}, "
            f"epochType := EpochType.{e['type']} }},"
        )

    lines.append("  ]")
    return "\n".join(lines)


def emit_epoch_theorems() -> str:
    """
    Formal theorem stubs required by constitutional epoch semantics.
    These are placeholders only and must be discharged later.
    """
    return """
/-- Epoch numbers strictly increase. -/
theorem epoch_strictly_increasing : True := by
  trivial

/-- Epoch rollback is impossible. -/
theorem epoch_no_regression : True := by
  trivial

/-- Only one epoch may be active at a time. -/
theorem epoch_singleton_active : True := by
  trivial

/-- Each epoch has a unique parent (except genesis). -/
theorem epoch_unique_parent : True := by
  trivial

/-- Once sealed, an epoch is immutable. -/
theorem sealed_epoch_immutable : True := by
  trivial
"""


# ---------------------------------------------------------------------
# MAIN GENERATION
# ---------------------------------------------------------------------

def main() -> None:
    meta = load_ir()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    lean_code = "\n".join([
        lean_header(meta),
        emit_epoch_type_enum(meta["epoch_types"]),
        emit_semantic_epoch_structure(),
        emit_transition_rules(meta["transition_rules"]),
        emit_epoch_lineage(meta["lineage"]),
        emit_epoch_theorems(),
        lean_footer(),
    ])

    OUTPUT_FILE.write_text(lean_code.strip() + "\n", encoding="utf-8")

    print("[OK] Lean epoch definitions generated")
    print(f"     Epoch types: {len(meta['epoch_types'])}")
    print(f"     Output: {OUTPUT_FILE.relative_to(ROOT)}")


# ---------------------------------------------------------------------
# ENTRYPOINT
# ---------------------------------------------------------------------

if __name__ == "__main__":
    main()