from django.urls import path, include

from afritech.api.afriride_driver_views import (
    active_rides,
    api_root,
    driver_availability,
    driver_earnings,
    driver_queue,
    driver_replay_history,
    driver_status,
    evidence_pipeline,
    guard_violations,
    pilot_evidence,
    replay_health,
    ride_accept,
    ride_arrive,
    ride_complete,
    ride_reject,
    ride_start,
)
from afritech.api.trust_kernel_views import verify_event_view
from afritech.api.trust_graph_views import (
    governance_pending_requests_view,
    governance_rollback_view,
    governance_rule_save_view,
    governance_rule_submit_view,
    governance_rules_view,
    governance_vote_view,
    governance_votes_view,
    proof_certificate_view,
    risk_scores_view,
    rule_dependency_add_view,
    rule_graph_view,
    rule_impact_view,
    trust_conversation_view,
    trust_converse_view,
    trust_graph_view,
    trust_history_view,
    trust_node_view,
    trust_process_view,
    trust_simulate_view,
)

urlpatterns = [
    path("", api_root),
    path("api/", include("afritech.api.urls")),
    path("verify/<uuid:event_id>", verify_event_view),
    path("driver/availability", driver_availability),
    path("driver/status", driver_status),
    path("driver/<str:driver_id>/queue", driver_queue),
    path("driver/<str:driver_id>/earnings", driver_earnings),
    path("driver/replay-history", driver_replay_history),
    path("rides/active", active_rides),
    path("system/replay/health", replay_health),
    path("system/evidence", evidence_pipeline),
    path("pilot/evidence", pilot_evidence),
    path("system/guards", guard_violations),
    path("trust/graph", trust_graph_view),
    path("trust/history", trust_history_view),
    path("trust/node/<str:node_id>", trust_node_view),
    path("trust/process", trust_process_view),
    path("trust/conversation", trust_conversation_view),
    path("trust/converse", trust_converse_view),
    path("trust/rules", governance_rules_view),
    path("trust/rules/save", governance_rule_save_view),
    path("trust/rules/<str:version_id>/submit", governance_rule_submit_view),
    path("trust/change-requests/pending", governance_pending_requests_view),
    path("trust/change-requests/<str:request_id>/vote", governance_vote_view),
    path("trust/change-requests/<str:request_id>/votes", governance_votes_view),
    path("trust/rules/<str:rule_name>/rollback", governance_rollback_view),
    path("trust/simulate", trust_simulate_view),
    path("trust/rule-graph", rule_graph_view),
    path("trust/rule-graph/dependency", rule_dependency_add_view),
    path("trust/impact/<str:rule_name>", rule_impact_view),
    path("trust/risk", risk_scores_view),
    path("trust/proof/<str:proposal_id>", proof_certificate_view),
    path("ride/<str:ride_id>/accept", ride_accept),
    path("ride/<str:ride_id>/reject", ride_reject),
    path("ride/arrive", ride_arrive),
    path("ride/<str:ride_id>/start", ride_start),
    path("ride/<str:ride_id>/complete", ride_complete),
]
