import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const agentBankingTemplates = [
  scenarioTemplate({
    title: "Cash In at Agent",
    actors: ["Customer", "Agent", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Agent Network", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I deposit cash into my wallet through an approved agent.",
    preconditions: ["Agent is approved", "Customer account is active", "Cash amount is valid"],
    workflowSteps: ["Choose cash in", "Enter amount", "Verify customer", "Receive cash", "Confirm deposit", "Store receipt"],
    expectedOutcome: "Wallet is credited and the cash-in receipt is recorded.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Agent Verification", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "Medium",
    complianceTags: ["Cash In", "Agent", "Wallet"],
    independenceRule: "Agent banking remains a NovaPay service and does not require NovaRide.",
  }),
  scenarioTemplate({
    title: "Cash Out at Agent",
    actors: ["Customer", "Agent", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Agent Network", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I withdraw wallet funds as cash from an approved agent.",
    preconditions: ["Wallet balance is sufficient", "Agent is verified", "Withdrawal limits permit the request"],
    workflowSteps: ["Choose cash out", "Enter amount", "Authenticate", "Agent validates", "Release cash", "Issue receipt"],
    expectedOutcome: "Wallet is debited and the cash-out evidence is retained.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Agent Verification", "Device Trust"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "High",
    complianceTags: ["Cash Out", "Agent", "Fraud"],
    independenceRule: "Cash-out controls belong to NovaPay agent banking only.",
  }),
  scenarioTemplate({
    title: "Agent Onboarding Support",
    actors: ["Agent", "Supervisor", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Compliance Console", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As an agent supervisor, I help onboard a new agent location and approve its operating profile.",
    preconditions: ["Business documents are available", "Supervisor is authorized", "Location is within a supported corridor"],
    workflowSteps: ["Create agent profile", "Verify documents", "Set float limits", "Authenticate", "Approve onboarding", "Activate location"],
    expectedOutcome: "The agent location becomes available for cash-in and cash-out services.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYB", "AML", "Agent Approval", "Location Verification"],
    uiSurfaces: ["Agent Console", "Supervisor Console", "Web Portal"],
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "Medium",
    complianceTags: ["Agent", "Onboarding", "KYB"],
    independenceRule: "Agent onboarding is a payment support workflow, not a mobility workflow.",
  }),
] as const;

export const agentBankingCatalog = buildScenarioCatalog("Agent Banking", "NP-AGT", agentBankingTemplates, 40);
