import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const apiIntegrationTestingTemplates = [
  scenarioTemplate({
    title: "Payments API Contract Test",
    actors: ["API Client", "NovaID", "NovaPay", "NovaAI"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "API Gateway"],
    primaryProductOwner: "NovaPay",
    userStory: "As an integration engineer, I verify the payment API contract against the approved schema.",
    preconditions: ["Sandbox credentials exist", "Schema is published", "Client is authorized"],
    workflowSteps: ["Authenticate client", "Submit API request", "Validate response", "Review evidence", "Check advisory output", "Store result"],
    expectedOutcome: "The contract test passes and NovaAI remains advisory only.",
    evidenceRequired: standardEvidence,
    policyChecks: ["Schema Validation", "Advisory Only", "Auth", "Audit"],
    uiSurfaces: ["Developer Portal", "Test Console", "Web Portal"],
    apiSurfaces: standardApiSurfaces,
    testType: "API",
    riskLevel: "Low",
    complianceTags: ["API", "Contract", "NovaAI-Advisory"],
    independenceRule: "API testing exercises NovaPay endpoints without requiring NovaRide.",
  }),
  scenarioTemplate({
    title: "Notification Webhook Test",
    actors: ["API Client", "NovaPay", "NovaTrust", "NovaAI"],
    productsUsed: ["NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "API Gateway", "Notification Hub"],
    primaryProductOwner: "NovaPay",
    userStory: "As an integration engineer, I validate notification webhooks and delivery receipts.",
    preconditions: ["Webhook endpoint is registered", "Signing key is configured", "Client can receive callbacks"],
    workflowSteps: ["Trigger event", "Verify signature", "Inspect payload", "Review advisory summary", "Persist response", "Assert delivery"],
    expectedOutcome: "The webhook is delivered with signed evidence and no decision is made by NovaAI.",
    evidenceRequired: standardEvidence,
    policyChecks: ["Webhook Validation", "Advisory Only", "Signature Verification", "Audit"],
    uiSurfaces: ["Developer Portal", "Webhook Console", "Operations Console"],
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Low",
    complianceTags: ["API", "Webhook", "NovaAI-Advisory"],
    independenceRule: "Webhook testing stays within the platform SDK and does not invoke mobility flows.",
  }),
  scenarioTemplate({
    title: "Auth Session Test",
    actors: ["API Client", "NovaID", "NovaPay", "NovaAI"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "API Gateway"],
    primaryProductOwner: "NovaID",
    userStory: "As an integration engineer, I verify a shared authentication session and consent grant.",
    preconditions: ["Client has credentials", "Consent is granted", "Session policy is published"],
    workflowSteps: ["Request auth", "Validate consent", "Issue session", "Review advisory note", "Call payment API", "Store audit trail"],
    expectedOutcome: "The session is accepted and the API response is traceable.",
    evidenceRequired: standardEvidence,
    policyChecks: ["Auth Policy", "Consent", "Advisory Only", "Audit"],
    uiSurfaces: ["Developer Portal", "Identity Console", "Test Console"],
    apiSurfaces: standardApiSurfaces,
    testType: "Production Certification",
    riskLevel: "Medium",
    complianceTags: ["API", "Authentication", "Consent", "NovaAI-Advisory"],
    independenceRule: "API certification checks shared services without merging product domains.",
  }),
] as const;

export const apiIntegrationTestingCatalog = buildScenarioCatalog("API / Integration Testing", "NP-API", apiIntegrationTestingTemplates, 100);
