import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const businessPaymentsTemplates = [
  scenarioTemplate({
    title: "Supplier Settlement",
    actors: ["Finance Manager", "Supplier", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Ledger"],
    primaryProductOwner: "NovaPay",
    userStory: "As a finance manager, I pay an approved supplier invoice.",
    preconditions: ["Business account exists", "Supplier is onboarded", "Approval is granted"],
    workflowSteps: ["Open business payments", "Select supplier", "Review invoice", "Authenticate", "Submit payment", "Track settlement"],
    expectedOutcome: "The supplier is paid and the business ledger is updated.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYB", "AML", "Approvals", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "Medium",
    complianceTags: ["Supplier", "Settlement", "Audit"],
    independenceRule: "Supplier payments remain in NovaPay Business and do not depend on NovaRide.",
  }),
  scenarioTemplate({
    title: "Payroll Batch Payment",
    actors: ["Payroll Officer", "Employee", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Payroll Engine"],
    primaryProductOwner: "NovaPay",
    userStory: "As a payroll officer, I process a business salary batch.",
    preconditions: ["Payroll file is prepared", "Approvals are present", "Sufficient funds are available"],
    workflowSteps: ["Upload payroll", "Validate batch", "Review exceptions", "Authenticate", "Release batch", "Send payslips"],
    expectedOutcome: "Employees receive payment and payroll evidence is archived.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYB", "AML", "Payroll Approval", "Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "High",
    complianceTags: ["Payroll", "Business", "Evidence"],
    independenceRule: "Payroll execution is a NovaPay business service, not a mobility feature.",
  }),
  scenarioTemplate({
    title: "Business Refund",
    actors: ["Business Operator", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a business operator, I issue a customer refund after an approved case.",
    preconditions: ["Case is approved", "Original payment exists", "Operator is authorized"],
    workflowSteps: ["Open case", "Choose refund", "Review reference", "Authenticate", "Confirm", "Notify customer"],
    expectedOutcome: "Refund settles with a signed receipt and updated ledger entry.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYB", "AML", "Refund Policy", "Case Approval"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Medium",
    complianceTags: ["Refund", "Business", "Case Management"],
    independenceRule: "Business refund flows remain inside NovaPay and outside NovaRide.",
  }),
] as const;

export const businessPaymentsCatalog = buildScenarioCatalog("Business Payments", "NP-BIZ", businessPaymentsTemplates, 50);
