import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const cardsTemplates = [
  scenarioTemplate({
    title: "Link Debit Card",
    actors: ["Customer", "Issuer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Card Network", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I link a debit card for funding wallet actions.",
    preconditions: ["Card is supported", "Customer is verified", "Issuer responds successfully"],
    workflowSteps: ["Open cards", "Add card", "Authenticate", "Verify card", "Save funding source", "Confirm link"],
    expectedOutcome: "The card becomes an approved funding method.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Card Verification", "Device Trust"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "UI",
    riskLevel: "Low",
    complianceTags: ["Cards", "Funding", "Wallet"],
    independenceRule: "Card linking is a NovaPay feature and does not require NovaRide.",
  }),
  scenarioTemplate({
    title: "Card Payment Refund",
    actors: ["Merchant", "Customer", "Issuer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Card Network", "Ledger"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I receive a card payment refund into my wallet or card rail.",
    preconditions: ["Original card payment exists", "Refund policy allows it", "Issuer accepts reversal"],
    workflowSteps: ["Open transaction", "Choose refund", "Authenticate", "Submit reversal", "Wait for settlement", "Review receipt"],
    expectedOutcome: "Refund status is recorded and the customer can view the evidence trail.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Refund Policy", "Card Network Rules"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Medium",
    complianceTags: ["Cards", "Refund", "Settlement"],
    independenceRule: "Card operations remain within NovaPay and external card rails.",
  }),
  scenarioTemplate({
    title: "Card Controls Update",
    actors: ["Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Risk Engine", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I freeze or unfreeze a linked card and review security controls.",
    preconditions: ["Card is linked", "Customer is authenticated", "Account is in good standing"],
    workflowSteps: ["Open card controls", "Review status", "Choose freeze or unfreeze", "Authenticate", "Save changes", "Confirm update"],
    expectedOutcome: "Card state changes securely and the action is logged.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "Device Trust", "Transaction Limits", "Fraud Monitoring"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Security",
    riskLevel: "Medium",
    complianceTags: ["Cards", "Controls", "Risk"],
    independenceRule: "Card controls are a wallet-side capability only.",
  }),
] as const;

export const cardsCatalog = buildScenarioCatalog("Cards", "NP-CARD", cardsTemplates, 40);
