import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const complianceAmlTemplates = [
  scenarioTemplate({
    title: "Enhanced Due Diligence Review",
    actors: ["Compliance Analyst", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Compliance Engine", "Audit Log"],
    primaryProductOwner: "NovaPay",
    userStory: "As a compliance analyst, I review a high-risk account for enhanced due diligence.",
    preconditions: ["Case is opened", "Analyst is authorized", "Evidence is available"],
    workflowSteps: ["Open case", "Review profile", "Check evidence", "Authenticate", "Record decision", "Close case"],
    expectedOutcome: "The case is resolved with a retained compliance record.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "EDD", "Sanctions", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "High",
    complianceTags: ["AML", "EDD", "Case Management"],
    independenceRule: "Compliance review is a shared control plane workflow and not a mobility feature.",
  }),
  scenarioTemplate({
    title: "Sanctions Screening",
    actors: ["Compliance Analyst", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Screening Engine", "Audit Log"],
    primaryProductOwner: "NovaPay",
    userStory: "As a compliance analyst, I inspect a transaction that triggered sanctions screening.",
    preconditions: ["Transaction exists", "Screening job ran", "Analyst has access"],
    workflowSteps: ["Open screening alert", "Review match", "Authenticate", "Validate evidence", "Approve or escalate", "Record outcome"],
    expectedOutcome: "The transaction is either cleared or escalated with a signed audit trail.",
    evidenceRequired: standardEvidence,
    policyChecks: ["AML", "Sanctions", "Manual Review", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Security",
    riskLevel: "Critical",
    complianceTags: ["AML", "Sanctions", "Screening"],
    independenceRule: "Screening decisions stay inside NovaPay compliance tooling.",
  }),
  scenarioTemplate({
    title: "Case Escalation",
    actors: ["Compliance Analyst", "Supervisor", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Case Management", "Audit Log"],
    primaryProductOwner: "NovaPay",
    userStory: "As a compliance analyst, I escalate a suspicious case to a supervisor.",
    preconditions: ["Case is open", "Escalation policy exists", "Supervisor is available"],
    workflowSteps: ["Open case", "Add evidence", "Select escalation", "Authenticate", "Submit", "Notify supervisor"],
    expectedOutcome: "The case is escalated with a complete record and no product boundary violation.",
    evidenceRequired: standardEvidence,
    policyChecks: ["AML", "CDD", "Escalation", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Medium",
    complianceTags: ["AML", "Case", "Escalation"],
    independenceRule: "Compliance escalation does not create rides, identity accounts, or product coupling.",
  }),
] as const;

export const complianceAmlCatalog = buildScenarioCatalog("Compliance / AML", "NP-COM", complianceAmlTemplates, 60);
