import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardPolicyChecks, standardUiSurfaces } from "../scenarioFixtures";

const consumerRemittanceTemplates = [
  scenarioTemplate({
    title: "Family Support Transfer",
    actors: ["Sender", "Recipient", "NovaID", "NovaPay", "NovaTrust"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Notification Hub"],
    primaryProductOwner: "NovaPay",
    userStory: "As a migrant worker, I send money home with transparent pricing and verified receipt evidence.",
    preconditions: ["NovaID Personal is verified", "NovaPay wallet is active", "Recipient profile exists"],
    workflowSteps: ["Open NovaPay", "Select Send Money", "Choose recipient", "Review pricing", "Authenticate", "Confirm transfer"],
    expectedOutcome: "The remittance completes with settlement, notification, and receipt evidence.",
    evidenceRequired: standardEvidence,
    policyChecks: standardPolicyChecks,
    uiSurfaces: ["Consumer App", "Web Portal", "Receipt Screen"],
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "Low",
    complianceTags: ["KYC", "AML", "Sanctions", "Remittance"],
    independenceRule: "NovaPay executes the transfer independently of NovaRide.",
  }),
  scenarioTemplate({
    title: "Salary Remittance",
    actors: ["Sender", "Employer", "Recipient", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I remit part of my salary to family in another country.",
    preconditions: ["Sender is authenticated", "Destination corridor is supported", "Wallet balance is sufficient"],
    workflowSteps: ["Open wallet", "Choose corridor", "Enter amount", "Review fees", "Approve payment", "Track settlement"],
    expectedOutcome: "Funds are delivered through the selected payout method and a receipt is issued.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Sanctions", "Transaction Limits", "Velocity"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Low",
    complianceTags: ["Remittance", "Payroll-like Support", "KYC", "AML"],
    independenceRule: "The journey remains a payment workflow, not a mobility workflow.",
  }),
  scenarioTemplate({
    title: "Education Fee Transfer",
    actors: ["Payer", "Student", "Institution", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Notification Hub"],
    primaryProductOwner: "NovaPay",
    userStory: "As a parent, I pay education fees directly to a school or university.",
    preconditions: ["Institution account is configured", "Payer is verified", "Amount is within limits"],
    workflowSteps: ["Select institution payment", "Search institution", "Enter student reference", "Review amount", "Authenticate", "Submit payment"],
    expectedOutcome: "The institution receives settlement and the payer receives a signed receipt.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Institution Verification", "Transaction Limits"],
    uiSurfaces: ["Consumer App", "Institution Portal", "Receipt View"],
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Medium",
    complianceTags: ["Education", "Cross-border", "Receipt", "Audit"],
    independenceRule: "NovaPay handles the educational payment while NovaRide remains unused.",
  }),
  scenarioTemplate({
    title: "Cash Pickup Remittance",
    actors: ["Sender", "Recipient", "Agent", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Notification Hub"],
    primaryProductOwner: "NovaPay",
    userStory: "As a sender, I deliver cash pickup funds to a first-time recipient without a wallet.",
    preconditions: ["Pickup corridor is enabled", "Recipient details are valid", "Compliance checks pass"],
    workflowSteps: ["Choose cash pickup", "Enter recipient details", "Review fees", "Authenticate", "Confirm transfer", "Send pickup code"],
    expectedOutcome: "Recipient can collect funds from an approved agent after identity verification.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Recipient Verification", "Cash Pickup Controls"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "High",
    complianceTags: ["Cash Pickup", "Remittance", "Agent", "Audit"],
    independenceRule: "The transfer remains a NovaPay remittance and does not depend on NovaRide.",
  }),
  scenarioTemplate({
    title: "Mobile Money Remittance",
    actors: ["Sender", "Recipient", "Mobile Money Partner", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I send funds into a mobile money wallet through a supported corridor.",
    preconditions: ["Partner network is live", "Wallet is funded", "Destination wallet exists"],
    workflowSteps: ["Choose mobile money payout", "Enter amount", "Review FX", "Authenticate", "Confirm", "Track settlement"],
    expectedOutcome: "The recipient wallet is credited and the sender can view a verified receipt.",
    evidenceRequired: standardEvidence,
    policyChecks: standardPolicyChecks,
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Mobile",
    riskLevel: "Low",
    complianceTags: ["Remittance", "Mobile Money", "Settlement", "Receipt"],
    independenceRule: "NovaPay uses partner rails only; NovaRide is not involved.",
  }),
] as const;

export const consumerRemittanceCatalog = buildScenarioCatalog("Consumer Remittance", "NP-CR", consumerRemittanceTemplates, 100);
