import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const customerSupportTemplates = [
  scenarioTemplate({
    title: "Transaction Dispute",
    actors: ["Customer", "Support Agent", "NovaID", "NovaPay", "NovaAI"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "Case Management"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I raise a transaction dispute and receive guided support.",
    preconditions: ["Transaction exists", "Support case is open", "Customer identity is verified"],
    workflowSteps: ["Open dispute", "Review transaction", "Review advisory summary", "Authenticate", "Submit case", "Track resolution"],
    expectedOutcome: "The dispute is logged and NovaAI only offers advisory guidance.",
    evidenceRequired: standardEvidence,
    policyChecks: ["MFA", "Dispute Policy", "Advisory Only", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "Medium",
    complianceTags: ["Support", "Dispute", "NovaAI-Advisory"],
    independenceRule: "Support automation may advise, but only human agents resolve cases.",
  }),
  scenarioTemplate({
    title: "Account Recovery",
    actors: ["Customer", "Support Agent", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Security Alerts", "Case Management"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I recover access to my wallet after losing a device.",
    preconditions: ["Recovery contact exists", "Customer can prove identity", "Security checks pass"],
    workflowSteps: ["Open recovery", "Verify identity", "Review trusted devices", "Authenticate", "Reset access", "Send alert"],
    expectedOutcome: "Access is restored and the recovery action is fully audited.",
    evidenceRequired: standardEvidence,
    policyChecks: ["MFA", "Device Trust", "Recovery Policy", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Security",
    riskLevel: "High",
    complianceTags: ["Support", "Recovery", "Security"],
    independenceRule: "Recovery is a support workflow within NovaPay, not a product merger.",
  }),
  scenarioTemplate({
    title: "Receipt Reissue",
    actors: ["Customer", "Support Agent", "NovaID", "NovaPay", "NovaTrust"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Document Service", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I request a reissued receipt for a past transaction.",
    preconditions: ["Original transaction exists", "Customer is authenticated", "Receipt retention applies"],
    workflowSteps: ["Open receipt help", "Search transaction", "Authenticate", "Request reissue", "Download document", "Close case"],
    expectedOutcome: "A reissued receipt is delivered with the original evidence reference.",
    evidenceRequired: standardEvidence,
    policyChecks: ["MFA", "Receipt Access", "Audit", "Retention"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Accessibility",
    riskLevel: "Low",
    complianceTags: ["Support", "Receipt", "Audit"],
    independenceRule: "Receipt servicing remains within NovaPay support tooling.",
  }),
] as const;

export const customerSupportCatalog = buildScenarioCatalog("Customer Support", "NP-SUP", customerSupportTemplates, 40);
