import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const fraudRiskTemplates = [
  scenarioTemplate({
    title: "Suspicious Login Review",
    actors: ["Fraud Analyst", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Risk Engine", "Security Alerts"],
    primaryProductOwner: "NovaPay",
    userStory: "As a fraud analyst, I investigate a suspicious login sequence.",
    preconditions: ["Alert exists", "Analyst is authorized", "Evidence was collected"],
    workflowSteps: ["Open alert", "Review device signals", "Authenticate", "Assess risk", "Record decision", "Close case"],
    expectedOutcome: "The account is protected and the investigation trail is retained.",
    evidenceRequired: standardEvidence,
    policyChecks: ["MFA", "Device Trust", "Fraud", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Security",
    riskLevel: "High",
    complianceTags: ["Fraud", "Login", "Security"],
    independenceRule: "Fraud review remains inside NovaPay risk tooling.",
  }),
  scenarioTemplate({
    title: "Velocity Rule Review",
    actors: ["Risk Analyst", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Risk Engine", "Audit Log"],
    primaryProductOwner: "NovaPay",
    userStory: "As a risk analyst, I review a velocity-based transaction alert.",
    preconditions: ["Velocity threshold triggered", "Analyst access is approved", "Customer history is available"],
    workflowSteps: ["Open velocity alert", "Review history", "Authenticate", "Assess pattern", "Escalate or clear", "Save outcome"],
    expectedOutcome: "A clear decision is stored with evidence for later audit.",
    evidenceRequired: standardEvidence,
    policyChecks: ["AML", "Fraud", "Velocity", "Manual Review"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "Critical",
    complianceTags: ["Fraud", "Velocity", "Monitoring"],
    independenceRule: "Velocity monitoring is a payment risk control only.",
  }),
  scenarioTemplate({
    title: "Device Change Alert",
    actors: ["Customer", "Fraud Analyst", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Security Alerts", "Audit Log"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I confirm or deny a device change alert.",
    preconditions: ["New device was detected", "Alert is active", "Customer can review it"],
    workflowSteps: ["Open alert", "Review device", "Authenticate", "Confirm or deny", "Update trust score", "Store evidence"],
    expectedOutcome: "The customer controls trust state and the action is logged.",
    evidenceRequired: standardEvidence,
    policyChecks: ["Device Trust", "MFA", "Fraud", "Account Recovery"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Medium",
    complianceTags: ["Fraud", "Device", "Recovery"],
    independenceRule: "Device changes are security controls, not ride features.",
  }),
] as const;

export const fraudRiskCatalog = buildScenarioCatalog("Fraud & Risk", "NP-FRD", fraudRiskTemplates, 60);
