import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const governmentServicesTemplates = [
  scenarioTemplate({
    title: "Tax Payment",
    actors: ["Citizen", "Tax Authority", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a citizen, I pay a tax liability through a government service.",
    preconditions: ["Tax bill is available", "Citizen is verified", "Government account exists"],
    workflowSteps: ["Open government services", "Select tax payment", "Review bill", "Authenticate", "Submit payment", "Store receipt"],
    expectedOutcome: "The tax authority receives settlement and the payment record is auditable.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Government Verification", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "Medium",
    complianceTags: ["Government", "Tax", "Receipt"],
    independenceRule: "Government payments remain within NovaPay and do not depend on NovaRide.",
  }),
  scenarioTemplate({
    title: "Passport Fee Payment",
    actors: ["Applicant", "Agency", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Government Registry", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As an applicant, I pay a passport fee to a government agency.",
    preconditions: ["Application exists", "Fee is known", "Applicant is authenticated"],
    workflowSteps: ["Open fee payment", "Select passport", "Enter reference", "Authenticate", "Pay", "Download confirmation"],
    expectedOutcome: "The government agency receives payment and the application advances.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Government Verification", "Reference Validation"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Low",
    complianceTags: ["Government", "Passport", "Document"],
    independenceRule: "Document fee payment remains a NovaPay capability.",
  }),
  scenarioTemplate({
    title: "Permit Renewal",
    actors: ["Citizen", "Government Officer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Government Registry", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a citizen, I renew a permit and pay the required fee.",
    preconditions: ["Permit is eligible for renewal", "Applicant is verified", "Outstanding fee exists"],
    workflowSteps: ["Open permit renewal", "Review fee", "Authenticate", "Submit payment", "Receive receipt", "Track status"],
    expectedOutcome: "The permit renewal remains traceable with signed evidence.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Government Verification", "Audit Logging"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "Medium",
    complianceTags: ["Government", "Renewal", "Audit"],
    independenceRule: "Permit workflows are payment-only in NovaPay.",
  }),
] as const;

export const governmentServicesCatalog = buildScenarioCatalog("Government Services", "NP-GOV", governmentServicesTemplates, 40);
