import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const insuranceTemplates = [
  scenarioTemplate({
    title: "Premium Payment",
    actors: ["Policyholder", "Insurer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a policyholder, I pay an insurance premium from my wallet.",
    preconditions: ["Policy exists", "Premium is due", "Customer is verified"],
    workflowSteps: ["Open insurance", "Select premium", "Review policy", "Authenticate", "Pay premium", "Store receipt"],
    expectedOutcome: "The insurer receives funds and the premium status updates.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Policy Validation", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Low",
    complianceTags: ["Insurance", "Premium", "Receipt"],
    independenceRule: "Premium payments are a NovaPay workflow only.",
  }),
  scenarioTemplate({
    title: "Claim Payout",
    actors: ["Insurer", "Policyholder", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Claims System", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a policyholder, I receive a claim payout into my selected account.",
    preconditions: ["Claim is approved", "Payment rail is available", "Customer details are valid"],
    workflowSteps: ["Open claim payout", "Review approval", "Choose payout destination", "Authenticate", "Confirm", "Track settlement"],
    expectedOutcome: "Payout is delivered and the evidence package is stored.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Claim Approval", "Disbursement Rules"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "Medium",
    complianceTags: ["Insurance", "Claims", "Disbursement"],
    independenceRule: "Claim payouts stay inside NovaPay and its supported payout rails.",
  }),
  scenarioTemplate({
    title: "Policy Renewal Advisory",
    actors: ["Policyholder", "NovaAI", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "Analytics"],
    primaryProductOwner: "NovaPay",
    userStory: "As a policyholder, I review renewal options with advisory guidance.",
    preconditions: ["Policy is approaching renewal", "Customer is verified", "Renewal options exist"],
    workflowSteps: ["Open renewal", "Review options", "Review advisory insight", "Authenticate", "Select option", "Confirm renewal"],
    expectedOutcome: "The customer makes the final decision and NovaAI remains advisory only.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Advisory Only", "Renewal Rules"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "Low",
    complianceTags: ["Insurance", "Advisory", "NovaAI-Advisory"],
    independenceRule: "NovaAI may guide renewal selection but cannot bind the policyholder.",
  }),
] as const;

export const insuranceCatalog = buildScenarioCatalog("Insurance", "NP-INS", insuranceTemplates, 30);
