import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const lendingTemplates = [
  scenarioTemplate({
    title: "Personal Loan Application",
    actors: ["Customer", "Lender", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Credit Decisioning", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I apply for a personal loan with transparent eligibility checks.",
    preconditions: ["Customer is verified", "Loan product exists", "Required disclosures are shown"],
    workflowSteps: ["Open lending", "Review offer", "Enter amount", "Authenticate", "Submit application", "Track decision"],
    expectedOutcome: "The application is recorded and the decision evidence is retained.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Credit Policy", "Affordability"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Medium",
    complianceTags: ["Lending", "Credit", "Audit"],
    independenceRule: "Lending decisions remain inside NovaPay and are not delegated to NovaRide.",
  }),
  scenarioTemplate({
    title: "Loan Repayment",
    actors: ["Customer", "Lender", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I repay a loan from my wallet on schedule.",
    preconditions: ["Repayment schedule exists", "Wallet balance is sufficient", "Customer is authenticated"],
    workflowSteps: ["Open loan account", "Select repayment", "Choose funding source", "Authenticate", "Submit payment", "Store receipt"],
    expectedOutcome: "Repayment is posted and the loan ledger updates accordingly.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Repayment Rules", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Low",
    complianceTags: ["Loan", "Repayment", "Ledger"],
    independenceRule: "Repayment is a financial workflow only.",
  }),
  scenarioTemplate({
    title: "Loan Offer Review",
    actors: ["Customer", "NovaAI", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "Analytics"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I review a prequalified offer with advisory assistance.",
    preconditions: ["Offer is generated", "Customer is eligible to view it", "Risk disclosures are visible"],
    workflowSteps: ["Open offer", "Review terms", "Review advisory insight", "Authenticate", "Accept or decline", "Archive decision"],
    expectedOutcome: "The customer chooses explicitly and NovaAI remains advisory only.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Advisory Only", "Suitability Disclosure"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "Medium",
    complianceTags: ["Lending", "Advice", "NovaAI-Advisory"],
    independenceRule: "NovaAI can suggest but cannot approve, disburse, or collect loans.",
  }),
] as const;

export const lendingCatalog = buildScenarioCatalog("Lending", "NP-LEND", lendingTemplates, 30);
