import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const merchantPaymentsTemplates = [
  scenarioTemplate({
    title: "QR Checkout",
    actors: ["Customer", "Merchant", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Merchant Acquirer", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a shopper, I pay a merchant by scanning a QR code.",
    preconditions: ["Merchant QR is generated", "Customer wallet is active", "Amount is known"],
    workflowSteps: ["Merchant shows QR", "Customer scans QR", "Review amount", "Authenticate", "Approve payment", "Receive receipt"],
    expectedOutcome: "The merchant is credited and the customer receives a verified receipt.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Device Trust", "Merchant Verification"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Mobile",
    riskLevel: "Low",
    complianceTags: ["Merchant", "QR", "Point of Sale"],
    independenceRule: "Retail payments are handled by NovaPay and do not involve NovaRide.",
  }),
  scenarioTemplate({
    title: "Invoice Payment",
    actors: ["Customer", "Merchant", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a business customer, I settle an invoice with a merchant reference.",
    preconditions: ["Invoice exists", "Customer is authorized", "Limit checks pass"],
    workflowSteps: ["Open invoice payment", "Enter invoice reference", "Confirm amount", "Authenticate", "Submit payment", "Track settlement"],
    expectedOutcome: "Invoice is settled and the payment record is retrievable.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Invoice Validation", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Medium",
    complianceTags: ["Invoice", "Merchant", "Settlement"],
    independenceRule: "The invoice flow remains a NovaPay merchant-payment workflow.",
  }),
  scenarioTemplate({
    title: "Refund to Customer",
    actors: ["Merchant", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a merchant, I reverse a transaction and return funds to the customer.",
    preconditions: ["Original payment exists", "Refund policy allows reversal", "Actor is authorized"],
    workflowSteps: ["Open payment history", "Select refund", "Enter reason", "Authenticate", "Confirm refund", "Notify customer"],
    expectedOutcome: "The customer receives the refund and an audit trail is retained.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Refund Policy", "Authorization"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Low",
    complianceTags: ["Refund", "Merchant", "Audit"],
    independenceRule: "Refund handling is a payment operation with no ride dependency.",
  }),
] as const;

export const merchantPaymentsCatalog = buildScenarioCatalog("Merchant Payments", "NP-MER", merchantPaymentsTemplates, 50);
