import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const payrollTemplates = [
  scenarioTemplate({
    title: "Payroll Batch Release",
    actors: ["Payroll Officer", "Employee", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Ledger"],
    primaryProductOwner: "NovaPay",
    userStory: "As a payroll officer, I release an approved payroll batch.",
    preconditions: ["Batch is approved", "Funding is available", "Officer is authorized"],
    workflowSteps: ["Upload batch", "Validate entries", "Review exceptions", "Authenticate", "Release batch", "Send payslips"],
    expectedOutcome: "Employees receive salary payments and payroll evidence is archived.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYB", "AML", "Payroll Approval", "Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "High",
    complianceTags: ["Payroll", "Salary", "Audit"],
    independenceRule: "Payroll is a financial disbursement workflow and not a mobility workflow.",
  }),
  scenarioTemplate({
    title: "Payroll Exception Review",
    actors: ["Payroll Officer", "Employee", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaPower", "NovaTrust", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a payroll officer, I resolve failed payroll rows before release.",
    preconditions: ["Batch contains an exception", "Officer can edit the row", "Approvals are in place"],
    workflowSteps: ["Open exceptions", "Review failed row", "Correct details", "Authenticate", "Save change", "Re-run batch"],
    expectedOutcome: "The corrected row can be processed and tracked in audit logs.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYB", "AML", "Exception Approval", "Limit Checks"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Medium",
    complianceTags: ["Payroll", "Exceptions", "Audit"],
    independenceRule: "Exception handling remains in NovaPay payroll tooling.",
  }),
  scenarioTemplate({
    title: "Payslip Retrieval",
    actors: ["Employee", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Document Service", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As an employee, I retrieve a digital payslip from the payroll archive.",
    preconditions: ["Payroll exists", "Employee is authorized", "Document retention is enabled"],
    workflowSteps: ["Open payslips", "Select period", "Authenticate", "Download document", "Review receipt", "Close session"],
    expectedOutcome: "Payslip is downloaded and the access event is retained.",
    evidenceRequired: standardEvidence,
    policyChecks: ["MFA", "Document Access", "Audit Logging", "Retention"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Accessibility",
    riskLevel: "Low",
    complianceTags: ["Payroll", "Document", "Audit"],
    independenceRule: "Document retrieval does not require NovaRide.",
  }),
] as const;

export const payrollCatalog = buildScenarioCatalog("Payroll", "NP-PAY", payrollTemplates, 30);
