import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const recoveryDisasterTemplates = [
  scenarioTemplate({
    title: "Service Outage Fallback",
    actors: ["Customer", "Operations", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Status Page", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I continue using service during a degraded outage state.",
    preconditions: ["Primary region is degraded", "Fallback route is available", "Customer is authenticated"],
    workflowSteps: ["Open app", "View status", "Switch to fallback", "Authenticate", "Continue transfer", "Store evidence"],
    expectedOutcome: "The platform records degraded-mode execution without losing transaction evidence.",
    evidenceRequired: standardEvidence,
    policyChecks: ["Service Continuity", "MFA", "Audit", "Fallback Controls"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Performance",
    riskLevel: "High",
    complianceTags: ["Recovery", "Outage", "Continuity"],
    independenceRule: "Resilience controls keep NovaPay functional without merging other products.",
  }),
  scenarioTemplate({
    title: "Wallet Restore After Device Loss",
    actors: ["Customer", "Support Agent", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Security Alerts", "Case Management"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I restore wallet access on a replacement device.",
    preconditions: ["Device loss was reported", "Recovery checks are complete", "Customer can prove identity"],
    workflowSteps: ["Open recovery", "Verify identity", "Review security history", "Authenticate", "Register new device", "Resume service"],
    expectedOutcome: "Wallet access is restored and the old device is revoked.",
    evidenceRequired: standardEvidence,
    policyChecks: ["MFA", "Device Trust", "Recovery Policy", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Security",
    riskLevel: "High",
    complianceTags: ["Recovery", "Device", "Support"],
    independenceRule: "Recovery flows repair access to NovaPay, not NovaRide.",
  }),
  scenarioTemplate({
    title: "Offline Sync Replay",
    actors: ["Agent", "Customer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Offline Queue", "Audit Log"],
    primaryProductOwner: "NovaPay",
    userStory: "As an operator, I sync offline transactions after connectivity returns.",
    preconditions: ["Offline queue has events", "Network has returned", "Operator is authorized"],
    workflowSteps: ["Reconnect device", "Validate queue", "Authenticate", "Sync events", "Resolve conflicts", "Archive replay evidence"],
    expectedOutcome: "Offline actions synchronize safely with no duplicate settlement.",
    evidenceRequired: standardEvidence,
    policyChecks: ["Sync Integrity", "MFA", "Replay Protection", "Audit"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Medium",
    complianceTags: ["Recovery", "Offline", "Replay"],
    independenceRule: "Disaster recovery preserves financial continuity without cross-product coupling.",
  }),
] as const;

export const recoveryDisasterCatalog = buildScenarioCatalog("Recovery & Disaster", "NP-DR", recoveryDisasterTemplates, 30);
