import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const savingsInvestmentsTemplates = [
  scenarioTemplate({
    title: "Savings Goal Setup",
    actors: ["Customer", "NovaID", "NovaPay", "NovaAI"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "Analytics"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I create a savings goal and receive advisory insights.",
    preconditions: ["Wallet is active", "Customer is verified", "Savings feature is enabled"],
    workflowSteps: ["Open savings", "Create goal", "Set target", "Review advisory insight", "Authenticate", "Save goal"],
    expectedOutcome: "The goal is created and NovaAI provides only advisory guidance.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Advisory Only", "Savings Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "UI",
    riskLevel: "Low",
    complianceTags: ["Savings", "Goal", "NovaAI-Advisory"],
    independenceRule: "NovaAI may suggest savings behavior but cannot approve transactions or identity.",
  }),
  scenarioTemplate({
    title: "Round-up Savings",
    actors: ["Customer", "NovaID", "NovaPay", "NovaAI"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "Analytics"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I enable round-up savings on purchases.",
    preconditions: ["Card or wallet funding is active", "Customer is authenticated", "Round-up policy is enabled"],
    workflowSteps: ["Open savings tools", "Choose round-up", "Review settings", "Review advisory insight", "Authenticate", "Activate"],
    expectedOutcome: "Small savings transfers are created as authorized and auditable wallet actions.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Advisory Only", "Savings Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Low",
    complianceTags: ["Savings", "Automated", "NovaAI-Advisory"],
    independenceRule: "Savings automation remains within NovaPay and does not trigger ride workflows.",
  }),
  scenarioTemplate({
    title: "Investment Transfer Review",
    actors: ["Customer", "Advisor", "NovaID", "NovaPay", "NovaAI"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "NovaAI", "Compliance Engine"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I review an investment transfer with advisory insights before confirmation.",
    preconditions: ["Investment product is available", "Customer is verified", "Risk disclosures are shown"],
    workflowSteps: ["Open investments", "Review proposal", "Review advisory insight", "Authenticate", "Confirm transfer", "Archive evidence"],
    expectedOutcome: "The transfer only proceeds after explicit human confirmation and advisory guidance remains non-binding.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Advisory Only", "Suitability Disclosure"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Compliance",
    riskLevel: "Medium",
    complianceTags: ["Investments", "Advice", "NovaAI-Advisory"],
    independenceRule: "NovaAI informs the decision but never authorizes the investment action.",
  }),
] as const;

export const savingsInvestmentsCatalog = buildScenarioCatalog("Savings & Investments", "NP-SAV", savingsInvestmentsTemplates, 30);
