import { buildScenarioCatalog, scenarioTemplate, standardApiSurfaces, standardEvidence, standardUiSurfaces } from "../scenarioFixtures";

const walletOperationsTemplates = [
  scenarioTemplate({
    title: "Wallet Top Up",
    actors: ["Customer", "Bank", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Ledger", "Notification Hub"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I add funds to my wallet before making payments.",
    preconditions: ["Wallet exists", "Funding source is linked", "Customer is authenticated"],
    workflowSteps: ["Open wallet", "Choose top up", "Select funding source", "Enter amount", "Authenticate", "Confirm"],
    expectedOutcome: "Wallet balance increases and the top-up receipt is stored.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Device Trust", "Funding Source Verification"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Regression",
    riskLevel: "Low",
    complianceTags: ["Wallet", "Top Up", "Ledger", "Receipt"],
    independenceRule: "This is a wallet operation only and does not require NovaRide.",
  }),
  scenarioTemplate({
    title: "Scheduled Transfer",
    actors: ["Customer", "Recipient", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Scheduler", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I schedule recurring transfers to a beneficiary.",
    preconditions: ["Beneficiary exists", "Recurring schedule is allowed", "Customer is verified"],
    workflowSteps: ["Open transfers", "Choose recurring", "Select beneficiary", "Set cadence", "Authenticate", "Save schedule"],
    expectedOutcome: "The schedule is stored and future executions remain auditable.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Transaction Limits", "Recurring Payment Controls"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "Integration",
    riskLevel: "Medium",
    complianceTags: ["Recurring", "Transfers", "Audit"],
    independenceRule: "Recurring wallet actions remain inside NovaPay.",
  }),
  scenarioTemplate({
    title: "Request Money",
    actors: ["Requester", "Payer", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Notification Hub", "Analytics"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I request money from a contact with a verified reference.",
    preconditions: ["Contact is known", "Wallet is active", "Request amount is within limits"],
    workflowSteps: ["Open request money", "Choose contact", "Enter amount", "Add note", "Send request", "Track response"],
    expectedOutcome: "The payer receives a request and the requester can monitor status.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "Fraud", "Velocity", "Request Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "UI",
    riskLevel: "Low",
    complianceTags: ["Wallet", "Request", "Notifications"],
    independenceRule: "Request flows are payment-only and stay outside the ride product.",
  }),
  scenarioTemplate({
    title: "Wallet Withdrawal",
    actors: ["Customer", "Agent", "NovaID", "NovaPay"],
    productsUsed: ["NovaID", "NovaPay"],
    sharedServicesUsed: ["NovaTrust", "Agent Network", "Notifications"],
    primaryProductOwner: "NovaPay",
    userStory: "As a customer, I withdraw wallet balance through an approved agent.",
    preconditions: ["Agent is approved", "Wallet has sufficient balance", "Withdrawal limits allow the request"],
    workflowSteps: ["Select cash out", "Enter amount", "Authenticate", "Present code", "Agent confirms", "Cash is released"],
    expectedOutcome: "Wallet is debited and a withdrawal receipt is stored.",
    evidenceRequired: standardEvidence,
    policyChecks: ["KYC", "AML", "Agent Verification", "Transaction Limits"],
    uiSurfaces: standardUiSurfaces,
    apiSurfaces: standardApiSurfaces,
    testType: "End-to-End",
    riskLevel: "High",
    complianceTags: ["Cash Out", "Agent", "Fraud", "Audit"],
    independenceRule: "Withdrawal processing stays within NovaPay and its agent network.",
  }),
] as const;

export const walletOperationsCatalog = buildScenarioCatalog("Wallet Operations", "NP-WAL", walletOperationsTemplates, 60);
