import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "personal",
  appName: "NovaID Personal",
  packageId: "com.novatech.novaid.personal",
  tagline: "Modern identity wallet, verification, consent, and security for individuals.",
  trustTheme: "#4f7cff",
  tabs: [
    { key: "home", label: "Home", description: "Identity status, trust score, and verified ID." },
    { key: "verify", label: "Verify", description: "Phone, email, document, selfie, and liveness verification." },
    { key: "documents", label: "Documents", description: "Uploaded documents, expiry dates, and receipts." },
    { key: "security", label: "Security", description: "PIN, passkeys, MFA, trusted devices, and recovery." },
    { key: "activity", label: "Activity", description: "Verification history, consent history, and audit logs." },
    { key: "profile", label: "Profile", description: "Profile details, language, privacy, and settings." },
    { key: "wallet", label: "Wallet", description: "Credentials, certificates, and identity wallet history." },
    { key: "share", label: "Share", description: "QR identity sharing and selective disclosure links." },
    { key: "consent", label: "Consent", description: "Connected apps and permission grants." },
  ],
  actions: [
    { label: "View NovaID status", detail: "Open the identity overview and current verification state." },
    { label: "View verification level", detail: "Show the current trust level and verification tier." },
    { label: "Start identity verification", detail: "Launch the full NovaID onboarding flow." },
    { label: "Continue verification", detail: "Resume a paused verification request." },
    { label: "View digital ID", detail: "Open the primary identity card and trust summary." },
    { label: "Share verified ID", detail: "Create a trusted identity share link or QR." },
    { label: "Open security center", detail: "Jump to the PIN, passkey, MFA, and device controls." },
    { label: "Open linked apps", detail: "Review connected services using this identity." },
    { label: "Verify phone number", detail: "Confirm the mobile number with OTP verification." },
    { label: "Verify email", detail: "Confirm the email address with a secure link or code." },
    { label: "Upload government ID", detail: "Upload a government-issued identity document." },
    { label: "Scan passport", detail: "Capture a passport for document validation." },
    { label: "Scan national ID", detail: "Capture a national ID for document validation." },
    { label: "Scan driver licence", detail: "Capture a driver licence for identity checks." },
    { label: "Take selfie", detail: "Capture a selfie for biometric matching." },
    { label: "Start liveness check", detail: "Run a liveness check to confirm a live user." },
    { label: "Match face to ID", detail: "Compare the live face capture with the identity document." },
    { label: "Verify address", detail: "Confirm the residential address used on the profile." },
    { label: "Submit verification", detail: "Send the current verification package for review." },
    { label: "Check verification status", detail: "Refresh the review state and latest policy result." },
    { label: "Upload document", detail: "Attach a supporting document to the identity vault." },
    { label: "View uploaded documents", detail: "Inspect the current uploaded document list." },
    { label: "Replace document", detail: "Replace an outdated or incorrect supporting document." },
    { label: "Delete document", detail: "Remove a stored supporting document." },
    { label: "Download verification receipt", detail: "Export the latest identity verification receipt." },
    { label: "View document expiry", detail: "Review document expiry dates and renewal alerts." },
    { label: "Renew expired document", detail: "Start a renewal action for an expired document." },
    { label: "Create PIN", detail: "Create a new NovaID PIN for sensitive actions." },
    { label: "Change PIN", detail: "Rotate the NovaID PIN." },
    { label: "Enable biometric login", detail: "Turn on biometric authentication for the device." },
    { label: "Enable MFA", detail: "Enable multi-factor authentication for the account." },
    { label: "Manage trusted devices", detail: "Review trusted devices and device trust history." },
    { label: "Remove device", detail: "Remove a device from the trusted set." },
    { label: "View login history", detail: "Inspect the latest login sessions and security events." },
    { label: "Freeze NovaID", detail: "Freeze the identity until a review is completed." },
    { label: "Recover account", detail: "Start account recovery with fallback verification." },
    { label: "View verification history", detail: "Review completed verification events." },
    { label: "View consent history", detail: "Review active and revoked consent grants." },
    { label: "View shared identity records", detail: "Inspect where the identity has been shared." },
    { label: "Revoke shared access", detail: "Revoke an active identity share or consent grant." },
    { label: "Download audit log", detail: "Export the audit trail for the identity profile." },
    { label: "Report suspicious activity", detail: "Flag suspicious identity activity for review." },
    { label: "Edit profile", detail: "Edit the public identity profile and preferences." },
    { label: "Update address", detail: "Change the residential address in the profile." },
    { label: "Update phone number", detail: "Update the mobile number on the account." },
    { label: "Update email", detail: "Update the email address on the account." },
    { label: "Set language", detail: "Choose the preferred language for the app." },
    { label: "Notification settings", detail: "Manage identity notifications and alerts." },
    { label: "Privacy settings", detail: "Manage visibility and consent preferences." },
    { label: "Delete account", detail: "Queue account deletion through the secure flow." },
    { label: "Logout", detail: "End the current NovaID session." },
    { label: "Add Credential", detail: "Attach a new government, student, health, or certificate credential." },
    { label: "Verify Identity", detail: "Run biometric, document, liveness, and policy verification." },
    { label: "Share Identity", detail: "Generate a QR or link with selective disclosure controls." },
    { label: "Scan QR", detail: "Scan a trusted identity QR for fast sharing or verification." },
    { label: "Revoke Access", detail: "Revoke a consent grant or connected app permission." },
    { label: "View Certificate", detail: "Open the latest digital certificate and replay receipt." },
    { label: "Enable Passkey", detail: "Turn on passkey-based authentication for the account." },
    { label: "Manage Devices", detail: "Review trusted devices and device trust history." },
    { label: "Start Recovery", detail: "Start account recovery with support and fallback checks." },
    { label: "Contact Support", detail: "Open support chat and create an assisted recovery ticket." },
  ],
  primaryFlow: [
    "Identity Request",
    "Biometric Verification",
    "Document Validation",
    "Liveness Detection",
    "Policy Evaluation",
    "Identity Approved",
    "Digital Certificate Issued",
  ],
  seed: {
    displayName: "Nova Citizen",
    walletLabel: "Identity wallet",
    trustLevel: "Verified",
    identityScore: 96,
    credentialCount: 5,
    trustedDevices: 2,
    governmentIds: 3,
    certificateCount: 2,
    biometricVerified: true,
    passkeyEnabled: false,
    deviceTrustEnabled: true,
    recoveryEnabled: true,
    connectedApps: 4,
    loginHistory: 18,
  },
};
