import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "personal",
  appName: "NovaID Personal",
  packageId: "com.novatech.novaid.personal",
  tagline: "Digital identity wallet for individuals.",
  trustTheme: "#4f7cff",
  tabs: [
    { key: "home", label: "Home", description: "Identity card, score, and trust level." },
    { key: "wallet", label: "Wallet", description: "Credentials, certificates, and wallets." },
    { key: "share", label: "Share", description: "QR identity sharing and payment-style links." },
    { key: "consent", label: "Consent", description: "Connected apps and permission grants." },
    { key: "security", label: "Security", description: "Passkeys, trusted devices, and recovery." },
    { key: "profile", label: "Profile", description: "Identity history and NovaAI support." },
  ],
  actions: [
    { label: "Add Credential", detail: "Attach a new government, student, health, or certificate credential." },
    { label: "Verify Identity", detail: "Run biometric, document, liveness, and policy verification." },
    { label: "Share Identity", detail: "Generate a QR or link with selective disclosure controls." },
    { label: "Scan QR", detail: "Scan a trusted identity QR for fast sharing or verification." },
    { label: "Revoke Access", detail: "Revoke a consent grant or connected app permission." },
    { label: "View Certificate", detail: "Open the latest digital certificate and replay receipt." },
    { label: "Enable Passkey", detail: "Turn on passkey-based authentication for the account." },
    { label: "Manage Devices", detail: "Review trusted devices and device trust history." },
    { label: "Start Recovery", detail: "Start account recovery with support and fallback checks." },
    { label: "Contact Support", detail: "Open support chat and create an assisted recovery ticket." },
  ],
  primaryFlow: [
    "Identity Request",
    "Biometric Verification",
    "Document Validation",
    "Liveness Detection",
    "Policy Evaluation",
    "Identity Approved",
    "Digital Certificate Issued",
  ],
  seed: {
    displayName: "Nova Citizen",
    walletLabel: "Identity wallet",
    trustLevel: "Verified",
    identityScore: 96,
    credentialCount: 5,
    trustedDevices: 2,
    governmentIds: 3,
    certificateCount: 2,
    biometricVerified: true,
    passkeyEnabled: false,
    deviceTrustEnabled: true,
    recoveryEnabled: true,
    connectedApps: 4,
    loginHistory: 18,
  },
};
