import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "inspector",
  appName: "NovaID Inspector",
  packageId: "com.novatech.novaid.inspector",
  tagline: "Inspection, casework, evidence, compliance, and offline field verification.",
  trustTheme: "#d47b00",
  tabs: [
    { key: "dashboard", label: "Dashboard", description: "Assigned inspections, cases, and alerts." },
    { key: "inspections", label: "Inspections", description: "Create and complete inspection checklists." },
    { key: "cases", label: "Cases", description: "Open, assign, escalate, and resolve cases." },
    { key: "evidence", label: "Evidence", description: "Upload and lock evidence for the evidence chain." },
    { key: "reports", label: "Reports", description: "Inspection reports and audit exports." },
    { key: "security", label: "Security", description: "MFA, biometric login, managed devices, and alerts." },
    { key: "profile", label: "Profile", description: "Inspector profile and authorization details." },
    { key: "scan", label: "Scan", description: "Legacy QR scanning and credential capture." },
    { key: "verify", label: "Verify", description: "Legacy online credential and certificate checks." },
    { key: "offline", label: "Offline", description: "Legacy offline verification and sync mode." },
    { key: "records", label: "Records", description: "Legacy saved inspections and evidence." },
  ],
  actions: [
    { label: "View assigned inspections", detail: "Open the inspection work queue." },
    { label: "View pending cases", detail: "Inspect cases waiting for action." },
    { label: "View compliance alerts", detail: "Review compliance alerts and exceptions." },
    { label: "Start inspection", detail: "Launch a new inspection flow." },
    { label: "Sync offline records", detail: "Synchronize local records with the server." },
    { label: "Create inspection", detail: "Create a new inspection record." },
    { label: "Open inspection checklist", detail: "Open the checklist for the current inspection." },
    { label: "Verify person", detail: "Verify a person against evidence and trust data." },
    { label: "Verify business", detail: "Verify a business during inspection." },
    { label: "Verify vehicle", detail: "Verify a vehicle record and inspection status." },
    { label: "Verify document", detail: "Verify a document in the field." },
    { label: "Approve inspection", detail: "Approve the current inspection result." },
    { label: "Reject inspection", detail: "Reject the current inspection result." },
    { label: "Request correction", detail: "Request corrections from the inspected party." },
    { label: "Open case", detail: "Open a new case from the inspection flow." },
    { label: "Assign case", detail: "Assign the case to another reviewer." },
    { label: "Add case note", detail: "Add a note to the current case." },
    { label: "Escalate case", detail: "Escalate the case for review." },
    { label: "Resolve case", detail: "Mark the case as resolved." },
    { label: "Close case", detail: "Close the case after review." },
    { label: "Upload photo", detail: "Upload a photo as evidence." },
    { label: "Upload document", detail: "Upload a document as evidence." },
    { label: "Capture signature", detail: "Capture a signature as evidence." },
    { label: "Scan document", detail: "Scan a document into the evidence chain." },
    { label: "Add evidence note", detail: "Add a note to the evidence chain." },
    { label: "View evidence chain", detail: "Inspect the current evidence chain." },
    { label: "Lock evidence", detail: "Lock the evidence package." },
    { label: "Create inspection report", detail: "Create a new inspection report." },
    { label: "Download report", detail: "Download the selected report." },
    { label: "Submit report", detail: "Submit the inspection report." },
    { label: "Export audit report", detail: "Export the audit report for review." },
    { label: "View submitted reports", detail: "Inspect submitted reports." },
    { label: "Enable MFA", detail: "Enable multi-factor authentication." },
    { label: "Enable biometric login", detail: "Enable biometric login for inspection work." },
    { label: "Manage device", detail: "Review or remove the managed device." },
    { label: "View login history", detail: "Inspect security login history." },
    { label: "Report compromised device", detail: "Report a compromised device immediately." },
    { label: "Edit inspector profile", detail: "Update the inspector profile." },
    { label: "View inspector authorization", detail: "Inspect the active authorization scope." },
    { label: "View organization", detail: "Show the inspection organization." },
    { label: "Set language", detail: "Choose the preferred language." },
    { label: "Notification settings", detail: "Adjust notification settings." },
    { label: "Logout", detail: "End the inspector session." },
    { label: "Scan QR", detail: "Scan a credential QR or replay anchor." },
    { label: "Verify Credential", detail: "Run a live credential verification request." },
    { label: "Offline Verify", detail: "Approve inspection while offline with cached trust." },
    { label: "Save Inspection", detail: "Store the inspection record locally." },
    { label: "Sync Records", detail: "Push inspection records to the server." },
    { label: "Validate Certificate", detail: "Check certificate seals and replay hashes." },
  ],
  primaryFlow: [
    "Scan credential",
    "Review attributes",
    "Verify certificate",
    "Offline fallback",
    "Save inspection",
    "Sync records",
  ],
  seed: {
    displayName: "Nova Inspector",
    walletLabel: "Inspection credential wallet",
    trustLevel: "High",
    identityScore: 89,
    credentialCount: 2,
    trustedDevices: 1,
    governmentIds: 1,
    certificateCount: 1,
    biometricVerified: true,
    passkeyEnabled: true,
    deviceTrustEnabled: true,
    recoveryEnabled: false,
    connectedApps: 2,
    loginHistory: 9,
  },
};
