FROM python:3.11

WORKDIR /app

ENV PYTHONPATH=/app:/app/afritech

COPY . /app/afritech

RUN pip install --no-cache-dir fastapi uvicorn redis

CMD ["uvicorn", "api.server.run_server:app", "--host", "0.0.0.0", "--port", "8000"]
