-- Tenant isolation policies. Apply after creating a dedicated app role.

ALTER TABLE rider_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_eligibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_bids ENABLE ROW LEVEL SECURITY;
ALTER TABLE fare_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE operator_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleets ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_compliance ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE corporate_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE corporate_travel_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE corporate_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE transit_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE transit_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE transit_journeys ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobility_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_replay_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE idempotency_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE read_model_checkpoints ENABLE ROW LEVEL SECURITY;

-- Example policy template for each table:
-- CREATE POLICY bookings_tenant_isolation ON bookings
-- USING (tenant_id = current_setting('app.tenant_id', true))
-- WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
