"""Governed decentralized data ownership surface."""

from afritech.data_governance.contracts import (
    AccessMode,
    DataAccessContract,
    DataGovernanceViolation,
    DomainDataContract,
)
from afritech.data_governance.guards import (
    guard_cross_domain_access,
    guard_data_write,
    guard_owner_domain,
)
from afritech.data_governance.enterprise import (
    ContractStatus,
    DataContract,
    DataDomainRegistryEntry,
    DataDomainStatus,
    DataEventDefinition,
    DataEventEnvelope,
    DataSharingLevel,
    DEFAULT_CREATED_AT,
    DEFAULT_MODEL_VERSION,
    EnterpriseDataGateway,
    EnterpriseDataGovernanceError,
    EnterpriseDataModel,
    ProductDataExtension,
    SchemaChangeClass,
    SharedEnterpriseEntity,
    default_enterprise_data_model,
    enterprise_data_manifest,
    validate_enterprise_data_model,
)
from afritech.data_governance.metadata_repository import (
    DEFAULT_METADATA_PATH,
    DataLineageRecord,
    DataProductPackage,
    EnterpriseMetadataRepository,
    EnterpriseMetadataRepositoryError,
    EntityMetadata,
    EntityRelationship,
    SchemaMigrationRecord,
    build_default_metadata_repository,
)
from afritech.data_governance.ownership import (
    DATA_OWNERSHIP_REGISTRY,
    owner_for_resource,
    resources_for_domain,
)
from afritech.data_governance.registry import (
    DATA_DECENTRALIZATION_STATUS,
    DATA_ENTERPRISE_MODEL_STATUS,
    INV_DATA_001,
    validate_data_governance_registry,
)
from afritech.data_governance.lifecycle import (
    DataClassification,
    DataLifecyclePolicy,
    DeletionDecision,
    RetentionClass,
    evaluate_deletion,
    retention_deadline,
    validate_residency,
)

__all__ = [
    "AccessMode",
    "ContractStatus",
    "DATA_DECENTRALIZATION_STATUS",
    "DATA_ENTERPRISE_MODEL_STATUS",
    "DATA_OWNERSHIP_REGISTRY",
    "DEFAULT_CREATED_AT",
    "DEFAULT_MODEL_VERSION",
    "DEFAULT_METADATA_PATH",
    "DataAccessContract",
    "DataContract",
    "DataGovernanceViolation",
    "DataDomainRegistryEntry",
    "DataDomainStatus",
    "DataEventDefinition",
    "DataEventEnvelope",
    "DataSharingLevel",
    "DataLineageRecord",
    "DataProductPackage",
    "DomainDataContract",
    "EnterpriseDataGateway",
    "EnterpriseDataGovernanceError",
    "EnterpriseDataModel",
    "EnterpriseMetadataRepository",
    "EnterpriseMetadataRepositoryError",
    "INV_DATA_001",
    "EntityMetadata",
    "EntityRelationship",
    "ProductDataExtension",
    "SchemaChangeClass",
    "SchemaMigrationRecord",
    "SharedEnterpriseEntity",
    "build_default_metadata_repository",
    "default_enterprise_data_model",
    "enterprise_data_manifest",
    "guard_cross_domain_access",
    "guard_data_write",
    "guard_owner_domain",
    "owner_for_resource",
    "resources_for_domain",
    "validate_data_governance_registry",
    "validate_enterprise_data_model",
    "DataClassification",
    "DataLifecyclePolicy",
    "DeletionDecision",
    "RetentionClass",
    "evaluate_deletion",
    "retention_deadline",
    "validate_residency",
]
