"""Known NovaRide runtime events."""

REQUIRED_EVENTS: tuple[str, ...] = (
    "BookingCreated",
    "FareQuoted",
    "BookingConfirmed",
    "DriverSearchStarted",
    "DriverOfferCreated",
    "DriverOfferExpired",
    "DriverOfferAccepted",
    "DriverOfferDeclined",
    "DriverBidSubmitted",
    "DriverAssigned",
    "DriverReassigned",
    "DriverArrived",
    "PickupVerified",
    "TripStarted",
    "TripLocationUpdated",
    "TripCompleted",
    "TripCancelled",
    "PaymentRequested",
    "PaymentConfirmed",
    "PaymentFailed",
    "EmergencyActivated",
    "EmergencyAcknowledged",
    "IncidentCreated",
    "OperatorInterventionRecorded",
    "FleetVehicleAssigned",
    "DeliveryCreated",
    "DeliveryPickedUp",
    "DeliveryCompleted",
    "CorporateBookingCreated",
    "TransitJourneyPlanned",
    "TripEvidenceFinalized",
)
