export const ROUTES = {
  AUTH: "Auth",
  SPLASH: "Splash",
  LOGIN: "Login",
  REGISTER: "Register",
  ROLE_SELECTION: "RoleSelection",
  RIDER: "Rider",
  RIDER_HOME: "RiderHome",
  REQUEST_RIDE: "RequestRide",
  ACTIVE_RIDE: "ActiveRide",
  RIDE_HISTORY: "RideHistory",
  DRIVER: "Driver",
  DRIVER_HOME: "DriverHome",
  ASSIGNED_RIDE: "AssignedRide",
  ACTIVE_TRIP: "ActiveTrip",
  EARNINGS: "Earnings",
  REPLAY_RECEIPT: "ReplayReceipt",
  OPERATOR: "Operator",
  DASHBOARD: "Dashboard",
  OPERATOR_DASHBOARD: "Dashboard",
  REPLAY_MONITOR: "ReplayMonitor",
  EVIDENCE_VIEWER: "EvidenceViewer",
};
