"""Shared NovaTech backend runtime and executable product plane."""

from .activation import ALLOWED_ACTIVATION_TRANSITIONS, ProductActivationService, validate_activation_transition
from .compatibility import CompatibilityClass, CompatibilityFinding, CompatibilityValidator
from .config import (
    PlatformRuntimeSettings,
    ProductConfigurationField,
    ProductConfigurationSchema,
    RuntimeLayer,
    create_platform_runtime_settings_from_env,
)
from .contracts import CommandHandler, NovaTechProductBackend, ProductBackendFactory, QueryHandler, WorkerHandler
from .deployment_verifier import DeploymentVerifier, default_verification_checks
from .errors import (
    ProductActivationBlocked,
    ProductContractViolation,
    ProductExecutionDenied,
    ProductHandlerConflict,
    ProductLoadRejected,
    ProductProvisioningFailed,
    ProductRouteConflict,
    ProductSecretAccessDenied,
    ProductVerificationFailed,
    ProtectedConfigurationViolation,
    RuntimeErrorBase,
)
from .executable_runtime import ExecutableProductRuntime
from .infrastructure import InfrastructureKind, InfrastructureOwnership, InfrastructurePlanStep
from .models import (
    ActivationAssessment,
    ActivationResult,
    ActivationState,
    DeploymentStatus,
    DeploymentVerificationPlan,
    EventConsumerDefinition,
    ExecutionContext,
    ExecutionResult,
    InfrastructureRequirement,
    LoadedProduct,
    ProductHealthCheck,
    ProductMigration,
    ProductRuntimeState,
    ProductStartupContext,
    ProvisioningPlan,
    ProvisioningResult,
    QueryResult,
    RoutePlan,
    RouteRegistration,
    RollbackResult,
    RuntimeApproval,
    RuntimeEvidenceRecord,
    VerificationCheck,
    VerificationCheckResult,
    WorkerDefinition,
    WorkerExecutionContext,
    WorkerHealthRecord,
    WorkerOperationResult,
    WorkerState,
)
from .product_loader import APPROVED_PREFIXES, ProductModuleLoader
from .protected_configuration import PROTECTED_SETTINGS, ProtectedConfigurationView, validate_protected_configuration
from .provisioning import (
    InfrastructureProvisioner,
    InfrastructureProvider,
    KubernetesProvisioningProvider,
    LocalDevelopmentProvisioningProvider,
    NatsProvisioningProvider,
    ObjectStorageProvisioningProvider,
    PostgresProvisioningProvider,
    RedisProvisioningProvider,
    SearchProvisioningProvider,
)
from .query_executor import ProductQueryExecutor
from .command_executor import IdempotencyStore, ProductCommandExecutor
from .registry import (
    BackendProductRegistration,
    CommandRegistry,
    ProductConfigurationRevision,
    ProductHealthStatus,
    ProductRegistrationStatus,
    ProductRuntimeRegistry,
    QueryRegistry,
    RequestContext,
    build_default_product_runtime_registry,
)
from .route_registry import RouteRegistry
from .runtime_evidence import RuntimeEvidenceService
from .secret_resolver import InMemorySecretResolver, SecretAccessContext, SecretResolver
from .worker_registry import WorkerRegistry
from .worker_supervisor import WorkerSupervisor

__all__ = [
    "APPROVED_PREFIXES",
    "ActivationAssessment",
    "ActivationResult",
    "ActivationState",
    "ALLOWED_ACTIVATION_TRANSITIONS",
    "BackendProductRegistration",
    "CommandHandler",
    "CommandRegistry",
    "CompatibilityClass",
    "CompatibilityFinding",
    "CompatibilityValidator",
    "DeploymentStatus",
    "DeploymentVerificationPlan",
    "DeploymentVerifier",
    "EventConsumerDefinition",
    "ExecutionContext",
    "ExecutionResult",
    "ExecutableProductRuntime",
    "InfrastructureKind",
    "InfrastructureOwnership",
    "InfrastructurePlanStep",
    "InfrastructureProvisioner",
    "InfrastructureProvider",
    "InfrastructureRequirement",
    "InMemorySecretResolver",
    "IdempotencyStore",
    "KubernetesProvisioningProvider",
    "LocalDevelopmentProvisioningProvider",
    "LoadedProduct",
    "NatsProvisioningProvider",
    "NovaTechProductBackend",
    "ObjectStorageProvisioningProvider",
    "PlatformRuntimeSettings",
    "PostgresProvisioningProvider",
    "ProductActivationBlocked",
    "ProductActivationService",
    "ProductBackendFactory",
    "ProductCommandExecutor",
    "ProductConfigurationField",
    "ProductConfigurationRevision",
    "ProductConfigurationSchema",
    "ProductContractViolation",
    "ProductExecutionDenied",
    "ProductHandlerConflict",
    "ProductHealthCheck",
    "ProductHealthStatus",
    "ProductLoadRejected",
    "ProductMigration",
    "ProductModuleLoader",
    "ProductProvisioningFailed",
    "ProductQueryExecutor",
    "ProductRegistrationStatus",
    "ProductRouteConflict",
    "ProductRuntimeRegistry",
    "ProductRuntimeState",
    "ProductSecretAccessDenied",
    "ProductStartupContext",
    "ProductVerificationFailed",
    "PROTECTED_SETTINGS",
    "ProtectedConfigurationView",
    "ProtectedConfigurationViolation",
    "ProvisioningPlan",
    "ProvisioningResult",
    "QueryHandler",
    "QueryRegistry",
    "QueryResult",
    "RedisProvisioningProvider",
    "RequestContext",
    "RollbackResult",
    "RoutePlan",
    "RouteRegistry",
    "RouteRegistration",
    "RuntimeApproval",
    "RuntimeErrorBase",
    "RuntimeEvidenceRecord",
    "RuntimeEvidenceService",
    "RuntimeLayer",
    "SearchProvisioningProvider",
    "SecretAccessContext",
    "SecretResolver",
    "VerificationCheck",
    "VerificationCheckResult",
    "WorkerDefinition",
    "WorkerExecutionContext",
    "WorkerHealthRecord",
    "WorkerOperationResult",
    "WorkerRegistry",
    "WorkerState",
    "WorkerHandler",
    "WorkerSupervisor",
    "build_default_product_runtime_registry",
    "create_platform_runtime_settings_from_env",
    "default_verification_checks",
    "validate_activation_transition",
    "validate_protected_configuration",
]
