-- NovaCodePro NCP-008 Operations Studio migration contract.
-- The live runtime currently stores governed operations records through the generic repository
-- layer, but this file documents the authoritative relational schema expected by the phase.

CREATE TABLE IF NOT EXISTS ncp008_operations_workspaces (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  environment_ids TEXT NOT NULL DEFAULT '[]',
  service_ids TEXT NOT NULL DEFAULT '[]',
  region_ids TEXT NOT NULL DEFAULT '[]',
  default_time_window TEXT NOT NULL DEFAULT '24h',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  causation_id TEXT,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_runtime_environments (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  region TEXT NOT NULL,
  zones TEXT NOT NULL DEFAULT '[]',
  tenant_scope TEXT NOT NULL DEFAULT '',
  network_scope TEXT NOT NULL DEFAULT '',
  service_scope TEXT NOT NULL DEFAULT '',
  data_classification TEXT NOT NULL DEFAULT 'INTERNAL',
  change_policy TEXT NOT NULL DEFAULT '',
  approval_policy TEXT NOT NULL DEFAULT '',
  deployment_policy TEXT NOT NULL DEFAULT '',
  incident_policy TEXT NOT NULL DEFAULT '',
  backup_policy TEXT NOT NULL DEFAULT '',
  restore_policy TEXT NOT NULL DEFAULT '',
  access_policy TEXT NOT NULL DEFAULT '',
  maintenance_policy TEXT NOT NULL DEFAULT '',
  observability_profile TEXT NOT NULL DEFAULT '',
  retention_policy TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'PLANNED',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  causation_id TEXT,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_runtime_services (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  product_code TEXT NOT NULL DEFAULT '',
  service_code TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  service_type TEXT NOT NULL DEFAULT 'service',
  runtime_kind TEXT NOT NULL DEFAULT '',
  version TEXT NOT NULL DEFAULT '1',
  desired_version TEXT NOT NULL DEFAULT '1',
  health_status TEXT NOT NULL DEFAULT 'UNKNOWN',
  readiness_status TEXT NOT NULL DEFAULT 'UNKNOWN',
  deployment_status TEXT NOT NULL DEFAULT 'UNKNOWN',
  instance_count INTEGER NOT NULL DEFAULT 0,
  desired_instance_count INTEGER NOT NULL DEFAULT 0,
  region TEXT NOT NULL DEFAULT '',
  dependencies TEXT NOT NULL DEFAULT '[]',
  endpoints TEXT NOT NULL DEFAULT '[]',
  owner_team TEXT NOT NULL DEFAULT '',
  criticality TEXT NOT NULL DEFAULT 'STANDARD',
  data_classification TEXT NOT NULL DEFAULT 'INTERNAL',
  mutation_capabilities TEXT NOT NULL DEFAULT '[]',
  last_observed_at TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version_number INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  causation_id TEXT,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_deployments (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  service_id TEXT NOT NULL,
  release_id TEXT NOT NULL DEFAULT '',
  version TEXT NOT NULL,
  previous_version TEXT NOT NULL DEFAULT '',
  deployment_strategy TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'DRAFT',
  initiated_by TEXT NOT NULL DEFAULT '',
  approved_by TEXT NOT NULL DEFAULT '',
  started_at TEXT NOT NULL DEFAULT '',
  completed_at TEXT NOT NULL DEFAULT '',
  verification_status TEXT NOT NULL DEFAULT 'UNKNOWN',
  rollback_status TEXT NOT NULL DEFAULT 'UNKNOWN',
  evidence_id TEXT NOT NULL DEFAULT '',
  correlation_id TEXT NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version_number INTEGER NOT NULL DEFAULT 1,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_alerts (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  service_id TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'observability',
  fingerprint TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  severity TEXT NOT NULL DEFAULT 'LOW',
  status TEXT NOT NULL DEFAULT 'FIRING',
  labels TEXT NOT NULL DEFAULT '{}',
  annotations TEXT NOT NULL DEFAULT '{}',
  first_seen_at TEXT NOT NULL DEFAULT '',
  last_seen_at TEXT NOT NULL DEFAULT '',
  occurrence_count INTEGER NOT NULL DEFAULT 0,
  acknowledged_by TEXT NOT NULL DEFAULT '',
  acknowledged_at TEXT NOT NULL DEFAULT '',
  resolved_at TEXT NOT NULL DEFAULT '',
  incident_id TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_incidents (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  severity TEXT NOT NULL DEFAULT 'SEV3',
  type TEXT NOT NULL DEFAULT 'OTHER',
  status TEXT NOT NULL DEFAULT 'DETECTED',
  impact TEXT NOT NULL DEFAULT '',
  affected_service_ids TEXT NOT NULL DEFAULT '[]',
  affected_product_codes TEXT NOT NULL DEFAULT '[]',
  commander_id TEXT NOT NULL DEFAULT '',
  technical_lead_id TEXT NOT NULL DEFAULT '',
  communications_lead_id TEXT NOT NULL DEFAULT '',
  scribe_id TEXT NOT NULL DEFAULT '',
  declared_by TEXT NOT NULL DEFAULT '',
  declared_at TEXT NOT NULL DEFAULT '',
  detected_at TEXT NOT NULL DEFAULT '',
  mitigated_at TEXT NOT NULL DEFAULT '',
  resolved_at TEXT NOT NULL DEFAULT '',
  closed_at TEXT NOT NULL DEFAULT '',
  customer_impact TEXT NOT NULL DEFAULT '',
  regulatory_impact TEXT NOT NULL DEFAULT '',
  security_impact TEXT NOT NULL DEFAULT '',
  financial_impact TEXT NOT NULL DEFAULT '',
  root_cause TEXT NOT NULL DEFAULT '',
  resolution_summary TEXT NOT NULL DEFAULT '',
  evidence_id TEXT NOT NULL DEFAULT '',
  correlation_id TEXT NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_incident_timeline (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  incident_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  actor_id TEXT NOT NULL DEFAULT '',
  source_type TEXT NOT NULL DEFAULT '',
  source_id TEXT NOT NULL DEFAULT '',
  evidence_id TEXT NOT NULL DEFAULT '',
  immutable_hash TEXT NOT NULL DEFAULT '',
  timestamp TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_action_requests (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  service_id TEXT NOT NULL DEFAULT '',
  incident_id TEXT NOT NULL DEFAULT '',
  action_type TEXT NOT NULL,
  requested_parameters TEXT NOT NULL DEFAULT '{}',
  normalized_parameters TEXT NOT NULL DEFAULT '{}',
  reason TEXT NOT NULL DEFAULT '',
  risk_level TEXT NOT NULL DEFAULT 'low',
  status TEXT NOT NULL DEFAULT 'draft',
  requested_by TEXT NOT NULL,
  requested_at TEXT NOT NULL,
  approval_required INTEGER NOT NULL DEFAULT 0,
  approval_policy_id TEXT NOT NULL DEFAULT '',
  approved_by TEXT NOT NULL DEFAULT '',
  approved_at TEXT NOT NULL DEFAULT '',
  rejected_by TEXT NOT NULL DEFAULT '',
  rejected_at TEXT NOT NULL DEFAULT '',
  rejection_reason TEXT NOT NULL DEFAULT '',
  execution_id TEXT NOT NULL DEFAULT '',
  evidence_id TEXT NOT NULL DEFAULT '',
  idempotency_key TEXT NOT NULL DEFAULT '',
  correlation_id TEXT NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_action_executions (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  action_id TEXT NOT NULL,
  adapter TEXT NOT NULL DEFAULT 'memory',
  execution_mode TEXT NOT NULL DEFAULT 'memory',
  status TEXT NOT NULL DEFAULT 'RUNNING',
  started_at TEXT NOT NULL,
  completed_at TEXT NOT NULL DEFAULT '',
  stdout_summary TEXT NOT NULL DEFAULT '',
  stderr_summary TEXT NOT NULL DEFAULT '',
  result TEXT NOT NULL DEFAULT '{}',
  previous_state TEXT NOT NULL DEFAULT '{}',
  resulting_state TEXT NOT NULL DEFAULT '{}',
  verification_result TEXT NOT NULL DEFAULT '{}',
  rollback_available INTEGER NOT NULL DEFAULT 0,
  rollback_action_id TEXT NOT NULL DEFAULT '',
  failure_code TEXT NOT NULL DEFAULT '',
  failure_message TEXT NOT NULL DEFAULT '',
  evidence_id TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  environment_id TEXT NOT NULL DEFAULT '',
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_approvals (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  action_id TEXT NOT NULL,
  required_role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_at TEXT NOT NULL,
  decided_at TEXT NOT NULL DEFAULT '',
  decided_by TEXT NOT NULL DEFAULT '',
  decision_reason TEXT NOT NULL DEFAULT '',
  separation_of_duties_satisfied INTEGER NOT NULL DEFAULT 0,
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  environment_id TEXT NOT NULL DEFAULT '',
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_slos (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  service_id TEXT NOT NULL,
  name TEXT NOT NULL,
  objective_type TEXT NOT NULL DEFAULT 'AVAILABILITY',
  target NUMERIC NOT NULL DEFAULT 0.999,
  window TEXT NOT NULL DEFAULT '30d',
  query_definition TEXT NOT NULL DEFAULT '',
  current_value NUMERIC NOT NULL DEFAULT 0,
  compliance_status TEXT NOT NULL DEFAULT 'DRAFT',
  error_budget_total NUMERIC NOT NULL DEFAULT 0,
  error_budget_remaining NUMERIC NOT NULL DEFAULT 0,
  burn_rate NUMERIC NOT NULL DEFAULT 0,
  evaluated_at TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_recovery_plans (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  environment_id TEXT NOT NULL,
  service_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  trigger_conditions TEXT NOT NULL DEFAULT '[]',
  steps TEXT NOT NULL DEFAULT '[]',
  rollback_steps TEXT NOT NULL DEFAULT '[]',
  required_approvals TEXT NOT NULL DEFAULT '[]',
  validation_steps TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'DRAFT',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_post_incident_reviews (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  incident_id TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  timeline_analysis TEXT NOT NULL DEFAULT '',
  root_cause TEXT NOT NULL DEFAULT '',
  contributing_factors TEXT NOT NULL DEFAULT '[]',
  what_went_well TEXT NOT NULL DEFAULT '',
  what_went_poorly TEXT NOT NULL DEFAULT '',
  detection_gaps TEXT NOT NULL DEFAULT '',
  response_gaps TEXT NOT NULL DEFAULT '',
  prevention_actions TEXT NOT NULL DEFAULT '[]',
  owners TEXT NOT NULL DEFAULT '[]',
  due_dates TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'DRAFT',
  approved_by TEXT NOT NULL DEFAULT '',
  published_at TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  correlation_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS ncp008_evidence_links (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  workspace_id TEXT,
  project_id TEXT,
  incident_id TEXT NOT NULL DEFAULT '',
  action_id TEXT NOT NULL DEFAULT '',
  deployment_id TEXT NOT NULL DEFAULT '',
  evidence_type TEXT NOT NULL DEFAULT '',
  evidence_uri TEXT NOT NULL DEFAULT '',
  digest TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'ATTACHED',
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_ncp008_environments_tenant_status ON ncp008_runtime_environments(tenant_id, organization_id, status);
CREATE INDEX IF NOT EXISTS idx_ncp008_services_environment ON ncp008_runtime_services(tenant_id, organization_id, environment_id, criticality);
CREATE INDEX IF NOT EXISTS idx_ncp008_alerts_tenant_status ON ncp008_alerts(tenant_id, organization_id, status, severity);
CREATE INDEX IF NOT EXISTS idx_ncp008_incidents_tenant_status ON ncp008_incidents(tenant_id, organization_id, status, severity);
CREATE INDEX IF NOT EXISTS idx_ncp008_actions_tenant_status ON ncp008_action_requests(tenant_id, organization_id, status, risk_level);
CREATE INDEX IF NOT EXISTS idx_ncp008_slos_tenant_status ON ncp008_slos(tenant_id, organization_id, compliance_status);
CREATE INDEX IF NOT EXISTS idx_ncp008_recovery_plans_tenant_status ON ncp008_recovery_plans(tenant_id, organization_id, status);
CREATE INDEX IF NOT EXISTS idx_ncp008_reviews_tenant_status ON ncp008_post_incident_reviews(tenant_id, organization_id, status);
CREATE INDEX IF NOT EXISTS idx_ncp008_evidence_links_tenant ON ncp008_evidence_links(tenant_id, organization_id, incident_id, action_id, deployment_id);

-- Representative operational collections used by the service layer:
-- health_check_definition, health_check_execution, runtime_inventory_snapshot,
-- runtime_discovery_run, operational_metric_sample, error_budget_policy,
-- error_budget_measurement, error_budget_consumption, operational_dashboard,
-- on_call_schedule, on_call_override, escalation_policy, escalation_step,
-- change_window, change_freeze, rollback, backup_policy, backup_record,
-- restore_plan, failover_plan, disaster_recovery_plan, disaster_recovery_exercise,
-- capacity_measurement, capacity_forecast, scaling_policy, scaling_action,
-- maintenance_window, maintenance_task, runbook, runbook_execution,
-- operational_command, postmortem, corrective_action, operational_baseline.
