SCENARIOS = (
    "Offline",
    "2G",
    "3G",
    "4G",
    "5G",
    "High latency",
    "Packet loss",
    "GPS loss",
    "GPS drift",
    "API timeout",
    "Authentication expiry",
    "Payment-provider failure reference",
    "Accessibility mode",
    "Localization expansion",
    "RTL",
    "Low-memory device",
    "Background sync recovery",
)
