from django.urls import path
from django.urls import include

from afritech.api.afriride_driver_views import (
    active_rides,
    api_root,
    driver_availability,
    driver_earnings,
    driver_queue,
    driver_replay_history,
    driver_status,
    evidence_pipeline,
    guard_violations,
    pilot_evidence,
    pilot_metrics,
    pilot_readiness,
    replay_health,
    ride_accept,
    ride_arrive,
    ride_complete,
    ride_reject,
    ride_start,
    system_drivers,
    system_health,
    system_pilot_metrics,
    trust_metrics,
)
from afritech.api.verification_views import (
    verify_proof_view,
    verify_log_proof_view,
)
from afritech.api.explain_execution_views import explain_execution_view
from afritech.api.trust_kernel_views import verify_event_view
from afritech.api.trust_graph_views import (
    governance_pending_requests_view,
    governance_rollback_view,
    governance_rule_save_view,
    governance_rule_submit_view,
    governance_rules_view,
    governance_vote_view,
    governance_votes_view,
    proof_certificate_view,
    risk_scores_view,
    rule_dependency_add_view,
    rule_graph_view,
    rule_impact_view,
    trust_conversation_view,
    trust_converse_view,
    trust_graph_view,
    trust_history_view,
    trust_node_view,
    trust_process_view,
    trust_simulate_view,
)
from afritech.api.afriprogramming_views import (
    novaprogramming_assurance,
    novaprogramming_assurance_alerts,
    novaprogramming_assurance_history,
    novaprogramming_assurance_run,
    novaprogramming_assurance_status,
    novaprogramming_catalog,
    novaprogramming_certification,
    novaprogramming_certificate_chains,
    novaprogramming_certificate_issue,
    novaprogramming_certificate_verify,
    novaprogramming_certification_issue,
    novaprogramming_certification_verify,
    novaprogramming_billing_summary,
    novaprogramming_cloud_deploy,
    novaprogramming_cloud_health,
    novaprogramming_cloud_request_deploy,
    novaprogramming_cloud_scale,
    novaprogramming_cloud_services,
    novaprogramming_crypto_backend_register,
    novaprogramming_crypto_backends,
    novaprogramming_distributed_trust_network,
    novaprogramming_identity_bind,
    novaprogramming_identity_bindings,
    novaprogramming_event_consume,
    novaprogramming_event_publish,
    novaprogramming_event_topic_create,
    novaprogramming_event_topics,
    novaprogramming_federation_claim,
    novaprogramming_federation_register,
    novaprogramming_federation_verify,
    novaprogramming_key_registry,
    novaprogramming_key_rotate,
    novaprogramming_governance_audit_log,
    novaprogramming_governance_approve,
    novaprogramming_governance_check,
    novaprogramming_governance_policy,
    novaprogramming_insights,
    novaprogramming_metrics,
    novaprogramming_policy_create,
    novaprogramming_policy_decisions,
    novaprogramming_policy_evaluate,
    novaprogramming_policy_registry,
    novaprogramming_reports_assurance,
    novaprogramming_reports_assurance_generate,
    novaprogramming_retention,
    novaprogramming_retention_check,
    novaprogramming_retention_set,
    novaprogramming_risk_prediction,
    novaprogramming_risk_predictions,
    novaprogramming_signed_audit_chain,
    novaprogramming_signed_audit_verify,
    novaprogramming_stream_backend_register,
    novaprogramming_stream_backends,
    novaprogramming_staff_dashboard,
    novaprogramming_staff_roles,
    novaprogramming_status,
    novaprogramming_studio_analyze_repo,
    novaprogramming_studio_context,
    novaprogramming_studio_explain_code,
    novaprogramming_studio_generate_code,
    novaprogramming_trust,
    novaprogramming_trust_anomalies,
    novaprogramming_trust_replay,
    novaprogramming_trust_risk,
    novaprogramming_trust_exchange_events,
    novaprogramming_trust_exchange_verify,
    novaprogramming_trust_fabric_graph,
    novaprogramming_trust_fabric_link,
    novaprogramming_trust_fabric_region_register,
    novaprogramming_trust_fabric_regions,
    novaprogramming_trust_fabric_signed_request,
    novaprogramming_trust_fabric_signed_request_verify,
    novaprogramming_trust_negotiation,
    novaprogramming_trust_negotiations,
    novaprogramming_trust_trends,
    novaprogramming_trust_stream,
    novaprogramming_trust_verify_external,
    novaprogramming_v9_assurance_scheduler_history,
    novaprogramming_v9_assurance_scheduler_run,
    novaprogramming_v9_certificate_transparency,
    novaprogramming_v9_certificate_transparency_append,
    novaprogramming_v9_certificate_transparency_log,
    novaprogramming_v9_key_revocation,
    novaprogramming_v9_key_revocations,
    novaprogramming_v9_schema,
    novaprogramming_v9_traces,
    novaprogramming_v9_trace_span,
    novaprogramming_v9_trace_spans,
    novaprogramming_v9_trust_consensus,
    novaprogramming_workflow_history,
    novaprogramming_workflow_signal,
    novaprogramming_workflow_start,
    novaprogramming_workflow_status,
    novaprogramming_zero_trust_decisions,
    novaprogramming_zero_trust_evaluate,
    novaprogramming_zero_trust_policies,
    novaprogramming_zero_trust_policy_create,
    novaprogramming_verify_generate_proof,
    novaprogramming_verify_lookup,
    novaprogramming_verify_replay,
)
from afritech.api.novascript_views import (
    novascript_architecture,
    novascript_catalog,
    novascript_context,
    novascript_debug,
    novascript_docs,
    novascript_explain,
    novascript_generate,
    novascript_repo_intelligence,
    novascript_status,
    novascript_tests,
)
from afritech.api.orchestration_views import (
    orchestration_abort_view,
    orchestration_detail_view,
    orchestration_list_view,
    orchestration_pause_view,
    orchestration_resume_view,
)

urlpatterns = [
    path("", api_root),
    path("driver/availability", driver_availability),
    path("driver/status", driver_status),
    path("driver/<str:driver_id>/queue", driver_queue),
    path("driver/<str:driver_id>/earnings", driver_earnings),
    path("driver/replay-history", driver_replay_history),
    path("rides/active", active_rides),
    path("system/health", system_health),
    path("system/drivers", system_drivers),
    path("system/replay/health", replay_health),
    path("system/evidence", evidence_pipeline),
    path("system/trust-metrics", trust_metrics),
    path("system/pilot-metrics", system_pilot_metrics),
    path("pilot/evidence", pilot_evidence),
    path("pilot/metrics", pilot_metrics),
    path("pilot/readiness", pilot_readiness),
    path("system/guards", guard_violations),
    path("trust/graph", trust_graph_view),
    path("trust/history", trust_history_view),
    path("trust/node/<str:node_id>", trust_node_view),
    path("trust/process", trust_process_view),
    path("trust/conversation", trust_conversation_view),
    path("trust/converse", trust_converse_view),
    path("trust/rules", governance_rules_view),
    path("trust/rules/save", governance_rule_save_view),
    path("trust/rules/<str:version_id>/submit", governance_rule_submit_view),
    path("trust/change-requests/pending", governance_pending_requests_view),
    path("trust/change-requests/<str:request_id>/vote", governance_vote_view),
    path("trust/change-requests/<str:request_id>/votes", governance_votes_view),
    path("trust/rules/<str:rule_name>/rollback", governance_rollback_view),
    path("trust/simulate", trust_simulate_view),
    path("trust/rule-graph", rule_graph_view),
    path("trust/rule-graph/dependency", rule_dependency_add_view),
    path("trust/impact/<str:rule_name>", rule_impact_view),
    path("trust/risk", risk_scores_view),
    path("trust/proof/<str:proposal_id>", proof_certificate_view),
    path("ride/<str:ride_id>/accept", ride_accept),
    path("ride/<str:ride_id>/reject", ride_reject),
    path("ride/arrive", ride_arrive),
    path("ride/<str:ride_id>/start", ride_start),
    path("ride/<str:ride_id>/complete", ride_complete),
    path("verify-proof/", verify_proof_view),
    path("verify/<uuid:event_id>", verify_event_view),
    path("verify-log-proof/", verify_log_proof_view),
    path("execution/<str:execution_id>/explain/", explain_execution_view),
    path("orchestrations", orchestration_list_view),
    path("orchestrations/<str:orchestration_id>", orchestration_detail_view),
    path("orchestrations/<str:orchestration_id>/pause", orchestration_pause_view),
    path("orchestrations/<str:orchestration_id>/resume", orchestration_resume_view),
    path("orchestrations/<str:orchestration_id>/abort", orchestration_abort_view),
    path("novapay/", include("afriride_system.django_app.apps.afripay.urls")),
    path("afripay/", include("afriride_system.django_app.apps.afripay.urls")),
    path("novaprogramming/status", novaprogramming_status),
    path("novaprogramming/catalog", novaprogramming_catalog),
    path("novaprogramming/staff/roles", novaprogramming_staff_roles),
    path("novaprogramming/staff/<str:role>/dashboard", novaprogramming_staff_dashboard),
    path("novaprogramming/studio/context/<str:project_id>", novaprogramming_studio_context),
    path("novaprogramming/studio/generate-code", novaprogramming_studio_generate_code),
    path("novaprogramming/studio/explain-code", novaprogramming_studio_explain_code),
    path("novaprogramming/studio/analyze-repo", novaprogramming_studio_analyze_repo),
    path("novaprogramming/cloud/services", novaprogramming_cloud_services),
    path("novaprogramming/cloud/health", novaprogramming_cloud_health),
    path("novaprogramming/cloud/request-deploy", novaprogramming_cloud_request_deploy),
    path("novaprogramming/cloud/deploy", novaprogramming_cloud_deploy),
    path("novaprogramming/cloud/scale", novaprogramming_cloud_scale),
    path("novaprogramming/governance/policy", novaprogramming_governance_policy),
    path("novaprogramming/governance/audit-log", novaprogramming_governance_audit_log),
    path("novaprogramming/governance/check", novaprogramming_governance_check),
    path("novaprogramming/governance/approve", novaprogramming_governance_approve),
    path("novaprogramming/verify/generate-proof", novaprogramming_verify_generate_proof),
    path("novaprogramming/verify/<str:execution_id>", novaprogramming_verify_lookup),
    path("novaprogramming/verify/<str:execution_id>/replay", novaprogramming_verify_replay),
    path("novaprogramming/metrics", novaprogramming_metrics),
    path("novaprogramming/trust", novaprogramming_trust),
    path("novaprogramming/trust/stream", novaprogramming_trust_stream),
    path("novaprogramming/trust/anomalies", novaprogramming_trust_anomalies),
    path("novaprogramming/trust/verify-external", novaprogramming_trust_verify_external),
    path("novaprogramming/trust/trends", novaprogramming_trust_trends),
    path("novaprogramming/trust/risk", novaprogramming_trust_risk),
    path("novaprogramming/trust/exchange/events", novaprogramming_trust_exchange_events),
    path("novaprogramming/trust/exchange/verify", novaprogramming_trust_exchange_verify),
    path("novaprogramming/trust/replay/<str:deployment_id>", novaprogramming_trust_replay),
    path("novaprogramming/crypto/backends", novaprogramming_crypto_backends),
    path("novaprogramming/crypto/backends/register", novaprogramming_crypto_backend_register),
    path("novaprogramming/crypto/chains", novaprogramming_certificate_chains),
    path("novaprogramming/crypto/chains/issue", novaprogramming_certificate_issue),
    path("novaprogramming/crypto/chains/verify", novaprogramming_certificate_verify),
    path("novaprogramming/stream/backends", novaprogramming_stream_backends),
    path("novaprogramming/stream/backends/register", novaprogramming_stream_backend_register),
    path("novaprogramming/trust/fabric/regions", novaprogramming_trust_fabric_regions),
    path("novaprogramming/trust/fabric/regions/register", novaprogramming_trust_fabric_region_register),
    path("novaprogramming/trust/fabric/regions/link", novaprogramming_trust_fabric_link),
    path("novaprogramming/trust/fabric/graph", novaprogramming_trust_fabric_graph),
    path("novaprogramming/trust/fabric/http-request", novaprogramming_trust_fabric_signed_request),
    path("novaprogramming/trust/fabric/http-request/verify", novaprogramming_trust_fabric_signed_request_verify),
    path("novaprogramming/identity/bind", novaprogramming_identity_bind),
    path("novaprogramming/identity/bindings", novaprogramming_identity_bindings),
    path("novaprogramming/risk/predict", novaprogramming_risk_prediction),
    path("novaprogramming/risk/predictions", novaprogramming_risk_predictions),
    path("novaprogramming/negotiation/start", novaprogramming_trust_negotiation),
    path("novaprogramming/negotiation/sessions", novaprogramming_trust_negotiations),
    path("novaprogramming/assurance/status", novaprogramming_assurance_status),
    path("novaprogramming/assurance/run", novaprogramming_assurance_run),
    path("novaprogramming/assurance/history", novaprogramming_assurance_history),
    path("novaprogramming/assurance/alerts", novaprogramming_assurance_alerts),
    path("novaprogramming/assurance/<str:deployment_id>", novaprogramming_assurance),
    path("novaprogramming/certification", novaprogramming_certification),
    path("novaprogramming/certification/issue", novaprogramming_certification_issue),
    path("novaprogramming/certification/verify", novaprogramming_certification_verify),
    path("novaprogramming/keys", novaprogramming_key_registry),
    path("novaprogramming/keys/rotate", novaprogramming_key_rotate),
    path("novaprogramming/audit/signed", novaprogramming_signed_audit_chain),
    path("novaprogramming/audit/signed/verify", novaprogramming_signed_audit_verify),
    path("novaprogramming/network/distributed", novaprogramming_distributed_trust_network),
    path("novaprogramming/federation/register", novaprogramming_federation_register),
    path("novaprogramming/federation/claim", novaprogramming_federation_claim),
    path("novaprogramming/federation/verify", novaprogramming_federation_verify),
    path("novaprogramming/stream/topics", novaprogramming_event_topics),
    path("novaprogramming/stream/topics/create", novaprogramming_event_topic_create),
    path("novaprogramming/stream/publish", novaprogramming_event_publish),
    path("novaprogramming/stream/consume", novaprogramming_event_consume),
    path("novaprogramming/workflows/start", novaprogramming_workflow_start),
    path("novaprogramming/workflows/signal", novaprogramming_workflow_signal),
    path("novaprogramming/workflows/<str:workflow_id>", novaprogramming_workflow_status),
    path("novaprogramming/workflows/<str:workflow_id>/history", novaprogramming_workflow_history),
    path("novaprogramming/zero-trust/policies", novaprogramming_zero_trust_policies),
    path("novaprogramming/zero-trust/policies/create", novaprogramming_zero_trust_policy_create),
    path("novaprogramming/zero-trust/evaluate", novaprogramming_zero_trust_evaluate),
    path("novaprogramming/zero-trust/decisions", novaprogramming_zero_trust_decisions),
    path("novaprogramming/policies", novaprogramming_policy_registry),
    path("novaprogramming/policies/create", novaprogramming_policy_create),
    path("novaprogramming/policies/evaluate", novaprogramming_policy_evaluate),
    path("novaprogramming/policies/decisions", novaprogramming_policy_decisions),
    path("novaprogramming/retention", novaprogramming_retention),
    path("novaprogramming/retention/check", novaprogramming_retention_check),
    path("novaprogramming/retention/set", novaprogramming_retention_set),
    path("novaprogramming/reports/assurance", novaprogramming_reports_assurance),
    path("novaprogramming/reports/assurance/generate", novaprogramming_reports_assurance_generate),
    path("novaprogramming/billing/summary", novaprogramming_billing_summary),
    path("novaprogramming/insights", novaprogramming_insights),
    path("novaprogramming/v9/schema", novaprogramming_v9_schema),
    path("novaprogramming/v9/trust/consensus", novaprogramming_v9_trust_consensus),
    path("novaprogramming/v9/certificate-transparency", novaprogramming_v9_certificate_transparency),
    path("novaprogramming/v9/keys/revocations", novaprogramming_v9_key_revocations),
    path("novaprogramming/v9/keys/revoke", novaprogramming_v9_key_revocation),
    path("novaprogramming/v9/traces", novaprogramming_v9_traces),
    path("novaprogramming/v9/assurance/scheduler/run", novaprogramming_v9_assurance_scheduler_run),
    path("novaprogramming/v9/assurance/scheduler/history", novaprogramming_v9_assurance_scheduler_history),
    path("novascript/status", novascript_status),
    path("novascript/catalog", novascript_catalog),
    path("novascript/context/<str:project_id>", novascript_context),
    path("novascript/generate", novascript_generate),
    path("novascript/explain", novascript_explain),
    path("novascript/debug", novascript_debug),
    path("novascript/architecture", novascript_architecture),
    path("novascript/tests", novascript_tests),
    path("novascript/docs", novascript_docs),
    path("novascript/repo/<str:project_id>/intelligence", novascript_repo_intelligence),
]
