import { createNovaTechIntegrationClient } from "../../platform/integrationClient.js";

const DESIGN_ROOT = "/v1/novacodepro/design";

export function createNovaCodeProNcp006bApi({ baseUrl = "", session = {}, timeoutMs } = {}) {
  const client = createNovaTechIntegrationClient({ baseUrl, session, timeoutMs });
  const { request, safeGet, mutation, createCorrelationId, createIdempotencyKey } = client;

  const collection = (path, key) => ({
    list: (signal) => safeGet(`${DESIGN_ROOT}${path}`, { signal }).then((body) => body?.[key] || []),
    create: (payload) => mutation(`${DESIGN_ROOT}${path}`, payload),
    get: (resourceId, signal) => request(`${DESIGN_ROOT}${path}/${encodeURIComponent(resourceId)}`, { signal }),
    update: (resourceId, payload) => mutation(`${DESIGN_ROOT}${path}/${encodeURIComponent(resourceId)}`, payload, { method: "PATCH" }),
    archive: (resourceId) => mutation(`${DESIGN_ROOT}${path}/${encodeURIComponent(resourceId)}/archive`, {}),
    restore: (resourceId) => mutation(`${DESIGN_ROOT}${path}/${encodeURIComponent(resourceId)}/restore`, {}),
    versions: (resourceId, signal) => safeGet(`${DESIGN_ROOT}${path}/${encodeURIComponent(resourceId)}/versions`, { signal }).then((body) => body?.versions || []),
  });

  const brief = collection("/briefs", "briefs");
  const research = collection("/research", "research_studies");
  const personas = collection("/personas", "personas");
  const journeys = collection("/journeys", "journeys");
  const blueprints = collection("/service-blueprints", "service_blueprints");
  const informationArchitecture = collection("/information-architecture", "information_architectures");
  const flows = collection("/user-flows", "user_flows");
  const wireframes = collection("/wireframes", "wireframes");
  const screens = collection("/screens", "screen_designs");
  const systems = collection("/systems", "design_systems");
  const tokens = collection("/tokens", "design_tokens");
  const themes = collection("/themes", "themes");
  const brands = collection("/brands", "brands");
  const components = collection("/components", "components");
  const interactionPatterns = collection("/interaction-patterns", "interaction_patterns");
  const responsiveSpecifications = collection("/responsive-specifications", "responsive_specifications");
  const content = collection("/content", "content_specifications");
  const localization = collection("/localization", "localization_resources");
  const accessibility = collection("/accessibility", "accessibility_requirements");
  const prototypes = collection("/prototypes", "prototypes");

  return {
    createCorrelationId,
    createIdempotencyKey,
    listWorkspaces: (signal) => safeGet(`${DESIGN_ROOT}/workspaces`, { signal }).then((body) => body?.experience_workspaces || []),
    createWorkspace: (payload) => mutation(`${DESIGN_ROOT}/workspaces`, payload),
    getWorkspace: (workspaceId, signal) => request(`${DESIGN_ROOT}/workspaces/${encodeURIComponent(workspaceId)}`, { signal }),
    updateWorkspace: (workspaceId, payload) => mutation(`${DESIGN_ROOT}/workspaces/${encodeURIComponent(workspaceId)}`, payload, { method: "PATCH" }),
    archiveWorkspace: (workspaceId) => mutation(`${DESIGN_ROOT}/workspaces/${encodeURIComponent(workspaceId)}/archive`, {}),
    restoreWorkspace: (workspaceId) => mutation(`${DESIGN_ROOT}/workspaces/${encodeURIComponent(workspaceId)}/restore`, {}),
    getWorkspaceSummary: (workspaceId, signal) => request(`${DESIGN_ROOT}/workspaces/${encodeURIComponent(workspaceId)}/summary`, { signal }),
    listExperienceBriefs: brief.list,
    createExperienceBrief: brief.create,
    getExperienceBrief: brief.get,
    updateExperienceBrief: brief.update,
    listExperienceBriefVersions: brief.versions,
    listResearchStudies: research.list,
    createResearchStudy: research.create,
    getResearchStudy: research.get,
    updateResearchStudy: research.update,
    addResearchFinding: (researchId, payload) => mutation(`${DESIGN_ROOT}/research/${encodeURIComponent(researchId)}/findings`, payload),
    completeResearchStudy: (researchId) => mutation(`${DESIGN_ROOT}/research/${encodeURIComponent(researchId)}/complete`, {}),
    listPersonas: personas.list,
    createPersona: personas.create,
    getPersona: personas.get,
    updatePersona: personas.update,
    listPersonaVersions: personas.versions,
    listJourneys: journeys.list,
    createJourney: journeys.create,
    getJourney: journeys.get,
    updateJourney: journeys.update,
    addJourneyStage: (journeyId, payload) => mutation(`${DESIGN_ROOT}/journeys/${encodeURIComponent(journeyId)}/stages`, payload),
    updateJourneyStage: (journeyId, stageId, payload) => mutation(`${DESIGN_ROOT}/journeys/${encodeURIComponent(journeyId)}/stages/${encodeURIComponent(stageId)}`, payload, { method: "PATCH" }),
    listJourneyVersions: journeys.versions,
    listServiceBlueprints: blueprints.list,
    createServiceBlueprint: blueprints.create,
    getServiceBlueprint: blueprints.get,
    updateServiceBlueprint: blueprints.update,
    addServiceBlueprintStep: (blueprintId, payload) => mutation(`${DESIGN_ROOT}/service-blueprints/${encodeURIComponent(blueprintId)}/steps`, payload),
    updateServiceBlueprintStep: (blueprintId, stepId, payload) => mutation(`${DESIGN_ROOT}/service-blueprints/${encodeURIComponent(blueprintId)}/steps/${encodeURIComponent(stepId)}`, payload, { method: "PATCH" }),
    listInformationArchitecture: informationArchitecture.list,
    createInformationArchitecture: informationArchitecture.create,
    getInformationArchitecture: informationArchitecture.get,
    updateInformationArchitecture: informationArchitecture.update,
    addNavigationNode: (iaId, payload) => mutation(`${DESIGN_ROOT}/information-architecture/${encodeURIComponent(iaId)}/nodes`, payload),
    updateNavigationNode: (iaId, nodeId, payload) => mutation(`${DESIGN_ROOT}/information-architecture/${encodeURIComponent(iaId)}/nodes/${encodeURIComponent(nodeId)}`, payload, { method: "PATCH" }),
    deleteNavigationNode: (iaId, nodeId) => mutation(`${DESIGN_ROOT}/information-architecture/${encodeURIComponent(iaId)}/nodes/${encodeURIComponent(nodeId)}`, {}, { method: "DELETE" }),
    validateInformationArchitecture: (iaId) => mutation(`${DESIGN_ROOT}/information-architecture/${encodeURIComponent(iaId)}/validate`, {}),
    listUserFlows: flows.list,
    createUserFlow: flows.create,
    getUserFlow: flows.get,
    updateUserFlow: flows.update,
    addFlowNode: (flowId, payload) => mutation(`${DESIGN_ROOT}/user-flows/${encodeURIComponent(flowId)}/nodes`, payload),
    addFlowEdge: (flowId, payload) => mutation(`${DESIGN_ROOT}/user-flows/${encodeURIComponent(flowId)}/edges`, payload),
    updateFlowNode: (flowId, nodeId, payload) => mutation(`${DESIGN_ROOT}/user-flows/${encodeURIComponent(flowId)}/nodes/${encodeURIComponent(nodeId)}`, payload, { method: "PATCH" }),
    updateFlowEdge: (flowId, edgeId, payload) => mutation(`${DESIGN_ROOT}/user-flows/${encodeURIComponent(flowId)}/edges/${encodeURIComponent(edgeId)}`, payload, { method: "PATCH" }),
    validateUserFlow: (flowId) => mutation(`${DESIGN_ROOT}/user-flows/${encodeURIComponent(flowId)}/validate`, {}),
    listWireframes: wireframes.list,
    createWireframe: wireframes.create,
    getWireframe: wireframes.get,
    updateWireframe: wireframes.update,
    listWireframeVersions: wireframes.versions,
    listScreens: screens.list,
    createScreen: screens.create,
    getScreen: screens.get,
    updateScreen: screens.update,
    listScreenVersions: screens.versions,
    validateScreen: (screenId) => mutation(`${DESIGN_ROOT}/screens/${encodeURIComponent(screenId)}/validate`, {}),
    listDesignSystems: systems.list,
    createDesignSystem: systems.create,
    getDesignSystem: systems.get,
    updateDesignSystem: systems.update,
    publishDesignSystem: (systemId) => mutation(`${DESIGN_ROOT}/systems/${encodeURIComponent(systemId)}/publish`, {}),
    listDesignTokens: tokens.list,
    createDesignToken: tokens.create,
    getDesignToken: tokens.get,
    updateDesignToken: tokens.update,
    deleteDesignToken: tokens.archive,
    validateDesignTokens: (payload) => mutation(`${DESIGN_ROOT}/tokens/validate`, payload),
    exportDesignTokens: (payload) => mutation(`${DESIGN_ROOT}/tokens/export`, payload),
    importDesignTokens: (payload) => mutation(`${DESIGN_ROOT}/tokens/import`, payload),
    listThemes: themes.list,
    createTheme: themes.create,
    getTheme: themes.get,
    updateTheme: themes.update,
    validateTheme: (themeId) => mutation(`${DESIGN_ROOT}/themes/${encodeURIComponent(themeId)}/validate`, {}),
    previewTheme: (themeId) => mutation(`${DESIGN_ROOT}/themes/${encodeURIComponent(themeId)}/preview`, {}),
    publishTheme: (themeId) => mutation(`${DESIGN_ROOT}/themes/${encodeURIComponent(themeId)}/publish`, {}),
    listBrands: brands.list,
    createBrand: brands.create,
    getBrand: brands.get,
    updateBrand: brands.update,
    listComponents: components.list,
    createComponent: components.create,
    getComponent: components.get,
    updateComponent: components.update,
    listComponentVersions: components.versions,
    validateComponent: (componentId) => mutation(`${DESIGN_ROOT}/components/${encodeURIComponent(componentId)}/validate`, {}),
    deprecateComponent: (componentId) => mutation(`${DESIGN_ROOT}/components/${encodeURIComponent(componentId)}/deprecate`, {}),
    getComponentImplementationContract: (componentId, signal) => request(`${DESIGN_ROOT}/components/${encodeURIComponent(componentId)}/implementation-contract`, { signal }),
    setComponentImplementationContract: (componentId, payload) => mutation(`${DESIGN_ROOT}/components/${encodeURIComponent(componentId)}/implementation-contract`, payload),
    validateComponentImplementationContract: (componentId) => mutation(`${DESIGN_ROOT}/components/${encodeURIComponent(componentId)}/implementation-contract/validate`, {}),
    publishComponentImplementationContract: (componentId) => mutation(`${DESIGN_ROOT}/components/${encodeURIComponent(componentId)}/implementation-contract/publish`, {}),
    listInteractionPatterns: interactionPatterns.list,
    createInteractionPattern: interactionPatterns.create,
    validateInteractionPattern: (patternId) => mutation(`${DESIGN_ROOT}/interaction-patterns/${encodeURIComponent(patternId)}/validate`, {}),
    listResponsiveSpecifications: responsiveSpecifications.list,
    createResponsiveSpecification: responsiveSpecifications.create,
    getResponsiveSpecification: responsiveSpecifications.get,
    updateResponsiveSpecification: responsiveSpecifications.update,
    validateResponsiveSpecification: (specId) => mutation(`${DESIGN_ROOT}/responsive-specifications/${encodeURIComponent(specId)}/validate`, {}),
    listContentSpecifications: content.list,
    createContentSpecification: content.create,
    getContentSpecification: content.get,
    updateContentSpecification: content.update,
    listLocalizationResources: localization.list,
    createLocalizationResource: localization.create,
    getLocalizationResource: localization.get,
    updateLocalizationResource: localization.update,
    listAccessibilityRequirements: accessibility.list,
    createAccessibilityRequirement: accessibility.create,
    listPrototypes: prototypes.list,
    createPrototype: prototypes.create,
    getPrototype: prototypes.get,
    updatePrototype: prototypes.update,
    validatePrototype: (prototypeId) => mutation(`${DESIGN_ROOT}/prototypes/${encodeURIComponent(prototypeId)}/validate`, {}),
    publishPrototype: (prototypeId) => mutation(`${DESIGN_ROOT}/prototypes/${encodeURIComponent(prototypeId)}/publish`, {}),
    archivePrototype: (prototypeId) => mutation(`${DESIGN_ROOT}/prototypes/${encodeURIComponent(prototypeId)}/archive`, {}),
    listValidationRules: (signal) => safeGet(`${DESIGN_ROOT}/validation/rules`, { signal }).then((body) => body?.rules || []),
    createValidationRule: (payload) => mutation(`${DESIGN_ROOT}/validation/rules`, payload),
    listValidationResults: (signal) => safeGet(`${DESIGN_ROOT}/validation/results`, { signal }).then((body) => body?.results || []),
    validateArtifact: (artifactId) => mutation(`${DESIGN_ROOT}/artifacts/${encodeURIComponent(artifactId)}/validate`, {}),
    listReviews: (signal) => safeGet(`${DESIGN_ROOT}/reviews`, { signal }).then((body) => body?.reviews || []),
    createReview: (payload) => mutation(`${DESIGN_ROOT}/reviews`, payload),
    listApprovals: (signal) => safeGet(`${DESIGN_ROOT}/approvals`, { signal }).then((body) => body?.approvals || []),
    createApproval: (payload) => mutation(`${DESIGN_ROOT}/approvals`, payload),
    listBaselines: (signal) => safeGet(`${DESIGN_ROOT}/baselines`, { signal }).then((body) => body?.baselines || []),
    createBaseline: (payload) => mutation(`${DESIGN_ROOT}/baselines`, payload),
    listTraceabilityLinks: (signal) => safeGet(`${DESIGN_ROOT}/traceability/links`, { signal }).then((body) => body?.links || []),
    createTraceabilityLink: (payload) => mutation(`${DESIGN_ROOT}/traceability/links`, payload),
    getTraceabilityCoverage: (signal) => safeGet(`${DESIGN_ROOT}/traceability/coverage`, { signal }),
    calculateTraceabilityCoverage: (payload) => mutation(`${DESIGN_ROOT}/traceability/coverage/calculate`, payload),
    listTraceabilityGaps: (signal) => safeGet(`${DESIGN_ROOT}/traceability/gaps`, { signal }).then((body) => body?.gaps || []),
    createTraceabilitySnapshot: (payload = {}) => mutation(`${DESIGN_ROOT}/traceability/snapshots`, payload),
    getTraceabilitySnapshot: (snapshotId, signal) => request(`${DESIGN_ROOT}/traceability/snapshots/${encodeURIComponent(snapshotId)}`, { signal }),
    calculateImpact: (payload) => mutation(`${DESIGN_ROOT}/impact`, payload),
    listDrift: (signal) => safeGet(`${DESIGN_ROOT}/drift`, { signal }).then((body) => body?.drift || []),
    calculateDrift: (payload) => mutation(`${DESIGN_ROOT}/drift/calculate`, payload),
    listHandoffs: (signal) => safeGet(`${DESIGN_ROOT}/handoffs`, { signal }).then((body) => body?.handoffs || []),
    listAIGenerations: (signal) => safeGet(`${DESIGN_ROOT}/ai/generations`, { signal }).then((body) => body?.generations || []),
    createAIDesignDraft: (payload) => mutation(`${DESIGN_ROOT}/ai/drafts`, payload),
    createHandoff: (payload) => mutation(`${DESIGN_ROOT}/handoffs`, payload),
    validateHandoff: (handoffId) => mutation(`${DESIGN_ROOT}/handoffs/${encodeURIComponent(handoffId)}/validate`, {}),
    publishHandoff: (handoffId) => mutation(`${DESIGN_ROOT}/handoffs/${encodeURIComponent(handoffId)}/publish`, {}),
    listImports: (signal) => safeGet(`${DESIGN_ROOT}/imports`, { signal }).then((body) => body?.imports || []),
    createImport: (payload) => mutation(`${DESIGN_ROOT}/imports`, payload),
    getImport: (importId, signal) => request(`${DESIGN_ROOT}/imports/${encodeURIComponent(importId)}`, { signal }),
    listExports: (signal) => safeGet(`${DESIGN_ROOT}/exports`, { signal }).then((body) => body?.exports || []),
    createExport: (payload) => mutation(`${DESIGN_ROOT}/exports`, payload),
    getExport: (exportId, signal) => request(`${DESIGN_ROOT}/exports/${encodeURIComponent(exportId)}`, { signal }),
    searchDesign: (payload) => mutation(`${DESIGN_ROOT}/search`, payload),
  };
}
