import { createNovaTechIntegrationClient } from "../../platform/integrationClient.js";

const DEFAULT_TIMEOUT_MS = 12000;

export function createNovaCodeProProductFactoryApi({ baseUrl = "", session = {}, timeoutMs = DEFAULT_TIMEOUT_MS } = {}) {
  const client = createNovaTechIntegrationClient({ baseUrl, session, timeoutMs, fetchImpl: globalThis.fetch });
  const request = (path, options = {}) => client.request(path, options);
  const safeGet = (path) => client.safeGet(path);
  const mutation = (path, body, options = {}) => client.mutation(path, body, options);

  return {
    request,
    getOverview: () => safeGet("/v1/product-factory"),
    getInventory: () => safeGet("/v1/product-factory/inventory"),
    getGaps: () => safeGet("/v1/product-factory/gaps"),
    listArchetypes: () => safeGet("/v1/product-factory/archetypes"),
    cloneArchetype: (archetypeId, payload) => mutation(`/v1/product-factory/archetypes/${encodeURIComponent(archetypeId)}/clone`, payload),
    publishArchetype: (archetypeId) => mutation(`/v1/product-factory/archetypes/${encodeURIComponent(archetypeId)}/publish`, {}),
    deprecateArchetype: (archetypeId) => mutation(`/v1/product-factory/archetypes/${encodeURIComponent(archetypeId)}/deprecate`, {}),
    listRequests: () => safeGet("/v1/product-factory/requests"),
    createRequest: (payload, idempotencyKey) => mutation("/v1/product-factory/requests", payload, { idempotencyKey }),
    getRequest: (requestId) => safeGet(`/v1/product-factory/requests/${encodeURIComponent(requestId)}`),
    submitRequest: (requestId, payload = {}) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/submit`, payload),
    reviewRequest: (requestId, payload = {}) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/review`, payload),
    approveRequest: (requestId, payload = {}) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/approve`, payload),
    rejectRequest: (requestId, payload = {}) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/reject`, payload),
    archiveRequest: (requestId) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/archive`, {}),
    convertRequestToProduct: (requestId) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/convert/product`, {}),
    convertRequestToProject: (requestId) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/convert/project`, {}),
    listBlueprints: () => safeGet("/v1/product-factory/blueprints"),
    createBlueprint: (requestId, payload) => mutation(`/v1/product-factory/requests/${encodeURIComponent(requestId)}/blueprints`, payload),
    getBlueprint: (blueprintId) => safeGet(`/v1/product-factory/blueprints/${encodeURIComponent(blueprintId)}`),
    approveBlueprint: (blueprintId, payload = {}) => mutation(`/v1/product-factory/blueprints/${encodeURIComponent(blueprintId)}/approve`, payload),
    amendBlueprint: (blueprintId, payload = {}) => mutation(`/v1/product-factory/blueprints/${encodeURIComponent(blueprintId)}/amend`, payload),
    listPhases: () => safeGet("/v1/product-factory/phases"),
    transitionPhase: (phaseId, payload) => mutation(`/v1/product-factory/phases/${encodeURIComponent(phaseId)}/transition`, payload),
    getTraceability: () => safeGet("/v1/product-factory/traceability"),
    listTraceabilityLinks: () => safeGet("/v1/product-factory/traceability/links"),
    createTraceabilityLink: (payload) => mutation("/v1/product-factory/traceability/links", payload),
    getTraceabilityLink: (linkId) => safeGet(`/v1/product-factory/traceability/links/${encodeURIComponent(linkId)}`),
    deleteTraceabilityLink: (linkId) => client.request(`/v1/product-factory/traceability/links/${encodeURIComponent(linkId)}`, { method: "DELETE" }),
    validateTraceability: () => mutation("/v1/product-factory/traceability/validate", {}),
    getTraceabilityCoverage: () => safeGet("/v1/product-factory/traceability/coverage"),
    getTraceabilityGaps: () => safeGet("/v1/product-factory/traceability/gaps"),
    exportTraceability: (payload = {}) => mutation("/v1/product-factory/traceability/export", payload),
    listRequirements: () => safeGet("/v1/product-factory/requirements"),
    createRequirement: (payload) => mutation("/v1/product-factory/requirements", payload),
    getRequirement: (requirementId) => safeGet(`/v1/product-factory/requirements/${encodeURIComponent(requirementId)}`),
    linkRequirement: (requirementId, payload) => mutation(`/v1/product-factory/requirements/${encodeURIComponent(requirementId)}/links`, payload),
    listLifecycleTemplates: () => safeGet("/v1/product-factory/lifecycle-templates"),
    createLifecycleTemplate: (payload) => mutation("/v1/product-factory/lifecycle-templates", payload),
    publishLifecycleTemplate: (templateId) => mutation(`/v1/product-factory/lifecycle-templates/${encodeURIComponent(templateId)}/publish`, {}),
    createLifecycle: (productId, payload) => mutation(`/v1/product-factory/products/${encodeURIComponent(productId)}/lifecycles`, payload),
    getLifecycle: (lifecycleId) => safeGet(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}`),
    startLifecycle: (lifecycleId) => mutation(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/start`, {}),
    transitionLifecycle: (lifecycleId, payload) => mutation(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/transition`, payload),
    pauseLifecycle: (lifecycleId) => mutation(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/pause`, {}),
    resumeLifecycle: (lifecycleId) => mutation(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/resume`, {}),
    cancelLifecycle: (lifecycleId) => mutation(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/cancel`, {}),
    rollbackLifecycle: (lifecycleId) => mutation(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/rollback`, {}),
    getLifecycleReadiness: (lifecycleId) => safeGet(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/readiness`),
    getLifecycleTimeline: (lifecycleId) => safeGet(`/v1/product-factory/lifecycles/${encodeURIComponent(lifecycleId)}/timeline`),
    listWorkflowDefinitions: () => safeGet("/v1/product-factory/workflows/definitions"),
    createWorkflowDefinition: (payload) => mutation("/v1/product-factory/workflows/definitions", payload),
    publishWorkflowDefinition: (definitionId) => mutation(`/v1/product-factory/workflows/definitions/${encodeURIComponent(definitionId)}/publish`, {}),
    deprecateWorkflowDefinition: (definitionId) => mutation(`/v1/product-factory/workflows/definitions/${encodeURIComponent(definitionId)}/deprecate`, {}),
    createWorkflowInstance: (payload) => mutation("/v1/product-factory/workflows/instances", payload),
    getWorkflowInstance: (instanceId) => safeGet(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}`),
    transitionWorkflowInstance: (instanceId, payload) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/transition`, payload),
    approveWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/approve`, {}),
    rejectWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/reject`, {}),
    pauseWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/pause`, {}),
    resumeWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/resume`, {}),
    cancelWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/cancel`, {}),
    retryWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/retry`, {}),
    compensateWorkflowInstance: (instanceId) => mutation(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/compensate`, {}),
    getWorkflowEvents: (instanceId) => safeGet(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/events`),
    getWorkflowEvidence: (instanceId) => safeGet(`/v1/product-factory/workflows/instances/${encodeURIComponent(instanceId)}/evidence`),
    listReleases: () => safeGet("/v1/product-factory/releases"),
    createRelease: (payload) => mutation("/v1/product-factory/releases", payload),
    getRelease: (releaseId) => safeGet(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}`),
    registerReleaseCandidate: (releaseId, payload) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/candidates`, payload),
    registerReleaseArtifact: (releaseId, payload) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/artifacts`, payload),
    registerReleaseEvidence: (releaseId, payload) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/evidence`, payload),
    evaluateRelease: (releaseId) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/evaluate`, {}),
    getReleaseReadiness: (releaseId) => safeGet(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/readiness`),
    getReleaseBlockers: (releaseId) => safeGet(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/blockers`),
    createReleaseException: (releaseId, payload) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/exceptions`, payload),
    createReleaseApproval: (releaseId, payload) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/approvals`, payload),
    decideRelease: (releaseId, payload) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/decision`, payload),
    exportPrr: (releaseId) => mutation(`/v1/product-factory/releases/${encodeURIComponent(releaseId)}/export-prr`, {}),
    search: (payload = {}) => safeGet(`/v1/product-factory/search?query=${encodeURIComponent(payload.query || "")}&product=${encodeURIComponent(payload.product || "")}`),
    searchPost: (payload = {}) => mutation("/v1/product-factory/search", payload),
    reportCatalog: () => safeGet("/v1/product-factory/reports/catalog"),
    runReport: (payload) => mutation("/v1/product-factory/reports/run", payload),
    getReport: (reportId) => safeGet(`/v1/product-factory/reports/${encodeURIComponent(reportId)}`),
    exportReport: (reportId, payload = {}) => mutation(`/v1/product-factory/reports/${encodeURIComponent(reportId)}/export`, payload),
    getDashboard: (kind) => safeGet(`/v1/product-factory/dashboards/${encodeURIComponent(kind)}`),
    getCrossProductGraph: () => safeGet("/v1/product-factory/cross-product/graph"),
    createCrossProductRelationship: (payload) => mutation("/v1/product-factory/cross-product/relationships", payload),
    getCrossProductImpact: (entityType, entityId) => safeGet(`/v1/product-factory/cross-product/impact/${encodeURIComponent(entityType)}/${encodeURIComponent(entityId)}`),
    getCrossProductDependencies: (releaseId) => safeGet(`/v1/product-factory/cross-product/releases/${encodeURIComponent(releaseId)}/dependencies`),
    validateCrossProduct: () => mutation("/v1/product-factory/cross-product/validate", {}),
    listMigrations: () => safeGet("/v1/product-factory/migrations"),
    createMigration: (payload) => mutation("/v1/product-factory/migrations", payload),
    getMigration: (migrationId) => safeGet(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}`),
    assessMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/assess`, {}),
    mapMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/map`, {}),
    previewMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/preview`, {}),
    approveMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/approve`, {}),
    executeMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/execute`, {}),
    pauseMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/pause`, {}),
    resumeMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/resume`, {}),
    validateMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/validate`, {}),
    reconcileMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/reconcile`, {}),
    rollbackMigration: (migrationId) => mutation(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/rollback`, {}),
    getMigrationEvidence: (migrationId) => safeGet(`/v1/product-factory/migrations/${encodeURIComponent(migrationId)}/evidence`),
    getPrr: (releaseId) => safeGet(`/v1/product-factory/prr/${encodeURIComponent(releaseId)}`),
    listEvidence: () => safeGet("/v1/product-factory/evidence"),
    createEvidence: (payload) => mutation("/v1/product-factory/evidence", payload),
    listAudit: (limit = 100) => safeGet(`/v1/product-factory/audit?limit=${encodeURIComponent(limit)}`),
    listImprovements: () => safeGet("/v1/product-factory/improvement-backlog"),
    createImprovement: (payload) => mutation("/v1/product-factory/improvements", payload),
    createDemoProduct: () => mutation("/v1/product-factory/demo", {}),
    createGateDecision: (payload) => mutation("/v1/product-factory/gates", payload),
    listGates: () => safeGet("/v1/product-factory/gates"),
    createIdempotencyKey: () => client.createIdempotencyKey(),
    createCorrelationId: () => client.createCorrelationId(),
  };
}
