import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "employee",
  appName: "NovaID Employee",
  packageId: "com.novatech.novaid.employee",
  tagline: "Employee identity, access, attendance, and HR workflows.",
  trustTheme: "#6d4aff",
  tabs: [
    { key: "id", label: "ID", description: "Employee identity card and status." },
    { key: "access", label: "Access", description: "Building access QR and device trust." },
    { key: "attendance", label: "Attendance", description: "Check in and check out flow." },
    { key: "hr", label: "HR", description: "Leave requests and expense claims." },
    { key: "wallet", label: "Wallet", description: "Payroll wallet and benefit balance." },
    { key: "profile", label: "Profile", description: "Employee support and audit history." },
  ],
  actions: [
    { label: "Show Employee ID", detail: "Render the live employee identity card and access proof." },
    { label: "Check In", detail: "Start attendance tracking for the current shift." },
    { label: "Check Out", detail: "Close attendance and export the shift record." },
    { label: "Request Leave", detail: "Submit a leave request to HR for review." },
    { label: "Submit Expense", detail: "Create an expense claim with receipt replay." },
    { label: "Open Access QR", detail: "Display the access QR for the building or campus." },
  ],
  primaryFlow: [
    "Employee onboarding",
    "Access pass issued",
    "Check in",
    "Attendance recorded",
    "Leave or expense request",
    "HR review",
    "Wallet settlement",
  ],
  seed: {
    displayName: "Nova Employee",
    walletLabel: "Employee identity wallet",
    trustLevel: "Verified",
    identityScore: 91,
    credentialCount: 3,
    trustedDevices: 2,
    governmentIds: 1,
    certificateCount: 1,
    biometricVerified: true,
    passkeyEnabled: true,
    deviceTrustEnabled: true,
    recoveryEnabled: false,
    connectedApps: 3,
    loginHistory: 14,
  },
};
