import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "employee",
  appName: "NovaID Employee",
  packageId: "com.novatech.novaid.employee",
  tagline: "Workforce identity, access, onboarding, tasks, and HR workflows.",
  trustTheme: "#6d4aff",
  tabs: [
    { key: "dashboard", label: "Dashboard", description: "Employee identity, role, and pending tasks." },
    { key: "employment", label: "Employment", description: "Employment verification, manager approval, and role." },
    { key: "access", label: "Access", description: "Permissions, temporary access, and SSO controls." },
    { key: "tasks", label: "Tasks", description: "Onboarding, security training, and compliance tasks." },
    { key: "security", label: "Security", description: "MFA, biometric login, device management, and alerts." },
    { key: "profile", label: "Profile", description: "Employee profile, notifications, and settings." },
    { key: "id", label: "ID", description: "Legacy employee identity card and status." },
    { key: "attendance", label: "Attendance", description: "Legacy check in and check out flow." },
    { key: "hr", label: "HR", description: "Legacy leave requests and expense claims." },
    { key: "wallet", label: "Wallet", description: "Legacy payroll wallet and benefit balance." },
  ],
  actions: [
    { label: "View employee ID", detail: "Open the live employee identity card and role badge." },
    { label: "View employment status", detail: "Review the current employment verification status." },
    { label: "View assigned organization", detail: "Show the organization linked to the employee profile." },
    { label: "View access level", detail: "Inspect the current access level and permissions." },
    { label: "View pending tasks", detail: "See onboarding and compliance tasks waiting to be completed." },
    { label: "Open work apps", detail: "Jump to the assigned work apps and tools." },
    { label: "Verify employment", detail: "Run employment verification through HR approval." },
    { label: "Upload employment document", detail: "Attach a supporting employment document." },
    { label: "View manager approval", detail: "Review the manager approval status." },
    { label: "View department", detail: "Show the employee department." },
    { label: "View job role", detail: "Show the current job role." },
    { label: "View start date", detail: "Display the employment start date." },
    { label: "Request role update", detail: "Request an update to the job role or access group." },
    { label: "View permissions", detail: "Inspect the granted permissions." },
    { label: "Request access", detail: "Request access to a system or workspace." },
    { label: "Request temporary access", detail: "Request a time-bound access grant." },
    { label: "View approval status", detail: "Check the approval status of pending access requests." },
    { label: "Revoke own session", detail: "Revoke the current session from the device list." },
    { label: "Open assigned systems", detail: "Launch the systems assigned to the employee." },
    { label: "Complete onboarding", detail: "Mark onboarding tasks as complete." },
    { label: "Complete security training", detail: "Mark security training as complete." },
    { label: "Complete compliance training", detail: "Mark compliance training as complete." },
    { label: "Submit required document", detail: "Upload a required supporting document." },
    { label: "View pending approvals", detail: "Inspect pending HR or access approvals." },
    { label: "Enable MFA", detail: "Turn on multi-factor authentication." },
    { label: "Enable biometric login", detail: "Turn on biometric login for work access." },
    { label: "Manage work device", detail: "Review or remove the managed work device." },
    { label: "Change PIN", detail: "Rotate the employee PIN." },
    { label: "View login history", detail: "Inspect recent employee login sessions." },
    { label: "Report compromised account", detail: "Escalate a compromised account for review." },
    { label: "Edit employee profile", detail: "Update the employee profile details." },
    { label: "Update phone", detail: "Change the mobile phone number." },
    { label: "Update email", detail: "Change the email address." },
    { label: "Set language", detail: "Choose the preferred language." },
    { label: "Notification settings", detail: "Adjust work notification preferences." },
    { label: "Logout", detail: "End the employee session." },
    { label: "Show Employee ID", detail: "Render the live employee identity card and access proof." },
    { label: "Check In", detail: "Start attendance tracking for the current shift." },
    { label: "Check Out", detail: "Close attendance and export the shift record." },
    { label: "Request Leave", detail: "Submit a leave request to HR for review." },
    { label: "Submit Expense", detail: "Create an expense claim with receipt replay." },
    { label: "Open Access QR", detail: "Display the access QR for the building or campus." },
  ],
  primaryFlow: [
    "Employee onboarding",
    "Access pass issued",
    "Check in",
    "Attendance recorded",
    "Leave or expense request",
    "HR review",
    "Wallet settlement",
  ],
  seed: {
    displayName: "Nova Employee",
    walletLabel: "Employee identity wallet",
    trustLevel: "Verified",
    identityScore: 91,
    credentialCount: 3,
    trustedDevices: 2,
    governmentIds: 1,
    certificateCount: 1,
    biometricVerified: true,
    passkeyEnabled: true,
    deviceTrustEnabled: true,
    recoveryEnabled: false,
    connectedApps: 3,
    loginHistory: 14,
  },
};
