export const fallbackSite = {
  brand: "AfriTechnology",
  headline: "Technology you can trust. Platforms built for real life.",
  supporting_message:
    "AfriTechnology builds secure, intelligent, and connected digital platforms for payments, mobility, identity, commerce, healthcare, logistics, government, and enterprise operations.",
  metadata: {
    title: "AfriTechnology | Trusted Digital Platforms",
    canonical: "https://afritechnology.com/",
    robots: "index,follow",
  },
  navigation: [
    { label: "Platform", href: "/platform" },
    { label: "Products", href: "/products" },
    { label: "Apps", href: "/apps" },
    { label: "Solutions", href: "/solutions" },
    { label: "Developers", href: "/developers" },
    { label: "Trust Center", href: "/trust" },
    { label: "Company", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  shell: {
    navigation: [
      { label: "Explore", href: "/" },
      { label: "Products", href: "/products" },
      { label: "Apps", href: "/apps" },
      { label: "Solutions", href: "/solutions" },
      { label: "Industries", href: "/industries" },
      { label: "Developers", href: "/developers" },
      { label: "Partners", href: "/partners" },
      { label: "Support", href: "/support" },
      { label: "Trust", href: "/trust" },
      { label: "Company", href: "/about" },
    ],
    quick_actions: [
      { label: "Start a project", href: "/contact" },
      { label: "Open dashboard", href: "/dashboard" },
      { label: "Search knowledge", href: "/knowledge" },
      { label: "Verify evidence", href: "/verify" },
      { label: "View downloads", href: "/downloads" },
    ],
    assistant_prompts: [
      "Find the right product for payments or mobility",
      "Show me the trusted developer path",
      "Open my workspace dashboard",
      "Help me verify a release or receipt",
      "Explain the difference between public and private surfaces",
    ],
    workspace_options: [
      { key: "guest", label: "Guest", description: "Public browsing with approved discovery content." },
      { key: "customer", label: "Customer", description: "Open products, downloads, support, and saved items." },
      { key: "enterprise", label: "Enterprise", description: "Projects, approvals, evidence, and AI recommendations." },
      { key: "partner", label: "Partner", description: "Integration, certification, and partner program access." },
    ],
    language_options: [
      { code: "en", label: "English" },
      { code: "fr", label: "Français" },
      { code: "sw", label: "Kiswahili" },
    ],
    capabilities: [
      "Global search",
      "AI assistant",
      "Command palette",
      "Workspace switching",
      "Theme switching",
      "Notifications",
    ],
  },
  portal_destinations: {
    app: "https://app.afritechnology.com",
    novacodepro: "https://novacodepro.afritechnology.com",
    developer: "https://developer.afritechnology.com",
    trust: "https://trust.afritechnology.com",
    verify: "https://verify.afritechnology.com",
    status: "https://status.afritechnology.com",
    support: "https://support.afritechnology.com",
  },
  launcher: [
    {
      audience: "Customers",
      name: "NovaRide Rider",
      slug: "novaride-rider",
      icon: "RR",
      summary: "Book rides, review receipts, and verify trip evidence.",
      availability: "Controlled Pilot",
      authentication_required: true,
      version: "2026.1.3",
      region: "Australia",
      health: "Healthy",
      release_channel: "Public pilot",
      url: "https://app.afritechnology.com",
    },
    {
      audience: "Customers",
      name: "NovaRide Driver",
      slug: "novaride-driver",
      icon: "RD",
      summary: "Driver shifts, earnings, safety checks, and trip handling.",
      availability: "Controlled Pilot",
      authentication_required: true,
      version: "2026.1.3",
      region: "Australia",
      health: "Healthy",
      release_channel: "Public pilot",
      url: "https://app.afritechnology.com",
    },
    {
      audience: "Businesses",
      name: "NovaPay Merchant",
      slug: "novapay-merchant",
      icon: "PM",
      summary: "Payment operations, settlement, and merchant verification.",
      availability: "Controlled Pilot",
      authentication_required: true,
      version: "2026.1.3",
      region: "Australia",
      health: "Healthy",
      release_channel: "Public pilot",
      url: "https://business.afritechnology.com",
    },
    {
      audience: "Partners",
      name: "NovaID Partner",
      slug: "novaid-partner",
      icon: "ID",
      summary: "Federated access, certification, and integration management.",
      availability: "Partner Access",
      authentication_required: true,
      version: "2026.1",
      region: "Australia",
      health: "Healthy",
      release_channel: "Partner access",
      url: "https://identity.afritechnology.com",
    },
    {
      audience: "Employees",
      name: "NovaCodePro",
      slug: "novacodepro-workspace",
      icon: "CP",
      summary: "Requirements, architecture, delivery, and operational evidence.",
      availability: "Available",
      authentication_required: true,
      version: "2026.1",
      region: "Australia",
      health: "Healthy",
      release_channel: "General availability",
      url: "https://novacodepro.afritechnology.com",
    },
    {
      audience: "Developers",
      name: "Developer Portal",
      slug: "developer-portal",
      icon: "API",
      summary: "API explorer, SDK downloads, docs, sandbox, and status.",
      availability: "Available",
      authentication_required: false,
      version: "2026.1",
      region: "Global",
      health: "Healthy",
      release_channel: "General availability",
      url: "https://developer.afritechnology.com",
    },
    {
      audience: "Employees",
      name: "NovaRide Operator",
      slug: "novaride-operator",
      icon: "OP",
      summary: "Operational control, dispatch oversight, and incident handling.",
      availability: "Private",
      authentication_required: true,
      version: "2026.1.3",
      region: "Australia",
      health: "Healthy",
      release_channel: "Private preview",
      url: "https://operator.afritechnology.com",
    },
    {
      audience: "Employees",
      name: "NovaRide Fleet",
      slug: "novaride-fleet",
      icon: "FL",
      summary: "Fleet oversight, utilization, and managed operations.",
      availability: "Private",
      authentication_required: true,
      version: "2026.1.3",
      region: "Australia",
      health: "Healthy",
      release_channel: "Private preview",
      url: "https://operator.afritechnology.com",
    },
    {
      audience: "Businesses",
      name: "NovaPay Business",
      slug: "novapay-business",
      icon: "PB",
      summary: "Business payments, settlement, approvals, and reporting.",
      availability: "Controlled Pilot",
      authentication_required: true,
      version: "2026.1.3",
      region: "Australia",
      health: "Healthy",
      release_channel: "Public pilot",
      url: "https://business.afritechnology.com",
    },
    {
      audience: "Public",
      name: "Support Center",
      slug: "support-center",
      icon: "SU",
      summary: "Service requests, escalation paths, and response tracking.",
      availability: "Available",
      authentication_required: false,
      version: "2026.1",
      region: "Global",
      health: "Healthy",
      release_channel: "General availability",
      url: "https://support.afritechnology.com",
    },
  ],
  downloads: [
    {
      category: "Android",
      name: "NovaRide Rider",
      version: "2026.1.3",
      checksum: "949108d090c449888688d59085244b8a21406ef0fd1af62c183cc570fcf53160",
      signature: "release_certificate.pem",
      published_at: "2026-07-15T00:00:00+00:00",
      supported_platforms: ["Android 10+"],
      release_notes: "/downloads#novaride-rider",
      href: "https://download.afritechnology.com/novaride/rider.apk",
    },
    {
      category: "Android",
      name: "NovaRide Driver",
      version: "2026.1.3",
      checksum: "32f71600203ff78cb1f507cbe0f447fa5fa89506e3b29e3306102512461730b1",
      signature: "release_certificate.pem",
      published_at: "2026-07-15T00:00:00+00:00",
      supported_platforms: ["Android 10+"],
      release_notes: "/downloads#novaride-driver",
      href: "https://download.afritechnology.com/novaride/driver.apk",
    },
    {
      category: "Android",
      name: "NovaPay Consumer",
      version: "2026.1.3",
      checksum: "signature-required",
      signature: "release_certificate.pem",
      published_at: "2026-07-15T00:00:00+00:00",
      supported_platforms: ["Android 10+"],
      release_notes: "/downloads#novapay-consumer",
      href: "https://download.afritechnology.com/novapay/consumer.apk",
    },
    {
      category: "Android",
      name: "NovaID Personal",
      version: "2026.1.3",
      checksum: "signature-required",
      signature: "release_certificate.pem",
      published_at: "2026-07-15T00:00:00+00:00",
      supported_platforms: ["Android 10+"],
      release_notes: "/downloads#novaid-personal",
      href: "https://download.afritechnology.com/novaid/personal.apk",
    },
    {
      category: "SDKs",
      name: "Nova API SDK",
      version: "2026.1",
      checksum: "signature-required",
      signature: "sdk-signature.pem",
      published_at: "2026-07-15T00:00:00+00:00",
      supported_platforms: ["TypeScript", "Python"],
      release_notes: "/developers",
      href: "/developers",
    },
    {
      category: "Evidence Packages",
      name: "Release certificate",
      version: "2026.1.3",
      checksum: "d728b8b26f9acfbc1cd66cca60dbb86aa3663cf2943d06b6aa12600e509b1cc8",
      signature: "release_certificate.pem",
      published_at: "2026-07-15T00:00:00+00:00",
      supported_platforms: ["Public verification"],
      release_notes: "/verify",
      href: "https://download.afritechnology.com/novaride/releases/2026.1.3/release_certificate.pem",
    },
  ],
  verifications: [
    {
      category: "Receipts",
      name: "Receipt verification",
      summary: "Validate signed receipts against public evidence records.",
      lookup: "/verify",
      evidence: "Receipt identifiers, timestamps, and public signatures.",
    },
    {
      category: "Payments",
      name: "Payment verification",
      summary: "Check approved payment evidence and transaction references.",
      lookup: "/verify",
      evidence: "Payment approval, settlement, and reconciliation records.",
    },
    {
      category: "Releases",
      name: "Release verification",
      summary: "Confirm a release certificate and signed artifact checksum.",
      lookup: "/downloads",
      evidence: "Artifact checksums, signatures, and publication dates.",
    },
    {
      category: "Certificates",
      name: "Certificate verification",
      summary: "Review readiness and operational certification evidence.",
      lookup: "/trust",
      evidence: "Readiness, trust, and governance records.",
    },
    {
      category: "Trust",
      name: "Evidence lookup",
      summary: "Find the public record associated with a verified claim.",
      lookup: "/trust",
      evidence: "Owner, scope, status, and evidence reference.",
    },
  ],
  documentation_sections: [
    { title: "Developer Docs", summary: "API reference, SDKs, sandbox, and status.", href: "/developers" },
    { title: "Quick Starts", summary: "Launch guides for customers, businesses, partners, and developers.", href: "/knowledge" },
    { title: "Architecture", summary: "Governance, platform, products, and app layers.", href: "/architecture" },
    { title: "Security", summary: "Trust, verification, and release integrity.", href: "/trust" },
    { title: "Support", summary: "Guided support entry and contact workflow.", href: "/support" },
  ],
};

export const fallbackProducts = [
  {
    product_id: "NOVACODEPRO",
    name: "NovaCodePro",
    slug: "novacodepro",
    family: "Enterprise Platform",
    summary: "Governed delivery from requirements to operational evidence.",
    audiences: ["Enterprise", "Developers", "Operations"],
    industries: ["Technology", "Government"],
    features: ["Requirements", "Architecture", "Governance", "Operational verification"],
    regions: ["Australia", "Africa"],
    availability: "Available",
    lifecycle: "Available",
    portal_url: "https://novacodepro.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVARIDE",
    name: "NovaRide",
    slug: "novaride",
    family: "Mobility",
    summary: "Trust-governed mobility operations for riders, drivers, fleets, and dispatch.",
    audiences: ["Customers", "Businesses", "Operators"],
    industries: ["Mobility", "Logistics"],
    features: ["Ride operations", "Driver tools", "Fleet controls", "Safety evidence"],
    regions: ["Australia", "DRC", "Burundi"],
    availability: "Controlled Pilot",
    lifecycle: "Controlled Pilot",
    portal_url: "https://app.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVAPAY",
    name: "NovaPay",
    slug: "novapay",
    family: "Financial Services",
    summary: "Payment, wallet, merchant, settlement, and reconciliation workflows with strict activation governance.",
    audiences: ["Businesses", "Merchants", "Financial Institutions"],
    industries: ["Financial Services", "Commerce"],
    features: ["Wallet workflows", "Merchant tools", "Receipts", "Reconciliation"],
    regions: ["Australia", "Africa"],
    availability: "Controlled Pilot",
    lifecycle: "Controlled Pilot",
    portal_url: "https://business.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVAID",
    name: "NovaID",
    slug: "novaid",
    family: "Identity",
    summary: "Unified identity, access, consent, and assurance for AfriTechnology experiences.",
    audiences: ["Customers", "Businesses", "Employees", "Partners"],
    industries: ["Enterprise", "Government", "Financial Services"],
    features: ["Authentication", "Sessions", "MFA readiness", "Role-aware access"],
    regions: ["Australia", "Africa"],
    availability: "Partner Access",
    lifecycle: "Partner Access",
    portal_url: "https://identity.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVATRUST",
    name: "NovaTrust",
    slug: "novatrust",
    family: "Trust",
    summary: "Evidence, assurance, policy, verification, and governance for trusted operations.",
    audiences: ["Compliance", "Security", "Executives", "Partners"],
    industries: ["Enterprise", "Government", "Financial Services"],
    features: ["Evidence verification", "Trust center", "Policy controls", "Audit history"],
    regions: ["Australia", "Africa"],
    availability: "Available",
    lifecycle: "Available",
    portal_url: "https://trust.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVACOMMERCE",
    name: "NovaCommerce",
    slug: "novacommerce",
    family: "Commerce",
    summary: "Merchant, inventory, checkout, support, and evidence-backed commerce operations.",
    audiences: ["Merchants", "Businesses", "Partners"],
    industries: ["Commerce", "Retail"],
    features: ["Merchant workflows", "Catalog readiness", "Receipt verification"],
    regions: ["Australia", "Africa"],
    availability: "Coming Soon",
    lifecycle: "Coming Soon",
    portal_url: "https://merchant.afritechnology.com",
    verified_at: null,
  },
  {
    product_id: "NOVACLOUD",
    name: "NovaCloud",
    slug: "novacloud",
    family: "Cloud Platform",
    summary: "Regional infrastructure and governed deployment for NovaTech services.",
    audiences: ["Enterprise", "Operations", "Developers"],
    industries: ["Technology", "Government"],
    features: ["Environments", "Deployment gates", "Observability", "Regional controls"],
    regions: ["Australia", "Africa"],
    availability: "Partner Access",
    lifecycle: "Partner Access",
    portal_url: "https://novacodepro.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVAGATEWAY",
    name: "NovaGateway",
    slug: "novagateway",
    family: "Integration",
    summary: "API routing, policy enforcement, and partner integration for public services.",
    audiences: ["Developers", "Enterprise", "Partners"],
    industries: ["Technology", "Commerce", "Government"],
    features: ["API policy", "Routing", "Rate limits", "Webhook controls"],
    regions: ["Australia", "Africa"],
    availability: "Available",
    lifecycle: "Available",
    portal_url: "https://developer.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVADATA",
    name: "NovaData",
    slug: "novadata",
    family: "Data Platform",
    summary: "Trusted operational and analytical data products with governed access.",
    audiences: ["Enterprise", "Developers", "Operations"],
    industries: ["Technology", "Financial Services", "Government"],
    features: ["Operational metrics", "Analytical views", "Lineage", "Access controls"],
    regions: ["Australia", "Africa"],
    availability: "Partner Access",
    lifecycle: "Partner Access",
    portal_url: "https://novacodepro.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVACONNECT",
    name: "NovaConnect",
    slug: "novaconnect",
    family: "Integration",
    summary: "Webhooks, partner integrations, and event contracts for the ecosystem.",
    audiences: ["Developers", "Partners", "Enterprise"],
    industries: ["Technology", "Commerce", "Logistics"],
    features: ["Webhooks", "Event contracts", "Partner routing", "Retries"],
    regions: ["Australia", "Africa"],
    availability: "Available",
    lifecycle: "Available",
    portal_url: "https://developer.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVAGOV",
    name: "NovaGov",
    slug: "novagov",
    family: "Government",
    summary: "Public service workflows and auditable citizen service delivery.",
    audiences: ["Government", "Enterprise"],
    industries: ["Government"],
    features: ["Case handling", "Evidence", "Citizen routing", "Policy controls"],
    regions: ["Australia", "Africa"],
    availability: "Controlled Pilot",
    lifecycle: "Controlled Pilot",
    portal_url: "https://app.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
];

export const fallbackTrust = {
  records: [
    {
      id: "routing-isolation",
      title: "Public root isolated from internal dashboards",
      scope: "afritechnology.com",
      status: "CONFIGURED",
      owner: "Platform Operations",
      evidence_ref: "tests/public_gateway/test_public_gateway.py",
    },
    {
      id: "payment-governance-boundary",
      title: "GA and real-payment activation are separate",
      scope: "NovaPay, NovaRide, NovaCodePro",
      status: "ENFORCED",
      owner: "Risk and Compliance",
      evidence_ref: "afritech/governance/rules/RULE-NOVARIDE-FINANCIAL-BOUNDARY.yaml",
    },
  ],
};

export const fallbackServices = [
  {
    name: "Public Website",
    slug: "public-web",
    url: "https://afritechnology.com",
    domain: "afritechnology.com",
    category: "Public Experience",
    status: "CONFIGURED",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Public",
    icon: "AT",
  },
  {
    name: "Customer Application Gateway",
    slug: "app",
    url: "https://app.afritechnology.com",
    domain: "app.afritechnology.com",
    category: "Customer Portals",
    status: "CONFIGURED",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Australia",
    audience: "Customers",
    icon: "APP",
  },
  {
    name: "NovaCodePro",
    slug: "novacodepro",
    url: "https://novacodepro.afritechnology.com",
    domain: "novacodepro.afritechnology.com",
    category: "Platform",
    status: "CONFIGURED",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1.0",
    release_channel: "General availability",
    health: "Healthy",
    region: "Australia",
    audience: "Employees",
    icon: "CP",
  },
  {
    name: "Developer Portal",
    slug: "developer",
    url: "https://developer.afritechnology.com",
    domain: "developer.afritechnology.com",
    category: "Platform",
    status: "CONFIGURED",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Developers",
    icon: "DEV",
  },
  {
    name: "Operator Workspace",
    slug: "operator",
    url: "https://operator.afritechnology.com",
    domain: "operator.afritechnology.com",
    category: "Customer Portals",
    status: "PRIVATE",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1",
    release_channel: "Private preview",
    health: "Planned",
    region: "Australia",
    audience: "Employees",
    icon: "OP",
  },
  {
    name: "Business Portal",
    slug: "business",
    url: "https://business.afritechnology.com",
    domain: "business.afritechnology.com",
    category: "Customer Portals",
    status: "CONFIGURED",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Australia",
    audience: "Businesses",
    icon: "BUS",
  },
  {
    name: "NovaRide Rider",
    slug: "novaride-rider",
    url: "https://app.afritechnology.com",
    domain: "app.afritechnology.com",
    category: "Customer Portals",
    status: "CONTROLLED_PILOT",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1.3",
    release_channel: "Public pilot",
    health: "Healthy",
    region: "Australia",
    audience: "Customers",
    icon: "RR",
  },
  {
    name: "NovaRide Driver",
    slug: "novaride-driver",
    url: "https://app.afritechnology.com",
    domain: "app.afritechnology.com",
    category: "Customer Portals",
    status: "CONTROLLED_PILOT",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1.3",
    release_channel: "Public pilot",
    health: "Healthy",
    region: "Australia",
    audience: "Customers",
    icon: "RD",
  },
  {
    name: "NovaPay Merchant",
    slug: "novapay-merchant",
    url: "https://business.afritechnology.com",
    domain: "business.afritechnology.com",
    category: "Customer Portals",
    status: "CONTROLLED_PILOT",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1.3",
    release_channel: "Public pilot",
    health: "Healthy",
    region: "Australia",
    audience: "Businesses",
    icon: "PM",
  },
  {
    name: "NovaID Partner",
    slug: "novaid-partner",
    url: "https://identity.afritechnology.com",
    domain: "identity.afritechnology.com",
    category: "Partner Portals",
    status: "PARTNER_ACCESS",
    indexing: "noindex,nofollow",
    authentication_required: true,
    version: "2026.1",
    release_channel: "Partner access",
    health: "Healthy",
    region: "Australia",
    audience: "Partners",
    icon: "ID",
  },
  {
    name: "Trust Center",
    slug: "trust-center",
    url: "https://trust.afritechnology.com",
    domain: "trust.afritechnology.com",
    category: "Public Experience",
    status: "CONFIGURED",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Public",
    icon: "TR",
  },
  {
    name: "Evidence Verification",
    slug: "verify-center",
    url: "https://verify.afritechnology.com",
    domain: "verify.afritechnology.com",
    category: "Public Experience",
    status: "AVAILABLE",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Public",
    icon: "VR",
  },
  {
    name: "Download Center",
    slug: "download-center",
    url: "https://download.afritechnology.com",
    domain: "download.afritechnology.com",
    category: "Public Experience",
    status: "CONFIGURED",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Public",
    icon: "DL",
  },
  {
    name: "Support Center",
    slug: "support-center",
    url: "https://support.afritechnology.com",
    domain: "support.afritechnology.com",
    category: "Public Experience",
    status: "CONFIGURED",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Public",
    icon: "SU",
  },
  {
    name: "Developer Docs",
    slug: "developer-docs",
    url: "https://developer.afritechnology.com",
    domain: "developer.afritechnology.com",
    category: "Developer Platform",
    status: "CONFIGURED",
    indexing: "index,follow",
    authentication_required: false,
    version: "2026.1",
    release_channel: "General availability",
    health: "Healthy",
    region: "Global",
    audience: "Developers",
    icon: "DOC",
  },
];

export const audiences = {
  Customers: {
    benefits: ["Find trusted products", "Get support", "Verify receipts and evidence"],
    products: ["NovaRide", "NovaPay", "NovaID"],
    cta: "Open customer gateway",
    href: "https://app.afritechnology.com",
  },
  Businesses: {
    benefits: ["Launch commerce and payments", "Manage operations", "Use evidence-backed workflows"],
    products: ["NovaPay", "NovaCommerce", "NovaCodePro"],
    cta: "Start a business enquiry",
    href: "/contact",
  },
  Enterprises: {
    benefits: ["Govern delivery", "Verify operations", "Modernize workflows"],
    products: ["NovaCodePro", "NovaTrust", "NovaAI"],
    cta: "Explore enterprise platform",
    href: "/platform",
  },
  Developers: {
    benefits: ["Explore APIs", "Review SDKs", "Build against governed contracts"],
    products: ["NovaCodePro", "NovaID", "NovaConnect"],
    cta: "Open developer platform",
    href: "/developers",
  },
  Partners: {
    benefits: ["Integrate safely", "Review trust requirements", "Coordinate pilots"],
    products: ["NovaTrust", "NovaPay", "NovaRide"],
    cta: "Become a partner",
    href: "/contact",
  },
  Governments: {
    benefits: ["Modernize services", "Protect citizen workflows", "Use auditable delivery"],
    products: ["NovaGov", "NovaTrust", "NovaID"],
    cta: "Discuss public sector needs",
    href: "/contact",
  },
};
