export const fallbackSite = {
  brand: "AfriTechnology",
  headline: "Technology you can trust. Platforms built for real life.",
  supporting_message:
    "AfriTechnology builds secure, intelligent, and connected digital platforms for payments, mobility, identity, commerce, healthcare, logistics, government, and enterprise operations.",
  metadata: {
    title: "AfriTechnology | Trusted Digital Platforms",
    canonical: "https://afritechnology.com/",
    robots: "index,follow",
  },
  navigation: [
    { label: "Platform", href: "/platform" },
    { label: "Products", href: "/products" },
    { label: "Solutions", href: "/solutions" },
    { label: "Developers", href: "/developers" },
    { label: "Trust Center", href: "/trust" },
    { label: "Company", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  portal_destinations: {
    app: "https://app.afritechnology.com",
    novacodepro: "https://novacodepro.afritechnology.com",
    developer: "https://developer.afritechnology.com",
    trust: "https://trust.afritechnology.com",
    verify: "https://verify.afritechnology.com",
    status: "https://status.afritechnology.com",
    support: "https://support.afritechnology.com",
  },
};

export const fallbackProducts = [
  {
    product_id: "NOVACODEPRO",
    name: "NovaCodePro",
    slug: "novacodepro",
    family: "Enterprise Platform",
    summary: "Governed delivery from requirements to operational evidence.",
    audiences: ["Enterprise", "Developers", "Operations"],
    industries: ["Technology", "Government"],
    features: ["Requirements", "Architecture", "Governance", "Operational verification"],
    regions: ["Australia", "Africa"],
    availability: "Available",
    lifecycle: "Available",
    portal_url: "https://novacodepro.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVARIDE",
    name: "NovaRide",
    slug: "novaride",
    family: "Mobility",
    summary: "Trust-governed mobility operations for riders, drivers, fleets, and dispatch.",
    audiences: ["Customers", "Businesses", "Operators"],
    industries: ["Mobility", "Logistics"],
    features: ["Ride operations", "Driver tools", "Fleet controls", "Safety evidence"],
    regions: ["Australia", "DRC", "Burundi"],
    availability: "Controlled Pilot",
    lifecycle: "Controlled Pilot",
    portal_url: "https://app.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVAPAY",
    name: "NovaPay",
    slug: "novapay",
    family: "Financial Services",
    summary: "Payment, wallet, merchant, settlement, and reconciliation workflows with strict activation governance.",
    audiences: ["Businesses", "Merchants", "Financial Institutions"],
    industries: ["Financial Services", "Commerce"],
    features: ["Wallet workflows", "Merchant tools", "Receipts", "Reconciliation"],
    regions: ["Australia", "Africa"],
    availability: "Controlled Pilot",
    lifecycle: "Controlled Pilot",
    portal_url: "https://business.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVAID",
    name: "NovaID",
    slug: "novaid",
    family: "Identity",
    summary: "Unified identity, access, consent, and assurance for AfriTechnology experiences.",
    audiences: ["Customers", "Businesses", "Employees", "Partners"],
    industries: ["Enterprise", "Government", "Financial Services"],
    features: ["Authentication", "Sessions", "MFA readiness", "Role-aware access"],
    regions: ["Australia", "Africa"],
    availability: "Partner Access",
    lifecycle: "Partner Access",
    portal_url: "https://identity.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVATRUST",
    name: "NovaTrust",
    slug: "novatrust",
    family: "Trust",
    summary: "Evidence, assurance, policy, verification, and governance for trusted operations.",
    audiences: ["Compliance", "Security", "Executives", "Partners"],
    industries: ["Enterprise", "Government", "Financial Services"],
    features: ["Evidence verification", "Trust center", "Policy controls", "Audit history"],
    regions: ["Australia", "Africa"],
    availability: "Available",
    lifecycle: "Available",
    portal_url: "https://trust.afritechnology.com",
    verified_at: "2026-07-15T00:00:00+00:00",
  },
  {
    product_id: "NOVACOMMERCE",
    name: "NovaCommerce",
    slug: "novacommerce",
    family: "Commerce",
    summary: "Merchant, inventory, checkout, support, and evidence-backed commerce operations.",
    audiences: ["Merchants", "Businesses", "Partners"],
    industries: ["Commerce", "Retail"],
    features: ["Merchant workflows", "Catalog readiness", "Receipt verification"],
    regions: ["Australia", "Africa"],
    availability: "Coming Soon",
    lifecycle: "Coming Soon",
    portal_url: "https://merchant.afritechnology.com",
    verified_at: null,
  },
];

export const fallbackTrust = {
  records: [
    {
      id: "routing-isolation",
      title: "Public root isolated from internal dashboards",
      scope: "afritechnology.com",
      status: "CONFIGURED",
      owner: "Platform Operations",
      evidence_ref: "tests/public_gateway/test_public_gateway.py",
    },
    {
      id: "payment-governance-boundary",
      title: "GA and real-payment activation are separate",
      scope: "NovaPay, NovaRide, NovaCodePro",
      status: "ENFORCED",
      owner: "Risk and Compliance",
      evidence_ref: "afritech/governance/rules/RULE-NOVARIDE-FINANCIAL-BOUNDARY.yaml",
    },
  ],
};

export const audiences = {
  Customers: {
    benefits: ["Find trusted products", "Get support", "Verify receipts and evidence"],
    products: ["NovaRide", "NovaPay", "NovaID"],
    cta: "Open customer gateway",
    href: "https://app.afritechnology.com",
  },
  Businesses: {
    benefits: ["Launch commerce and payments", "Manage operations", "Use evidence-backed workflows"],
    products: ["NovaPay", "NovaCommerce", "NovaCodePro"],
    cta: "Start a business enquiry",
    href: "/contact",
  },
  Enterprises: {
    benefits: ["Govern delivery", "Verify operations", "Modernize workflows"],
    products: ["NovaCodePro", "NovaTrust", "NovaAI"],
    cta: "Explore enterprise platform",
    href: "/platform",
  },
  Developers: {
    benefits: ["Explore APIs", "Review SDKs", "Build against governed contracts"],
    products: ["NovaCodePro", "NovaID", "NovaConnect"],
    cta: "Open developer platform",
    href: "/developers",
  },
  Partners: {
    benefits: ["Integrate safely", "Review trust requirements", "Coordinate pilots"],
    products: ["NovaTrust", "NovaPay", "NovaRide"],
    cta: "Become a partner",
    href: "/contact",
  },
  Governments: {
    benefits: ["Modernize services", "Protect citizen workflows", "Use auditable delivery"],
    products: ["NovaGov", "NovaTrust", "NovaID"],
    cta: "Discuss public sector needs",
    href: "/contact",
  },
};
