export const WORKFLOW_STAGES = [
  {
    id: "intent",
    label: "Intent Analysis",
    kind: "automation",
    service: "Solution Orchestrator Engine",
    api: "POST /api/solutions/intent",
    storage: "solution_requests",
    audit: "solution.intent.raised",
    ui: "Solution Studio",
    output: "Intent brief",
  },
  {
    id: "business",
    label: "Business Analysis",
    kind: "automation",
    service: "Business AI",
    api: "POST /api/solutions/analysis",
    storage: "solution_artifacts",
    audit: "solution.analysis.generated",
    ui: "Solution Studio",
    output: "Business requirements",
  },
  {
    id: "requirements-approval",
    label: "Requirements Approval",
    kind: "human",
    service: "Human Review & Governance Engine",
    api: "POST /api/approvals/requirements",
    storage: "approvals",
    audit: "solution.requirements.approved",
    ui: "Governance",
    output: "Approved requirements",
  },
  {
    id: "architecture",
    label: "Architecture Design",
    kind: "automation",
    service: "Architecture Studio",
    api: "POST /api/architecture/design",
    storage: "architecture_artifacts",
    audit: "solution.architecture.generated",
    ui: "Architecture Studio",
    output: "C4 and topology pack",
  },
  {
    id: "architecture-approval",
    label: "Architecture Approval",
    kind: "human",
    service: "Human Review & Governance Engine",
    api: "POST /api/approvals/architecture",
    storage: "approvals",
    audit: "solution.architecture.approved",
    ui: "Governance",
    output: "Approved architecture",
  },
  {
    id: "design",
    label: "UI/UX Design",
    kind: "automation",
    service: "UI/UX Studio",
    api: "POST /api/design/generate",
    storage: "design_artifacts",
    audit: "solution.design.generated",
    ui: "UI/UX Studio",
    output: "Wireframes and UI kit",
  },
  {
    id: "implementation",
    label: "Implementation",
    kind: "automation",
    service: "Code Studio",
    api: "POST /api/code/generate",
    storage: "source_repositories",
    audit: "solution.code.generated",
    ui: "Code Studio",
    output: "Scaffold and services",
  },
  {
    id: "testing",
    label: "Testing",
    kind: "automation",
    service: "Test Studio",
    api: "POST /api/tests/run",
    storage: "test_reports",
    audit: "solution.tests.executed",
    ui: "Test Studio",
    output: "Test report",
  },
  {
    id: "security",
    label: "Security Review",
    kind: "automation",
    service: "Security Studio",
    api: "POST /api/security/review",
    storage: "security_reports",
    audit: "solution.security.reviewed",
    ui: "Security Studio",
    output: "Security review",
  },
  {
    id: "compliance-approval",
    label: "Compliance Approval",
    kind: "human",
    service: "Human Review & Governance Engine",
    api: "POST /api/approvals/compliance",
    storage: "approvals",
    audit: "solution.compliance.approved",
    ui: "Governance",
    output: "Compliance signoff",
  },
  {
    id: "deployment",
    label: "Deployment",
    kind: "automation",
    service: "Deployment Studio",
    api: "POST /api/deployments/create",
    storage: "deployment_manifests",
    audit: "solution.deployment.prepared",
    ui: "Deployment Studio",
    output: "Deployment bundle",
  },
  {
    id: "monitoring",
    label: "Monitoring",
    kind: "automation",
    service: "Operations Center",
    api: "GET /api/observability/runtime",
    storage: "runtime_events",
    audit: "solution.monitoring.enabled",
    ui: "Operations Center",
    output: "Monitoring view",
  },
];

export const SERVICE_CATALOG = [
  {
    id: "orchestrator",
    title: "Solution Orchestrator Engine",
    kind: "workflow",
    service: "NovaCodePro Orchestrator",
    api: "/api/solutions",
    storage: "solution_requests",
    audit: "solution.request.created",
    ui: "Solution Studio",
    description: "Coordinates intake, planning, generation, review, and release for every request.",
  },
  {
    id: "business-ai",
    title: "Business AI",
    kind: "analysis",
    service: "Business AI Service",
    api: "/api/analysis/business",
    storage: "business_artifacts",
    audit: "solution.analysis.generated",
    ui: "Solution Studio",
    description: "Converts user intent into scope, requirements, assumptions, and delivery estimates.",
  },
  {
    id: "architecture-studio",
    title: "Architecture Studio",
    kind: "design",
    service: "Architecture Service",
    api: "/api/architecture",
    storage: "architecture_artifacts",
    audit: "solution.architecture.generated",
    ui: "Architecture Studio",
    description: "Produces context diagrams, C4 models, DDD boundaries, and topology exports.",
  },
  {
    id: "uiux-studio",
    title: "UI/UX Studio",
    kind: "design",
    service: "Design Service",
    api: "/api/design",
    storage: "design_artifacts",
    audit: "solution.design.generated",
    ui: "UI/UX Studio",
    description: "Generates journeys, wireframes, components, accessibility notes, and layouts.",
  },
  {
    id: "code-studio",
    title: "Code Studio",
    kind: "engineering",
    service: "Implementation Service",
    api: "/api/code",
    storage: "source_repositories",
    audit: "solution.code.generated",
    ui: "Code Studio",
    description: "Scaffolds repositories, services, frontends, mobile apps, and configuration.",
  },
  {
    id: "data-studio",
    title: "Data Studio",
    kind: "engineering",
    service: "Data Platform Service",
    api: "/api/data",
    storage: "data_catalog",
    audit: "solution.data.generated",
    ui: "Data Studio",
    description: "Creates schemas, migrations, lineage, ETL, backups, and warehouse plans.",
  },
  {
    id: "api-studio",
    title: "API Studio",
    kind: "engineering",
    service: "Integration API Service",
    api: "/api/apis",
    storage: "api_specs",
    audit: "solution.api.generated",
    ui: "API Studio",
    description: "Delivers REST, GraphQL, gRPC, OpenAPI, SDKs, mocks, and contract tests.",
  },
  {
    id: "test-studio",
    title: "Test Studio",
    kind: "governance",
    service: "Verification Service",
    api: "/api/tests",
    storage: "test_reports",
    audit: "solution.tests.executed",
    ui: "Test Studio",
    description: "Runs unit, integration, UI, load, accessibility, and security test suites.",
  },
  {
    id: "security-studio",
    title: "Security Studio",
    kind: "governance",
    service: "Security Review Service",
    api: "/api/security",
    storage: "security_reports",
    audit: "solution.security.reviewed",
    ui: "Security Studio",
    description: "Performs static analysis, dependency scans, secret detection, and threat review.",
  },
  {
    id: "documentation-studio",
    title: "Documentation Studio",
    kind: "support",
    service: "Documentation Service",
    api: "/api/docs",
    storage: "documentation_repository",
    audit: "solution.documentation.generated",
    ui: "Documentation Studio",
    description: "Keeps user guides, runbooks, API docs, and release notes synchronized.",
  },
  {
    id: "deployment-studio",
    title: "Deployment Studio",
    kind: "operations",
    service: "Release & Deployment Service",
    api: "/api/deployments",
    storage: "deployment_manifests",
    audit: "solution.deployment.prepared",
    ui: "Deployment Studio",
    description: "Produces Docker, Kubernetes, Terraform, CI/CD, staging, rollback, and publish plans.",
  },
  {
    id: "operations-center",
    title: "Operations Center",
    kind: "operations",
    service: "Runtime Observability Service",
    api: "/api/observability",
    storage: "runtime_events",
    audit: "solution.monitoring.enabled",
    ui: "Operations Center",
    description: "Shows logs, metrics, traces, alerts, health, and incidents in one live console.",
  },
  {
    id: "audit-service",
    title: "Audit Service",
    kind: "governance",
    service: "Audit Trail Service",
    api: "/api/audit",
    storage: "audit_trail",
    audit: "audit.event.appended",
    ui: "Trust Center",
    description: "Persists every action with actor, timestamp, service, evidence, and decision state.",
  },
];

export const AGENT_MARKETPLACE = [
  {
    id: "banking-agent",
    title: "Banking Solution Agent",
    category: "finance",
    service: "Domain Solution Service",
    api: "/api/agents/banking",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Governed accelerators for banking workflows, payments, ledgers, and compliance.",
  },
  {
    id: "healthcare-agent",
    title: "Healthcare Compliance Agent",
    category: "health",
    service: "Domain Solution Service",
    api: "/api/agents/healthcare",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Industry rules for patient records, compliance, and care journey workflows.",
  },
  {
    id: "ride-hailing-agent",
    title: "Ride-Hailing Agent",
    category: "mobility",
    service: "Domain Solution Service",
    api: "/api/agents/ride-hailing",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Solution packs for rider, driver, dispatch, maps, payments, and operations.",
  },
  {
    id: "erp-agent",
    title: "ERP Agent",
    category: "business",
    service: "Domain Solution Service",
    api: "/api/agents/erp",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Business process automation for procurement, inventory, finance, and approvals.",
  },
  {
    id: "crm-agent",
    title: "CRM Agent",
    category: "customer",
    service: "Domain Solution Service",
    api: "/api/agents/crm",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Customer engagement, support, sales pipeline, and analytics accelerators.",
  },
  {
    id: "government-agent",
    title: "Government Services Agent",
    category: "public-sector",
    service: "Domain Solution Service",
    api: "/api/agents/government",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Citizen services, identity, case management, and policy-driven delivery workflows.",
  },
];

export const SOLUTION_TEMPLATES = [
  {
    id: "ride-hailing",
    title: "Ride-hailing platform",
    request: "Build a ride-hailing platform for Melbourne.",
    surfaces: ["Rider app", "Driver app", "Operations dashboard", "Admin portal"],
    domain: "mobility",
  },
  {
    id: "hospital",
    title: "Hospital management system",
    request: "Build a hospital management system.",
    surfaces: ["Patient portal", "Staff portal", "Clinical workflows", "Admin console"],
    domain: "healthcare",
  },
  {
    id: "money-transfer",
    title: "Money transfer platform",
    request: "Create a money transfer platform between Australia and DR Congo.",
    surfaces: ["Consumer app", "Operations console", "Compliance portal", "Partner API"],
    domain: "finance",
  },
  {
    id: "ecommerce",
    title: "E-commerce platform",
    request: "Build an enterprise e-commerce platform for regional retail.",
    surfaces: ["Storefront", "Admin portal", "Inventory console", "Fulfillment tools"],
    domain: "commerce",
  },
  {
    id: "erp",
    title: "ERP platform",
    request: "Build an ERP platform for a distributed enterprise.",
    surfaces: ["Planning console", "Finance portal", "HR workspace", "Reporting tools"],
    domain: "business",
  },
];

export const PLATFORM_CENTERS = [
  {
    title: "Trust Center",
    summary: "Identities, receipts, certificates, releases, and audit evidence in one governed surface.",
    chips: ["Identities", "Receipts", "Certificates", "Evidence", "Audit"],
  },
  {
    title: "Release Center",
    summary: "Validate, build, test, sign, publish, deploy, observe, and roll back from a single flow.",
    chips: ["Validate", "Build", "Tests", "Sign", "Publish"],
  },
  {
    title: "Observability Center",
    summary: "Latency, error rate, regions, logs, metrics, traces, and alerts remain visible together.",
    chips: ["CPU", "Memory", "Latency", "Logs", "Tracing"],
  },
  {
    title: "Data Center",
    summary: "SQL, NoSQL, storage, analytics, streaming, backups, and replication with shared context.",
    chips: ["SQL", "Warehouse", "Streaming", "Backups", "Replication"],
  },
  {
    title: "Security Center",
    summary: "Zero Trust, NovaID, RBAC, MFA, certificates, secrets, threats, and policies are governed here.",
    chips: ["Zero Trust", "RBAC", "MFA", "Secrets", "Policies"],
  },
  {
    title: "Executive Center",
    summary: "Revenue, MRR, ARR, growth, trust score, and regional performance drive leadership review.",
    chips: ["Revenue", "MRR", "ARR", "Trust", "Forecast"],
  },
];

export const WORKFLOW_SEQUENCE = [
  "intent",
  "business",
  "requirements-approval",
  "architecture",
  "architecture-approval",
  "design",
  "implementation",
  "testing",
  "security",
  "compliance-approval",
  "deployment",
  "monitoring",
];

export const WORKFLOW_LABELS = Object.fromEntries(
  WORKFLOW_STAGES.map((stage) => [stage.id, stage.label]),
);

export const TENANTS = [
  {
    id: "novatech",
    name: "NovaTech",
    tier: "Enterprise",
    regions: ["Australia", "Africa", "Europe"],
    billing: "active",
    quota: "12,000 seats",
    branding: "NovaTech Blue",
    residency: "AU + EU",
  },
  {
    id: "pilot-mobility",
    name: "Pilot Mobility",
    tier: "Pilot",
    regions: ["Australia"],
    billing: "metered",
    quota: "500 seats",
    branding: "NovaRide",
    residency: "AU",
  },
  {
    id: "partner-labs",
    name: "Partner Labs",
    tier: "Sandbox",
    regions: ["Australia", "Asia"],
    billing: "sandbox",
    quota: "200 seats",
    branding: "NovaPartner",
    residency: "AU + APAC",
  },
];

export const PROJECTS = [
  {
    id: "nova-ride-platform",
    name: "NovaRide Platform",
    tenantId: "novatech",
    status: "Active",
    owner: "Platform Engineering",
    solution: "Ride-hailing platform",
    region: "Melbourne",
    budget: "$1.8M",
  },
  {
    id: "nova-pay-core",
    name: "NovaPay Core",
    tenantId: "novatech",
    status: "Review",
    owner: "Payments Engineering",
    solution: "Money transfer platform",
    region: "Sydney",
    budget: "$2.4M",
  },
  {
    id: "health-ops",
    name: "Health Operations",
    tenantId: "partner-labs",
    status: "Discovery",
    owner: "Solutions Team",
    solution: "Hospital management system",
    region: "Johannesburg",
    budget: "$640K",
  },
];

export const COLLABORATION_THREADS = [
  {
    id: "thread-req",
    scope: "Requirements review",
    participants: ["Product", "Finance", "Security"],
    message: "Requirements need a privacy note before the next approval gate.",
    state: "waiting-approval",
  },
  {
    id: "thread-arch",
    scope: "Architecture discussion",
    participants: ["Architecture", "DevOps", "Governance"],
    message: "The trust boundary should remain explicit in the C4 export.",
    state: "active",
  },
  {
    id: "thread-release",
    scope: "Release coordination",
    participants: ["Release", "Operations", "QA"],
    message: "Rollback plan and smoke tests are ready for the staging window.",
    state: "ready",
  },
];

export const KNOWLEDGE_GRAPH = [
  {
    id: "kg-request",
    label: "Business Request",
    type: "intent",
    domain: "Solution intake",
    owner: "Product",
    evidence: "User request captured in NovaCodePro composer",
    links: ["kg-requirements", "kg-approval"],
  },
  {
    id: "kg-requirements",
    label: "Requirements",
    type: "artifact",
    domain: "Definition",
    owner: "Business Analysis",
    evidence: "Approved requirements package",
    links: ["kg-architecture", "kg-design"],
  },
  {
    id: "kg-architecture",
    label: "Architecture",
    type: "artifact",
    domain: "Architecture",
    owner: "Solution Architecture",
    evidence: "C4 and topology pack",
    links: ["kg-api", "kg-deployment"],
  },
  {
    id: "kg-api",
    label: "API Spec",
    type: "artifact",
    domain: "Contracts",
    owner: "API Engineering",
    evidence: "OpenAPI and AsyncAPI specification",
    links: ["kg-tests", "kg-release"],
  },
  {
    id: "kg-tests",
    label: "Test Report",
    type: "evidence",
    domain: "Quality",
    owner: "QA",
    evidence: "Validated execution report",
    links: ["kg-security", "kg-audit"],
  },
  {
    id: "kg-security",
    label: "Security Review",
    type: "evidence",
    domain: "Security",
    owner: "Security",
    evidence: "Security review findings and remediation",
    links: ["kg-audit"],
  },
  {
    id: "kg-deployment",
    label: "Deployment",
    type: "runtime",
    domain: "Release",
    owner: "Release Manager",
    evidence: "Deployment manifest and rollout record",
    links: ["kg-operations"],
  },
  {
    id: "kg-release",
    label: "Release",
    type: "artifact",
    domain: "Release",
    owner: "Release Factory",
    evidence: "Signed release bundle and checksums",
    links: ["kg-operations", "kg-audit"],
  },
  {
    id: "kg-operations",
    label: "Operations",
    type: "runtime",
    domain: "Operations",
    owner: "SRE",
    evidence: "Operational telemetry and incident history",
    links: ["kg-audit"],
  },
  {
    id: "kg-audit",
    label: "Audit Trail",
    type: "governance",
    domain: "Governance",
    owner: "Audit",
    evidence: "Immutable event ledger",
    links: [],
  },
  {
    id: "kg-design",
    label: "UI/UX",
    type: "artifact",
    domain: "Experience",
    owner: "Design",
    evidence: "Wireframes and design tokens",
    links: ["kg-implementation"],
  },
  {
    id: "kg-implementation",
    label: "Code",
    type: "artifact",
    domain: "Engineering",
    owner: "Engineering",
    evidence: "Source repository and diff",
    links: ["kg-tests", "kg-deployment"],
  },
  {
    id: "kg-approval",
    label: "Approval Gate",
    type: "governance",
    domain: "Governance",
    owner: "Approvals",
    evidence: "Human approval record with conditions",
    links: ["kg-audit", "kg-release"],
  },
];

export const AUTOMATION_TEMPLATES = [
  {
    id: "template-mobile-app",
    title: "Build a production-ready mobile app",
    description: "Move from validated product strategy to governed iOS and Android release with evidence at every gate.",
    stages: ["intent", "business", "architecture", "design", "implementation", "testing", "security", "deployment"],
    outcome: "A store-ready, observable mobile MVP with an owned roadmap and auditable release evidence.",
    phases: [
      {
        id: "strategy", title: "Strategy & discovery", owner: "Product", gate: "Problem and MVP approved",
        tasks: ["Define the user, core problem, and measurable success criteria.", "Map direct competitors and articulate the product's differentiated value.", "Prioritise the smallest testable MVP and move non-essential ideas to the roadmap."],
        deliverables: ["Product brief", "Competitive landscape", "MVP scorecard"],
      },
      {
        id: "planning", title: "Architecture & delivery plan", owner: "Product + Engineering", gate: "Architecture decision approved",
        tasks: ["Choose native Swift/Kotlin or cross-platform Flutter/React Native against product constraints.", "Decide supported platforms, OS baseline, offline behaviour, and device capabilities.", "Select managed/no-code services or custom frontend, backend, database, and API components."],
        deliverables: ["Architecture decision record", "Delivery plan", "Risk register"],
      },
      {
        id: "design", title: "Product & experience design", owner: "Design", gate: "Usability baseline accepted",
        tasks: ["Map primary, alternate, empty, error, onboarding, and recovery user flows.", "Create accessible wireframes with clear information hierarchy and platform conventions.", "Validate an interactive prototype with representative users before implementation."],
        deliverables: ["User-flow map", "Wireframes", "Tested prototype", "Design tokens"],
      },
      {
        id: "development", title: "Governed development", owner: "Engineering", gate: "Build and review evidence complete",
        tasks: ["Provision reproducible IDE, repository, branching, CI, signing, and environment configuration.", "Implement secure APIs, identity, data storage, migrations, notifications, and synchronisation.", "Build the mobile interface, local state, accessibility, device integrations, and telemetry."],
        deliverables: ["Source repositories", "API contract", "Signed builds", "Technical documentation"],
      },
      {
        id: "quality", title: "Quality, security & readiness", owner: "Quality + Security", gate: "Release candidate approved",
        tasks: ["Automate unit, integration, contract, UI, and end-to-end acceptance tests.", "Verify supported devices, screen sizes, OS versions, permissions, and degraded-network behaviour.", "Assess privacy, secrets, dependencies, data handling, accessibility, performance, and load."],
        deliverables: ["Test report", "Device matrix", "Security assessment", "Release candidate"],
      },
      {
        id: "release", title: "Release & continuous improvement", owner: "Release + Product", gate: "Store release authorised",
        tasks: ["Prepare compliant listings, privacy disclosures, search metadata, screenshots, and support details.", "Distribute staged builds through TestFlight and Play testing tracks before store submission.", "Monitor crashes, performance, analytics, reviews, and support signals; triage them into the roadmap."],
        deliverables: ["Store listing pack", "Release evidence", "Monitoring dashboard", "Maintenance plan"],
      },
    ],
  },
  {
    id: "template-banking-backend",
    title: "Generate banking backend",
    description: "Produce APIs, data models, controls, and release artifacts for a regulated backend.",
    stages: ["intent", "business", "architecture", "implementation", "testing", "security", "compliance-approval", "deployment"],
  },
  {
    id: "template-staging-deploy",
    title: "Deploy to staging",
    description: "Run the approval, packaging, deployment, and verification workflow for staging.",
    stages: ["intent", "requirements-approval", "deployment", "monitoring"],
  },
  {
    id: "template-security-scan",
    title: "Run security scan",
    description: "Execute dependency, container, and secret scanning with audit output.",
    stages: ["intent", "testing", "security", "compliance-approval"],
  },
];

export const INTEGRATIONS = [
  {
    id: "github",
    name: "GitHub",
    kind: "source control",
    status: "connected",
    purpose: "repositories and pull requests",
  },
  {
    id: "gitlab",
    name: "GitLab",
    kind: "source control",
    status: "available",
    purpose: "mirrored repositories",
  },
  {
    id: "jira",
    name: "Jira",
    kind: "workflow",
    status: "available",
    purpose: "issue tracking and approvals",
  },
  {
    id: "slack",
    name: "Slack",
    kind: "notifications",
    status: "connected",
    purpose: "review alerts and approvals",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    kind: "runtime",
    status: "connected",
    purpose: "deployment targets and rollouts",
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    kind: "storage",
    status: "connected",
    purpose: "solution and audit storage",
  },
  {
    id: "grafana",
    name: "Grafana",
    kind: "observability",
    status: "available",
    purpose: "dashboards and service health",
  },
];

export const DEVELOPER_SURFACES = [
  { name: "REST APIs", description: "Solution, workflow, audit, and artifact APIs." },
  { name: "GraphQL", description: "Cross-surface query model for the enterprise graph." },
  { name: "Webhooks", description: "Event delivery for approvals, deployments, and incidents." },
  { name: "CLI", description: "Command-line access for automation and local workflows." },
  { name: "SDKs", description: "TypeScript, Python, Java, and Go integration kits." },
  { name: "Policy Packs", description: "Reusable governance rules for solution execution." },
];
