export const WORKFLOW_STAGES = [
  {
    id: "intent",
    label: "Intent Analysis",
    kind: "automation",
    service: "Solution Orchestrator Engine",
    api: "POST /api/solutions/intent",
    storage: "solution_requests",
    audit: "solution.intent.raised",
    ui: "Solution Studio",
    output: "Intent brief",
  },
  {
    id: "business",
    label: "Business Analysis",
    kind: "automation",
    service: "Business AI",
    api: "POST /api/solutions/analysis",
    storage: "solution_artifacts",
    audit: "solution.analysis.generated",
    ui: "Solution Studio",
    output: "Business requirements",
  },
  {
    id: "requirements-approval",
    label: "Requirements Approval",
    kind: "human",
    service: "Human Review & Governance Engine",
    api: "POST /api/approvals/requirements",
    storage: "approvals",
    audit: "solution.requirements.approved",
    ui: "Governance",
    output: "Approved requirements",
  },
  {
    id: "architecture",
    label: "Architecture Design",
    kind: "automation",
    service: "Architecture Studio",
    api: "POST /api/architecture/design",
    storage: "architecture_artifacts",
    audit: "solution.architecture.generated",
    ui: "Architecture Studio",
    output: "C4 and topology pack",
  },
  {
    id: "architecture-approval",
    label: "Architecture Approval",
    kind: "human",
    service: "Human Review & Governance Engine",
    api: "POST /api/approvals/architecture",
    storage: "approvals",
    audit: "solution.architecture.approved",
    ui: "Governance",
    output: "Approved architecture",
  },
  {
    id: "design",
    label: "UI/UX Design",
    kind: "automation",
    service: "UI/UX Studio",
    api: "POST /api/design/generate",
    storage: "design_artifacts",
    audit: "solution.design.generated",
    ui: "UI/UX Studio",
    output: "Wireframes and UI kit",
  },
  {
    id: "implementation",
    label: "Implementation",
    kind: "automation",
    service: "Code Studio",
    api: "POST /api/code/generate",
    storage: "source_repositories",
    audit: "solution.code.generated",
    ui: "Code Studio",
    output: "Scaffold and services",
  },
  {
    id: "testing",
    label: "Testing",
    kind: "automation",
    service: "Test Studio",
    api: "POST /api/tests/run",
    storage: "test_reports",
    audit: "solution.tests.executed",
    ui: "Test Studio",
    output: "Test report",
  },
  {
    id: "security",
    label: "Security Review",
    kind: "automation",
    service: "Security Studio",
    api: "POST /api/security/review",
    storage: "security_reports",
    audit: "solution.security.reviewed",
    ui: "Security Studio",
    output: "Security review",
  },
  {
    id: "compliance-approval",
    label: "Compliance Approval",
    kind: "human",
    service: "Human Review & Governance Engine",
    api: "POST /api/approvals/compliance",
    storage: "approvals",
    audit: "solution.compliance.approved",
    ui: "Governance",
    output: "Compliance signoff",
  },
  {
    id: "deployment",
    label: "Deployment",
    kind: "automation",
    service: "Deployment Studio",
    api: "POST /api/deployments/create",
    storage: "deployment_manifests",
    audit: "solution.deployment.prepared",
    ui: "Deployment Studio",
    output: "Deployment bundle",
  },
  {
    id: "monitoring",
    label: "Monitoring",
    kind: "automation",
    service: "Operations Center",
    api: "GET /api/observability/runtime",
    storage: "runtime_events",
    audit: "solution.monitoring.enabled",
    ui: "Operations Center",
    output: "Monitoring view",
  },
];

export const SERVICE_CATALOG = [
  {
    id: "orchestrator",
    title: "Solution Orchestrator Engine",
    kind: "workflow",
    service: "NovaCodePro Orchestrator",
    api: "/api/solutions",
    storage: "solution_requests",
    audit: "solution.request.created",
    ui: "Solution Studio",
    description: "Coordinates intake, planning, generation, review, and release for every request.",
  },
  {
    id: "business-ai",
    title: "Business AI",
    kind: "analysis",
    service: "Business AI Service",
    api: "/api/analysis/business",
    storage: "business_artifacts",
    audit: "solution.analysis.generated",
    ui: "Solution Studio",
    description: "Converts user intent into scope, requirements, assumptions, and delivery estimates.",
  },
  {
    id: "architecture-studio",
    title: "Architecture Studio",
    kind: "design",
    service: "Architecture Service",
    api: "/api/architecture",
    storage: "architecture_artifacts",
    audit: "solution.architecture.generated",
    ui: "Architecture Studio",
    description: "Produces context diagrams, C4 models, DDD boundaries, and topology exports.",
  },
  {
    id: "uiux-studio",
    title: "UI/UX Studio",
    kind: "design",
    service: "Design Service",
    api: "/api/design",
    storage: "design_artifacts",
    audit: "solution.design.generated",
    ui: "UI/UX Studio",
    description: "Generates journeys, wireframes, components, accessibility notes, and layouts.",
  },
  {
    id: "code-studio",
    title: "Code Studio",
    kind: "engineering",
    service: "Implementation Service",
    api: "/api/code",
    storage: "source_repositories",
    audit: "solution.code.generated",
    ui: "Code Studio",
    description: "Scaffolds repositories, services, frontends, mobile apps, and configuration.",
  },
  {
    id: "data-studio",
    title: "Data Studio",
    kind: "engineering",
    service: "Data Platform Service",
    api: "/api/data",
    storage: "data_catalog",
    audit: "solution.data.generated",
    ui: "Data Studio",
    description: "Creates schemas, migrations, lineage, ETL, backups, and warehouse plans.",
  },
  {
    id: "api-studio",
    title: "API Studio",
    kind: "engineering",
    service: "Integration API Service",
    api: "/api/apis",
    storage: "api_specs",
    audit: "solution.api.generated",
    ui: "API Studio",
    description: "Delivers REST, GraphQL, gRPC, OpenAPI, SDKs, mocks, and contract tests.",
  },
  {
    id: "test-studio",
    title: "Test Studio",
    kind: "governance",
    service: "Verification Service",
    api: "/api/tests",
    storage: "test_reports",
    audit: "solution.tests.executed",
    ui: "Test Studio",
    description: "Runs unit, integration, UI, load, accessibility, and security test suites.",
  },
  {
    id: "security-studio",
    title: "Security Studio",
    kind: "governance",
    service: "Security Review Service",
    api: "/api/security",
    storage: "security_reports",
    audit: "solution.security.reviewed",
    ui: "Security Studio",
    description: "Performs static analysis, dependency scans, secret detection, and threat review.",
  },
  {
    id: "documentation-studio",
    title: "Documentation Studio",
    kind: "support",
    service: "Documentation Service",
    api: "/api/docs",
    storage: "documentation_repository",
    audit: "solution.documentation.generated",
    ui: "Documentation Studio",
    description: "Keeps user guides, runbooks, API docs, and release notes synchronized.",
  },
  {
    id: "deployment-studio",
    title: "Deployment Studio",
    kind: "operations",
    service: "Release & Deployment Service",
    api: "/api/deployments",
    storage: "deployment_manifests",
    audit: "solution.deployment.prepared",
    ui: "Deployment Studio",
    description: "Produces Docker, Kubernetes, Terraform, CI/CD, staging, rollback, and publish plans.",
  },
  {
    id: "operations-center",
    title: "Operations Center",
    kind: "operations",
    service: "Runtime Observability Service",
    api: "/api/observability",
    storage: "runtime_events",
    audit: "solution.monitoring.enabled",
    ui: "Operations Center",
    description: "Shows logs, metrics, traces, alerts, health, and incidents in one live console.",
  },
  {
    id: "audit-service",
    title: "Audit Service",
    kind: "governance",
    service: "Audit Trail Service",
    api: "/api/audit",
    storage: "audit_trail",
    audit: "audit.event.appended",
    ui: "Trust Center",
    description: "Persists every action with actor, timestamp, service, evidence, and decision state.",
  },
];

export const AGENT_MARKETPLACE = [
  {
    id: "banking-agent",
    title: "Banking Solution Agent",
    category: "finance",
    service: "Domain Solution Service",
    api: "/api/agents/banking",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Governed accelerators for banking workflows, payments, ledgers, and compliance.",
  },
  {
    id: "healthcare-agent",
    title: "Healthcare Compliance Agent",
    category: "health",
    service: "Domain Solution Service",
    api: "/api/agents/healthcare",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Industry rules for patient records, compliance, and care journey workflows.",
  },
  {
    id: "ride-hailing-agent",
    title: "Ride-Hailing Agent",
    category: "mobility",
    service: "Domain Solution Service",
    api: "/api/agents/ride-hailing",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Solution packs for rider, driver, dispatch, maps, payments, and operations.",
  },
  {
    id: "erp-agent",
    title: "ERP Agent",
    category: "business",
    service: "Domain Solution Service",
    api: "/api/agents/erp",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Business process automation for procurement, inventory, finance, and approvals.",
  },
  {
    id: "crm-agent",
    title: "CRM Agent",
    category: "customer",
    service: "Domain Solution Service",
    api: "/api/agents/crm",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Customer engagement, support, sales pipeline, and analytics accelerators.",
  },
  {
    id: "government-agent",
    title: "Government Services Agent",
    category: "public-sector",
    service: "Domain Solution Service",
    api: "/api/agents/government",
    storage: "agent_catalog",
    audit: "agent.installed",
    ui: "Marketplace",
    summary: "Citizen services, identity, case management, and policy-driven delivery workflows.",
  },
];

export const SOLUTION_TEMPLATES = [
  {
    id: "ride-hailing",
    title: "Ride-hailing platform",
    request: "Build a ride-hailing platform for Melbourne.",
    surfaces: ["Rider app", "Driver app", "Operations dashboard", "Admin portal"],
    domain: "mobility",
  },
  {
    id: "hospital",
    title: "Hospital management system",
    request: "Build a hospital management system.",
    surfaces: ["Patient portal", "Staff portal", "Clinical workflows", "Admin console"],
    domain: "healthcare",
  },
  {
    id: "money-transfer",
    title: "Money transfer platform",
    request: "Create a money transfer platform between Australia and DR Congo.",
    surfaces: ["Consumer app", "Operations console", "Compliance portal", "Partner API"],
    domain: "finance",
  },
  {
    id: "ecommerce",
    title: "E-commerce platform",
    request: "Build an enterprise e-commerce platform for regional retail.",
    surfaces: ["Storefront", "Admin portal", "Inventory console", "Fulfillment tools"],
    domain: "commerce",
  },
  {
    id: "erp",
    title: "ERP platform",
    request: "Build an ERP platform for a distributed enterprise.",
    surfaces: ["Planning console", "Finance portal", "HR workspace", "Reporting tools"],
    domain: "business",
  },
];

export const PLATFORM_CENTERS = [
  {
    title: "Trust Center",
    summary: "Identities, receipts, certificates, releases, and audit evidence in one governed surface.",
    chips: ["Identities", "Receipts", "Certificates", "Evidence", "Audit"],
  },
  {
    title: "Release Center",
    summary: "Validate, build, test, sign, publish, deploy, observe, and roll back from a single flow.",
    chips: ["Validate", "Build", "Tests", "Sign", "Publish"],
  },
  {
    title: "Observability Center",
    summary: "Latency, error rate, regions, logs, metrics, traces, and alerts remain visible together.",
    chips: ["CPU", "Memory", "Latency", "Logs", "Tracing"],
  },
  {
    title: "Data Center",
    summary: "SQL, NoSQL, storage, analytics, streaming, backups, and replication with shared context.",
    chips: ["SQL", "Warehouse", "Streaming", "Backups", "Replication"],
  },
  {
    title: "Security Center",
    summary: "Zero Trust, NovaID, RBAC, MFA, certificates, secrets, threats, and policies are governed here.",
    chips: ["Zero Trust", "RBAC", "MFA", "Secrets", "Policies"],
  },
  {
    title: "Executive Center",
    summary: "Revenue, MRR, ARR, growth, trust score, and regional performance drive leadership review.",
    chips: ["Revenue", "MRR", "ARR", "Trust", "Forecast"],
  },
];

export const WORKFLOW_SEQUENCE = [
  "intent",
  "business",
  "requirements-approval",
  "architecture",
  "architecture-approval",
  "design",
  "implementation",
  "testing",
  "security",
  "compliance-approval",
  "deployment",
  "monitoring",
];

export const WORKFLOW_LABELS = Object.fromEntries(
  WORKFLOW_STAGES.map((stage) => [stage.id, stage.label]),
);

