#!/usr/bin/env bash
set -euo pipefail

echo "Running NovaTech Controlled Pilot tests..."
python3 -m pytest tests/private_dev -q
python3 -m pytest tests/internal_qa -q
python3 -m pytest tests/test_controlled_pilot_environment.py tests/test_controlled_pilot_access_control.py tests/test_controlled_pilot_device_control.py tests/test_controlled_pilot_payment_safety.py tests/test_controlled_pilot_novaride_e2e.py tests/test_controlled_pilot_novapay_consumer_e2e.py tests/test_controlled_pilot_novapay_agent_e2e.py tests/test_controlled_pilot_novapay_merchant_e2e.py tests/test_controlled_pilot_novapay_business_e2e.py tests/test_controlled_pilot_novaid_e2e.py tests/test_controlled_pilot_button_registry.py tests/test_controlled_pilot_apk_validation.py tests/test_controlled_pilot_apk_distribution.py tests/test_controlled_pilot_api_contracts.py tests/test_controlled_pilot_server_validation.py tests/test_controlled_pilot_release_guard.py tests/test_controlled_pilot_monitoring_support.py tests/test_controlled_pilot_incident_response.py tests/test_controlled_pilot_cash_procedure.py tests/test_controlled_pilot_exit_criteria.py tests/test_controlled_pilot_observability.py tests/test_controlled_pilot_android_icons.py -q
python3 -m pytest -m "controlled_pilot or pilot_smoke or pilot_mobile or pilot_api or pilot_release_guard or pilot_access_control or pilot_device_control or pilot_payment_guard or simulated_payment or no_live_charge" tests/controlled_pilot -q
echo "Controlled Pilot validation complete."
