"""DDL for the persistent runtime control store."""

from __future__ import annotations

SCHEMA_NAME = "platform_runtime"

DDL = """
CREATE SCHEMA IF NOT EXISTS platform_runtime;

CREATE TABLE IF NOT EXISTS platform_runtime.products (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    module_checksum TEXT NOT NULL,
    configuration_checksum TEXT NOT NULL,
    infrastructure_checksum TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.runtime_instances (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    deployment_id TEXT NOT NULL,
    worker_state TEXT NOT NULL,
    health_state TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.activations (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    approval_id TEXT NOT NULL,
    current_state TEXT NOT NULL,
    previous_state TEXT NOT NULL,
    module_checksum TEXT NOT NULL,
    configuration_checksum TEXT NOT NULL,
    infrastructure_checksum TEXT NOT NULL,
    route_plan_checksum TEXT NOT NULL,
    migration_checksum TEXT NOT NULL,
    details TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.activation_transitions (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    from_state TEXT NOT NULL,
    to_state TEXT NOT NULL,
    reason TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.approvals (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    approval_type TEXT NOT NULL,
    approver_id TEXT NOT NULL,
    approver_roles TEXT NOT NULL,
    evidence_refs TEXT NOT NULL,
    decision TEXT NOT NULL,
    expires_at TEXT,
    conditions TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.worker_instances (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    worker_name TEXT NOT NULL,
    replica_id TEXT NOT NULL,
    state TEXT NOT NULL,
    queue TEXT NOT NULL,
    image TEXT NOT NULL,
    image_digest TEXT NOT NULL,
    heartbeat_at TEXT NOT NULL,
    started_at TEXT NOT NULL,
    processed_count INTEGER NOT NULL,
    failure_count INTEGER NOT NULL,
    retry_count INTEGER NOT NULL,
    dead_letter_count INTEGER NOT NULL,
    current_job_id TEXT,
    consumer_lag INTEGER NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.infrastructure_plans (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    requirement_id TEXT NOT NULL,
    adapter TEXT NOT NULL,
    actions TEXT NOT NULL,
    destructive INTEGER NOT NULL,
    state TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.infrastructure_resources (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    requirement_id TEXT NOT NULL,
    adapter TEXT NOT NULL,
    resource_name TEXT NOT NULL,
    resource_kind TEXT NOT NULL,
    real_mode TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.deployment_revisions (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    deployment_id TEXT NOT NULL,
    image TEXT NOT NULL,
    image_digest TEXT NOT NULL,
    route_plan_checksum TEXT NOT NULL,
    configuration_checksum TEXT NOT NULL,
    migration_checksum TEXT NOT NULL,
    infrastructure_checksum TEXT NOT NULL,
    approval_id TEXT NOT NULL,
    previous_deployment_id TEXT NOT NULL,
    deployed_at TEXT NOT NULL,
    verified_at TEXT NOT NULL,
    promoted_at TEXT NOT NULL,
    rolled_back_at TEXT NOT NULL,
    current_state TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.verification_runs (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    verification_id TEXT NOT NULL,
    deployment_id TEXT NOT NULL,
    checks TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.verification_results (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    verification_id TEXT NOT NULL,
    probe_id TEXT NOT NULL,
    category TEXT NOT NULL,
    result_status TEXT NOT NULL,
    evidence TEXT NOT NULL,
    error_code TEXT,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS platform_runtime.rollback_runs (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    rollback_id TEXT NOT NULL,
    deployment_id TEXT NOT NULL,
    previous_deployment_id TEXT NOT NULL,
    reason TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.evidence_records (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    evidence_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    object_uri TEXT NOT NULL,
    signature TEXT NOT NULL,
    recorded_at TEXT NOT NULL,
    metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_runtime.idempotency_records (
    id TEXT PRIMARY KEY,
    product_code TEXT NOT NULL,
    product_version TEXT NOT NULL,
    environment TEXT NOT NULL,
    region TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    status TEXT NOT NULL,
    version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    checksum TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    response_hash TEXT NOT NULL,
    expires_at TEXT,
    metadata TEXT NOT NULL
);
"""
