"""Read-only explanation surfaces for AfriTech evidence."""
from afritech.explainability.projection_enrichment import (
    ENFORCEMENT_AUTHORITY as PROJECTION_ENRICHMENT_ENFORCEMENT_AUTHORITY,
    ENRICHMENT_STATUS,
    PROJECTION_DISPLAY_ONLY,
    RECEIPT_MUTATION,
    RUNTIME_AUTHORITY as PROJECTION_ENRICHMENT_RUNTIME_AUTHORITY,
    VALIDATION_AUTHORITY as PROJECTION_ENRICHMENT_VALIDATION_AUTHORITY,
    ProjectionSummary,
    enrich_explanation_payload,
    enrich_governance_references,
)

EXPLANATION_STATUS = "READ_ONLY_EXPLANATION"
RUNTIME_AUTHORITY = False
ENFORCEMENT_AUTHORITY = False
VALIDATION_AUTHORITY = False
PROJECTION_DISPLAY_ONLY = True

__all__ = [
    "ENFORCEMENT_AUTHORITY",
    "EXPLANATION_STATUS",
    "PROJECTION_DISPLAY_ONLY",
    "RUNTIME_AUTHORITY",
    "VALIDATION_AUTHORITY",
    "ENRICHMENT_STATUS",
    "PROJECTION_DISPLAY_ONLY",
    "RECEIPT_MUTATION",
    "PROJECTION_ENRICHMENT_RUNTIME_AUTHORITY",
    "PROJECTION_ENRICHMENT_ENFORCEMENT_AUTHORITY",
    "PROJECTION_ENRICHMENT_VALIDATION_AUTHORITY",
    "ProjectionSummary",
    "enrich_explanation_payload",
    "enrich_governance_references",
]
