from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


ENTERPRISE_STRUCTURE = [
    "Corporate Governance",
    "Enterprise Governance Plane",
    "Enterprise Platform Plane",
    "Knowledge & Intelligence Plane",
    "Enterprise AI Plane",
    "Digital Twin & Resilience Plane",
    "Business Product Plane",
    "Enterprise Operations Plane",
    "Shared Enterprise Services",
    "Infrastructure & Regional Runtime",
]

GOVERNANCE_CHAIN = [
    "Identity",
    "Authentication",
    "Role and Attribute Resolution",
    "Policy Evaluation",
    "Risk Evaluation",
    "Compliance Evaluation",
    "Authority and Approval",
    "Execution",
    "Evidence and Audit",
]

CANONICAL_STATE_VIEWS = [
    "Observed State",
    "Desired State",
    "Predicted State",
    "Simulated State",
    "Approved State",
    "Recovered State",
]

AUTHORITY_LEVELS = [
    {"level": 0, "name": "Observe"},
    {"level": 1, "name": "Recommend"},
    {"level": 2, "name": "Prepare"},
    {"level": 3, "name": "Execute with Approval"},
    {"level": 4, "name": "Execute under Pre-Approval"},
    {"level": 5, "name": "Emergency Containment"},
]

DATA_CLASSIFICATIONS = ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED", "REGULATED", "SECRET"]

PRODUCT_PORTFOLIO = {
    "Enterprise Platform": ["NovaCodePro", "NovaAI", "NovaCloud", "NovaID", "NovaTrust", "NovaData", "NovaConnect", "NovaGateway"],
    "Financial Services": ["NovaPay", "NovaWallet", "NovaBank", "NovaInvoice", "NovaInsurance", "NovaMarkets", "NovaTreasury"],
    "Mobility & Logistics": ["NovaRide", "NovaLogistics", "NovaFleet", "NovaDelivery", "NovaDispatch", "NovaTransport"],
    "Commerce": ["NovaCommerce", "NovaStore", "NovaMarketplace", "NovaMerchant", "NovaPOS", "NovaInventory"],
    "Enterprise Business": ["NovaERP", "NovaCRM", "NovaHR", "NovaProjects", "NovaAssets", "NovaProcurement", "NovaWorkspace"],
    "Healthcare": ["NovaHealth", "NovaCare", "NovaClinic", "NovaHospital", "NovaPharmacy", "NovaTeleHealth"],
    "Education": ["NovaEducation", "NovaLearn", "NovaCampus", "NovaClassroom", "NovaAssessment", "NovaLibrary"],
    "Agriculture": ["NovaAgriculture", "NovaFarm", "NovaLivestock", "NovaCrop", "NovaSupply", "NovaAgriMarket"],
    "Government": ["NovaGov", "NovaCitizen", "NovaPermit", "NovaLicensing", "NovaTax", "NovaJustice"],
    "Energy & Utilities": ["NovaEnergy", "NovaUtilities", "NovaWater", "NovaPower", "NovaGrid", "NovaMeter"],
    "Real Estate": ["NovaRealEstate", "NovaProperty", "NovaRent", "NovaFacilities", "NovaConstruction", "NovaMaintenance"],
    "Food & Hospitality": ["NovaFood", "NovaRestaurant", "NovaKitchen", "NovaReservations", "NovaHospitality", "NovaDelivery"],
    "Analytics & Intelligence": ["NovaAnalytics", "NovaInsights", "NovaReports", "NovaBI", "NovaForecast", "NovaIntelligence"],
    "Security": ["NovaSecure", "NovaSOC", "NovaAudit", "NovaCompliance", "NovaRisk"],
}

CAPABILITY_DOMAINS = [
    "Strategy, Governance & Leadership",
    "Enterprise Architecture & Transformation",
    "Product & Portfolio Management",
    "Customer, Partner & Market Management",
    "Software Engineering & Digital Delivery",
    "Platform, Cloud & Infrastructure",
    "Data, Knowledge & Intelligence",
    "Artificial Intelligence & Agent Operations",
    "Identity, Security, Trust & Privacy",
    "Risk, Compliance, Legal & Audit",
    "Enterprise Operations & Service Management",
    "Resilience, Continuity & Recovery",
    "Finance, Commercial & Procurement",
    "People, Workforce & Organization",
    "Sales, Marketing & Communications",
    "Ecosystem, Integration & Developer Enablement",
    "Industry Product Capabilities",
    "Enterprise Measurement & Improvement",
]

PORTAL_STATES = ["Loading", "Ready", "Empty", "Degraded", "Unavailable", "Forbidden", "Error", "Recovery"]


def build_nera_manifest() -> dict[str, Any]:
    platform_domains = [
        "NovaWorkspace",
        "NovaProjects",
        "NovaAgents",
        "NovaExecution",
        "NovaReviews",
        "NovaApprovals",
        "NovaGovernance",
        "NovaKnowledge",
        "NovaAutomation",
        "NovaTesting",
        "NovaDeployments",
        "NovaObservability",
        "NovaReporting",
        "NovaAdministration",
    ]
    enterprise_capabilities = [
        "NovaTrust",
        "NovaID",
        "NovaSecure",
        "NovaPolicy",
        "NovaRisk",
        "NovaCompliance",
        "NovaAudit",
        "NovaEvents",
        "NovaWorkflow",
        "NovaAutomation",
        "NovaKnowledge",
        "NovaGraph",
        "NovaMemory",
        "NovaInsights",
        "NovaDecision",
        "NovaDigitalTwin",
    ]
    return {
        "id": "nera",
        "name": "NovaTech Enterprise Reference Architecture",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Technology Officer",
        "generated_at": _now(),
        "layers": [
            {
                "id": "corporate-governance",
                "name": "Corporate Governance",
                "purpose": "Board, executive, and enterprise accountability.",
                "stable": True,
            },
            {
                "id": "enterprise-governance",
                "name": "Enterprise Governance",
                "purpose": "Identity, security, policy, risk, compliance, and audit.",
                "stable": True,
            },
            {
                "id": "enterprise-platform",
                "name": "Enterprise Platform",
                "purpose": "Reusable capabilities shared across all products.",
                "stable": True,
            },
            {
                "id": "knowledge-intelligence",
                "name": "Knowledge & Intelligence Plane",
                "purpose": "Memory, reasoning, digital twin, and decision intelligence.",
                "stable": True,
            },
            {
                "id": "enterprise-ai",
                "name": "Enterprise AI Plane",
                "purpose": "Governed model, agent, reasoning, memory, and tool runtime.",
                "stable": True,
            },
            {
                "id": "digital-twin-resilience",
                "name": "Digital Twin & Resilience Plane",
                "purpose": "Enterprise state, simulations, recovery planning, recovery execution, validation, replay, evidence, and scoring.",
                "stable": True,
            },
            {
                "id": "business-products",
                "name": "Business Product Plane",
                "purpose": "Customer-facing and partner-facing products.",
                "stable": False,
            },
            {
                "id": "enterprise-operations",
                "name": "Enterprise Operations Plane",
                "purpose": "Run-the-business operations and support functions.",
                "stable": False,
            },
            {
                "id": "shared-enterprise-services",
                "name": "Shared Enterprise Services",
                "purpose": "Common services consumed by every product and platform domain.",
                "stable": True,
            },
            {
                "id": "infrastructure",
                "name": "Infrastructure",
                "purpose": "Cloud, networking, runtime, storage, and edge services.",
                "stable": True,
            },
        ],
        "mission": [
            "Govern consistently",
            "Build reusable platforms",
            "Accumulate enterprise knowledge",
            "Deliver modular products",
            "Operate reliably",
            "Recover safely",
            "Improve continuously",
        ],
        "canonical_enterprise_structure": ENTERPRISE_STRUCTURE,
        "enterprise_platform": {
            "domains": platform_domains,
            "shared_capabilities": enterprise_capabilities,
            "default_ai_layer": "NovaAI",
        },
        "knowledge_and_intelligence": {
            "services": [
                "NovaKnowledge",
                "NovaGraph",
                "NovaMemory",
                "NovaDecision",
                "NovaInsights",
                "NovaDigitalTwin",
                "NovaSearch",
                "NovaLearning",
                "NovaReasoning",
            ],
            "graph_relationships": [
                "Project -> Requirement",
                "Requirement -> ADR",
                "ADR -> Architecture",
                "Architecture -> Approval",
                "Approval -> Deployment",
                "Deployment -> Evidence",
            ],
        },
        "digital_twin_resilience": {
            "platform": "NovaEROS",
            "state_views": CANONICAL_STATE_VIEWS,
            "runtime_services": [
                "Enterprise Observation Engine",
                "Twin Registry",
                "Twin Identity Service",
                "Twin State Engine",
                "Twin Relationship Graph",
                "Twin Snapshot Service",
                "Simulation Engine",
                "Decision Engine",
                "Recovery Planner",
                "Recovery Orchestrator",
                "Validation Engine",
                "Evidence Ledger",
                "Replay Engine",
                "Learning Engine",
                "Resilience Analytics",
                "Executive Resilience Center",
            ],
        },
        "governance_chain": GOVERNANCE_CHAIN,
        "authority_levels": AUTHORITY_LEVELS,
        "data_classifications": DATA_CLASSIFICATIONS,
        "product_portfolio": PRODUCT_PORTFOLIO,
        "default_product_examples": ["NovaRide", "NovaPay", "NovaHealth", "NovaCommerce", "NovaGov", "NovaERP"],
        "principles": [
            "Products are replaceable",
            "Platforms are reusable",
            "Governance and knowledge are persistent",
            "Governance is persistent",
            "Platform is reusable",
            "Knowledge is cumulative",
            "Products are modular",
            "Operations are observable",
            "AI is governed",
            "Events are the integration backbone",
            "Digital twin is the enterprise intelligence layer",
            "Recovery is validated through evidence",
        ],
        "portal_experience": [
            "Enterprise Map",
            "Capability Map",
            "Product Portfolio",
            "Platform Domains",
            "Governance Chain",
            "Knowledge Graph Explorer",
            "Digital Twin Explorer",
            "Simulation Workspace",
            "Recovery Workspace",
            "Architecture Review Workspace",
            "Policy and Risk Views",
            "Evidence Explorer",
            "Standards Catalog",
            "Technology Radar",
            "Regional Topology",
            "Executive Resilience Dashboard",
        ],
        "portal_states": PORTAL_STATES,
        "completion_criteria": [
            "Architecture manifest is versioned and published",
            "Every architecture model is queryable through NovaCodePro",
            "Digital Twins represent critical products and services",
            "Simulations produce traceable impact analysis",
            "Recovery plans are governed and executable",
            "Recovery outcomes are automatically validated",
            "Evidence is immutable and replayable",
            "AI agents operate under identity and policy",
            "Executive dashboards show live resilience and risk",
        ],
        "notes": [
            "Knowledge Graph is a projection, not the source of truth.",
            "Products may be replaced without changing the enterprise platform.",
            "Governance, identity, and audit remain stable across products and regions.",
            "NEDTM is the canonical digital twin model; NDTM remains a compatibility alias.",
        ],
    }


def build_enterprise_capability_model() -> dict[str, Any]:
    return {
        "id": "necm",
        "name": "NovaTech Enterprise Capability Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Operating Officer",
        "generated_at": _now(),
        "mission": "Define what NovaTech must be able to do, independent of products, departments, technologies, vendors, or applications.",
        "hierarchy_levels": [
            "NovaTech Enterprise",
            "Enterprise Capability Domain",
            "Business or Platform Capability",
            "Capability Component",
            "Operational Function",
            "Control, metric, API, workflow, or implementation",
        ],
        "capability_domains": CAPABILITY_DOMAINS,
        "capabilities": CAPABILITY_DOMAINS,
        "capability_groups": [
            {"name": "Customer", "items": ["Customer, Partner & Market Management", "Industry Product Capabilities", "Product & Portfolio Management"]},
            {"name": "Platform", "items": ["Software Engineering & Digital Delivery", "Platform, Cloud & Infrastructure", "Data, Knowledge & Intelligence", "Artificial Intelligence & Agent Operations"]},
            {"name": "Governance", "items": ["Strategy, Governance & Leadership", "Identity, Security, Trust & Privacy", "Risk, Compliance, Legal & Audit"]},
            {"name": "Resilience", "items": ["Enterprise Operations & Service Management", "Resilience, Continuity & Recovery", "Enterprise Measurement & Improvement"]},
        ],
        "criticality_model": ["TIER_0", "TIER_1", "TIER_2", "TIER_3", "TIER_4"],
        "maturity_model": ["Absent", "Initial", "Repeatable", "Managed", "Optimized", "Autonomous and Governed"],
        "health_model": ["HEALTHY", "DEGRADED", "AT_RISK", "UNAVAILABLE", "RECOVERING", "SUSPENDED", "RETIRED"],
        "metadata_standard": [
            "capability_id",
            "name",
            "description",
            "domain",
            "owner",
            "executive_owner",
            "criticality",
            "maturity",
            "target_maturity",
            "products_supported",
            "platform_services",
            "APIs",
            "events",
            "policies",
            "risks",
            "controls",
            "KPIs",
            "RTO",
            "RPO",
            "Digital_Twins",
            "dependencies",
            "evidence",
            "lifecycle_status",
        ],
        "dependency_relationships": ["DEPENDS_ON", "ENABLED_BY", "IMPLEMENTED_BY", "OPERATED_BY", "GOVERNED_BY", "EXPOSED_BY", "EMITS", "REPRESENTED_BY", "PROTECTED_BY", "MEASURED_BY"],
        "product_to_capability_examples": {
            "NovaRide": ["Industry Product Capabilities", "Identity, Security, Trust & Privacy", "Enterprise Operations & Service Management"],
            "NovaPay": ["Industry Product Capabilities", "Risk, Compliance, Legal & Audit", "Resilience, Continuity & Recovery"],
            "NovaHealth": ["Industry Product Capabilities", "Data, Knowledge & Intelligence", "Risk, Compliance, Legal & Audit"],
            "NovaCommerce": ["Industry Product Capabilities", "Ecosystem, Integration & Developer Enablement", "Enterprise Measurement & Improvement"],
        },
        "digital_twin_integration": "Every critical capability should have a Capability Twin containing health, dependencies, risks, controls, KPIs, RTO, RPO, incidents, recovery plans, evidence, and improvement roadmap.",
        "ai_integration": "AI agents are mapped to capabilities with allowed actions, authority level, data scope, required approvals, evidence requirements, and human owner.",
        "apis": [
            "GET /v1/novacodepro/capabilities",
            "GET /v1/novacodepro/capabilities/{id}",
            "GET /v1/novacodepro/capabilities/{id}/dependencies",
            "GET /v1/novacodepro/capabilities/{id}/twin",
            "POST /v1/novacodepro/capabilities/{id}/assess",
            "POST /v1/novacodepro/capabilities/{id}/simulate",
        ],
        "events": [
            "capability.created",
            "capability.updated",
            "capability.owner_assigned",
            "capability.maturity_assessed",
            "capability.health_changed",
            "capability.degraded",
            "capability.recovered",
            "capability.risk_changed",
            "capability.retired",
        ],
        "portal_views": [
            "Enterprise Capability Map",
            "Capability Hierarchy Explorer",
            "Capability Heatmap",
            "Capability Maturity Map",
            "Capability Health Map",
            "Capability Dependency Graph",
            "Capability Digital Twin",
            "Capability Investment Portfolio",
            "Capability Improvement Roadmap",
        ],
    }


def build_enterprise_operating_model() -> dict[str, Any]:
    return {
        "id": "neom",
        "name": "NovaTech Enterprise Operating Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Operating Officer",
        "generated_at": _now(),
        "principles": [
            "Customer-Centric",
            "Platform-First",
            "Governance by Design",
            "AI-Augmented Workforce",
            "Evidence-Based Decisions",
            "Automation Before Manual Work",
            "Secure by Default",
            "Resilience by Design",
            "Continuous Learning",
            "Global, Multi-Tenant, Multi-Region",
        ],
        "operating_domains": [
            "Leadership & Governance",
            "Strategy & Planning",
            "Portfolio & Product Management",
            "Enterprise Delivery",
            "Operations & Service Management",
            "Customer Operations",
            "Financial Operations",
            "Risk & Compliance",
            "Security Operations",
            "AI Workforce Operations",
            "Knowledge Operations",
            "Digital Twin Operations",
            "Enterprise Resilience",
            "Performance Management",
            "Continuous Improvement",
        ],
        "people": ["Executives", "Product Managers", "Engineers", "Analysts", "Operators", "Legal", "Compliance"],
        "roles": ["Owner", "Steward", "Approver", "Operator", "Agent", "Reviewer"],
        "departments": ["Engineering", "Product", "Operations", "Finance", "HR", "Legal", "Security", "Data"],
        "workspaces": ["NovaCodePro", "Customer Platforms", "Partner Platforms", "Enterprise Analytics"],
        "processes": ["Intake", "Review", "Approval", "Execution", "Monitoring", "Learning"],
        "delivery_model": ["Describe", "Understand", "Architect", "Plan", "Assign", "Develop", "Review", "Test", "Govern", "Approve", "Release", "Deploy", "Verify", "Learn"],
        "decision_model": ["Observe", "Analyze", "Recommend", "Assess Risk", "Approve", "Execute", "Verify", "Record"],
        "governance_model": GOVERNANCE_CHAIN,
        "digital_twin_model": ["Observe", "Model", "Compare", "Predict", "Simulate", "Recover", "Validate"],
        "resilience_model": ["Observe", "Detect", "Predict", "Simulate", "Plan", "Approve", "Recover", "Validate", "Learn"],
        "operational_states": ["Planned", "Ready", "Active", "Degraded", "Recovering", "Suspended", "Retired"],
        "ai_agents": ["Architect Agent", "Developer Agent", "QA Agent", "Security Agent", "Compliance Agent", "Risk Agent", "Recovery Agent", "Support Agent", "SRE Agent"],
    }


def build_enterprise_meta_model() -> dict[str, Any]:
    return {
        "id": "nekm",
        "name": "NovaTech Enterprise Knowledge Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Data & AI Officer",
        "generated_at": _now(),
        "mission": "Transform governed data, evidence, experience, decisions, architecture, policies, and operational activity into trusted reusable enterprise knowledge.",
        "knowledge_planes": [
            "Semantic Foundation Plane",
            "Knowledge Capture Plane",
            "Evidence and Provenance Plane",
            "Enterprise Knowledge Graph Plane",
            "Enterprise Memory Plane",
            "Decision Intelligence Plane",
            "Search and Discovery Plane",
            "Learning and Improvement Plane",
            "AI Knowledge Plane",
            "Digital Twin Knowledge Plane",
            "Governance and Compliance Plane",
            "Knowledge Operations Plane",
        ],
        "entities": [
            "Knowledge Item",
            "Fact",
            "Claim",
            "Inference",
            "Prediction",
            "Recommendation",
            "Decision",
            "Evidence",
            "Source",
            "Citation",
            "Organization",
            "Product",
            "Service",
            "Capability",
            "Application",
            "API",
            "Dataset",
            "Event",
            "Project",
            "Requirement",
            "Architecture",
            "ADR",
            "Policy",
            "Risk",
            "Control",
            "Approval",
            "Deployment",
            "Incident",
            "Recovery",
            "Lesson Learned",
            "Known Error",
            "AI Agent",
            "AI Model",
            "Digital Twin",
            "Region",
        ],
        "knowledge_types": ["Descriptive", "Procedural", "Decision", "Experiential", "Regulatory", "Analytical", "AI"],
        "lifecycle": ["Proposed", "Captured", "Classified", "Validated", "Reviewed", "Approved", "Published", "Used", "Measured", "Updated", "Superseded", "Archived or Deleted"],
        "authority_levels": [
            "Unverified",
            "Informational",
            "Reviewed",
            "Approved",
            "Controlled",
            "Constitutional",
        ],
        "relationships": [
            "OWNS",
            "DEPENDS_ON",
            "ENABLES",
            "IMPLEMENTS",
            "USES",
            "PRODUCES",
            "CONSUMES",
            "GOVERNS",
            "REQUIRES",
            "VIOLATES",
            "MITIGATES",
            "APPROVES",
            "SUPERSEDES",
            "AFFECTS",
            "RECOVERS",
            "REPRESENTS",
            "OBSERVES",
            "PREDICTS",
            "SIMULATES",
            "LEARNED_FROM",
            "SUPPORTED_BY",
            "CONTRADICTS",
            "DERIVED_FROM",
            "VALIDATED_BY",
        ],
        "memory_classes": [
            "Working Memory",
            "Session Memory",
            "Workspace Memory",
            "Project Memory",
            "Product Memory",
            "Domain Memory",
            "Operational Memory",
            "Governance Memory",
            "Incident Memory",
            "Recovery Memory",
            "Decision Memory",
            "Architecture Memory",
            "AI Memory",
            "Historical Enterprise Memory",
        ],
        "search_modes": ["Exact", "Keyword", "Semantic", "Graph", "Faceted", "Temporal", "Evidence", "Decision", "Policy", "Architecture", "Incident", "Natural-Language"],
        "apis": [
            "GET /v1/knowledge/items",
            "POST /v1/knowledge/items",
            "POST /v1/knowledge/items/{id}/validate",
            "GET /v1/knowledge/search",
            "POST /v1/knowledge/query",
            "GET /v1/knowledge/graph/nodes",
            "POST /v1/knowledge/graph/traverse",
            "GET /v1/knowledge/decisions",
            "POST /v1/knowledge/memory/promote",
        ],
        "events": [
            "knowledge.captured",
            "knowledge.validated",
            "knowledge.approved",
            "knowledge.published",
            "knowledge.stale",
            "knowledge.disputed",
            "knowledge.superseded",
            "decision.approved",
            "lesson.implemented",
            "memory.promoted",
            "graph.relationship.inferred",
        ],
        "portal_views": [
            "Enterprise Knowledge Center",
            "Knowledge Graph Explorer",
            "Enterprise Memory",
            "Decision Register",
            "ADR Library",
            "Policy Library",
            "Runbook Center",
            "Lessons Learned",
            "AI Knowledge Registry",
            "Knowledge Conflict Workbench",
            "Semantic Search",
            "Evidence Explorer",
        ],
    }


def build_enterprise_data_architecture() -> dict[str, Any]:
    return {
        "id": "nedm",
        "name": "NovaTech Enterprise Data Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Data & AI Officer",
        "generated_at": _now(),
        "mission": "Define how information is identified, owned, classified, created, validated, stored, exchanged, protected, retained, analyzed, represented, and retired.",
        "data_planes": [
            "Master Data Plane",
            "Reference Data Plane",
            "Transactional Data Plane",
            "Operational Data Plane",
            "Event and Temporal Data Plane",
            "Analytical Data Plane",
            "Knowledge and Semantic Data Plane",
            "Digital Twin Data Plane",
            "AI and Agent Data Plane",
            "Governance and Evidence Data Plane",
            "Security and Privacy Data Plane",
            "External and Partner Data Plane",
        ],
        "layers": ["Operational Stores", "Event Fabric", "Data Lakehouse", "Knowledge Graph", "Analytics Platform", "Digital Twin", "Enterprise AI"],
        "flow": [
            "Operational Stores -> NovaEvents / Event Store",
            "NovaEvents / Event Store -> Integration Layer",
            "NovaEvents / Event Store -> Data Lakehouse",
            "NovaEvents / Event Store -> Evidence Ledger",
            "Data Lakehouse -> Knowledge Graph",
            "Knowledge Graph -> NovaDigitalTwin",
            "NovaDigitalTwin -> NovaAI Reasoning",
        ],
        "core_entities": [
            "Enterprise",
            "Organization",
            "Identity",
            "Capability",
            "Product",
            "Service",
            "Application",
            "API",
            "Event",
            "Workflow",
            "Project",
            "Customer",
            "Partner",
            "Transaction",
            "Dataset",
            "Risk",
            "Control",
            "Incident",
            "Recovery Plan",
            "Evidence",
            "Audit Record",
            "Knowledge Item",
            "Digital Twin",
            "Simulation",
            "AI Agent",
            "AI Model",
        ],
        "classifications": DATA_CLASSIFICATIONS,
        "quality_dimensions": ["Accuracy", "Completeness", "Consistency", "Validity", "Uniqueness", "Timeliness", "Freshness", "Integrity", "Traceability", "Conformity"],
        "lifecycle_states": ["PROPOSED", "REGISTERED", "ACTIVE", "DEGRADED", "QUARANTINED", "ARCHIVED", "LEGAL_HOLD", "DEPRECATED", "RETIRED", "DELETED"],
        "canonical_data_types": ["Identifier", "Timestamp", "Money", "Currency", "Percentage", "Country", "Region", "Email", "Phone", "Address", "Status", "Classification", "Risk Score", "Confidence Score", "Version", "Hash", "Signature"],
        "data_trust_ratings": ["TRUSTED", "CONDITIONALLY_TRUSTED", "UNVERIFIED", "STALE", "CONFLICTED", "REJECTED"],
        "apis": [
            "GET /v1/data/catalog",
            "POST /v1/data/catalog",
            "GET /v1/data/glossary",
            "GET /v1/data/contracts",
            "POST /v1/data/contracts/{id}/validate",
            "GET /v1/data/quality/{dataset_id}",
            "GET /v1/data/lineage/{asset_id}",
            "POST /v1/data/access/evaluate",
            "GET /v1/data/twins",
        ],
        "events": [
            "dataset.registered",
            "dataset.classified",
            "dataset.quality_changed",
            "dataset.quarantined",
            "schema.published",
            "data_contract.approved",
            "data_access.denied",
            "retention.expired",
            "data_twin.observed",
            "data_twin.recovered",
        ],
        "portal_views": [
            "Enterprise Data Catalog",
            "Business Glossary",
            "Data Domain Map",
            "Data Ownership Map",
            "Data Classification Explorer",
            "Data Contract Registry",
            "Schema Registry",
            "Data Lineage Explorer",
            "Data Quality Dashboard",
            "Data Twin Explorer",
            "Data Resilience Dashboard",
            "AI Data Governance",
        ],
        "notes": [
            "Operational databases remain the source of record.",
            "Knowledge graphs are projections.",
            "Digital twin is the current enterprise state.",
            "Graph and twin state must be rebuildable from authoritative sources.",
        ],
    }


def build_enterprise_resilience_model() -> dict[str, Any]:
    return {
        "id": "nerm",
        "name": "NovaTech Enterprise Resilience Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Operating Officer",
        "generated_at": _now(),
        "mission": "Define how NovaTech anticipates disruption, protects critical capabilities, maintains acceptable service, responds, recovers safely, validates outcomes, preserves evidence, learns, and adapts.",
        "resilience_domains": [
            "Strategic Resilience",
            "Governance Resilience",
            "Business Capability Resilience",
            "Product Resilience",
            "Customer Experience Resilience",
            "Operational Resilience",
            "Technology Resilience",
            "Cloud and Infrastructure Resilience",
            "Data Resilience",
            "Cyber Resilience",
            "Identity Resilience",
            "AI and Agent Resilience",
            "Financial Resilience",
            "Workforce Resilience",
            "Supply-Chain and Partner Resilience",
            "Regional and Sovereign Resilience",
            "Regulatory and Legal Resilience",
            "Knowledge Resilience",
            "Communication and Reputation Resilience",
            "Resilience Assurance and Improvement",
        ],
        "objects": [
            "Capability Resilience Profile",
            "Important Business Service",
            "Business Impact Analysis",
            "Scenario",
            "Failure Mode",
            "Dependency",
            "Resilience Objective",
            "Continuity Plan",
            "Recovery Plan",
            "Exercise",
            "Incident",
            "Recovery Execution",
            "Validation",
            "Evidence",
            "Residual Risk",
            "Lesson",
            "Corrective Action",
            "Certification",
        ],
        "criticality_model": ["TIER_0", "TIER_1", "TIER_2", "TIER_3", "TIER_4"],
        "objectives": ["RTO", "RPO", "MTD", "MBCO", "WRT", "Recovery capacity objective"],
        "incident_severities": ["SEV0", "SEV1", "SEV2", "SEV3", "SEV4"],
        "resilience_strategies": ["Avoidance", "Prevention", "Absorption", "Containment", "Continuity", "Recovery", "Adaptation"],
        "validation_layers": ["Infrastructure", "Application", "Dependency", "Data", "Security and compliance", "Business outcome"],
        "scorecards": [
            "Capability Readiness",
            "Recovery Readiness",
            "Digital Twin Fidelity",
            "Dependency Confidence",
            "Exercise Coverage",
            "Security Resilience",
            "Data Recoverability",
            "Workforce Readiness",
            "Supplier Readiness",
            "Policy Compliance",
            "Residual Risk",
        ],
        "lifecycle": ["Criticality and Impact Review", "Architecture Review", "Risk and Compliance Review", "Strategy and Plan Design", "Approval", "Implementation", "Exercise", "Certification", "Continuous Monitoring", "Improvement or Retirement"],
        "runtime": "EROS operationalizes NERM continuously through observation, simulation, orchestration, validation, evidence, learning, and optimization.",
        "apis": [
            "GET /v1/resilience/capabilities",
            "GET /v1/resilience/services",
            "GET /v1/resilience/objectives",
            "GET /v1/resilience/scenarios",
            "GET /v1/resilience/plans",
            "GET /v1/resilience/metrics",
            "GET /v1/resilience/score",
            "POST /v1/resilience/assess",
            "POST /v1/resilience/simulate",
            "POST /v1/resilience/recover",
            "POST /v1/resilience/validate",
            "POST /v1/resilience/certify",
        ],
        "events": [
            "resilience.profile.created",
            "resilience.objective.approved",
            "resilience.exercise.completed",
            "resilience.gap.detected",
            "resilience.plan.approved",
            "resilience.incident.declared",
            "resilience.recovery.completed",
            "resilience.validation.passed",
            "resilience.residual_risk.accepted",
            "resilience.lesson.recorded",
            "resilience.score.changed",
        ],
        "portal_views": [
            "Enterprise Resilience Dashboard",
            "Critical Capability Register",
            "Important Business Services",
            "Business Impact Analysis Workspace",
            "Scenario Library",
            "Dependency Explorer",
            "Continuity Plan Center",
            "Recovery Plan Center",
            "Exercise Center",
            "Simulation Center",
            "Incident Command Center",
            "Validation Center",
            "Residual Risk Register",
            "Lessons and Improvement Center",
            "Resilience Certification Center",
            "Executive Crisis Dashboard",
        ],
    }


def build_enterprise_plane_model() -> dict[str, Any]:
    return {
        "id": "nepm",
        "name": "NovaTech Enterprise Plane Model",
        "version": "2.0",
        "generated_at": _now(),
        "sequence": [
            "Governance Plane",
            "Intelligence Plane",
            "Execution Plane",
            "Product Plane",
            "Infrastructure Plane",
        ],
        "planes": [
            {
                "id": "governance-plane",
                "name": "Governance Plane",
                "owner": "NovaGovernance",
                "responsibilities": [
                    "Trust",
                    "Identity",
                    "Security",
                    "Policy",
                    "Risk",
                    "Compliance",
                    "Audit",
                    "Legal",
                    "Privacy",
                    "Authority",
                ],
                "platforms": [
                    "NovaTrust",
                    "NovaID",
                    "NovaSecure",
                    "NovaPolicy",
                    "NovaRisk",
                    "NovaCompliance",
                    "NovaAudit",
                    "NovaLegal",
                    "NovaPrivacy",
                    "NovaAuthority",
                ],
            },
            {
                "id": "intelligence-plane",
                "name": "Intelligence Plane",
                "owner": "NovaIntelligence",
                "responsibilities": [
                    "Knowledge",
                    "Graph",
                    "Memory",
                    "Decision",
                    "Insights",
                    "Learning",
                    "Digital Twin",
                    "Search",
                    "Reasoning",
                ],
                "platforms": [
                    "NovaKnowledge",
                    "NovaGraph",
                    "NovaMemory",
                    "NovaDecision",
                    "NovaInsights",
                    "NovaLearning",
                    "NovaDigitalTwin",
                    "NovaSearch",
                    "NovaReasoning",
                ],
            },
            {
                "id": "execution-plane",
                "name": "Execution Plane",
                "owner": "NovaExecution",
                "responsibilities": [
                    "Workspace",
                    "Projects",
                    "Reviews",
                    "Approvals",
                    "Workflow",
                    "Automation",
                    "Deployments",
                    "Testing",
                    "Operations",
                ],
                "platforms": [
                    "NovaCodePro",
                    "NovaWorkspace",
                    "NovaProjects",
                    "NovaReviews",
                    "NovaApprovals",
                    "NovaWorkflow",
                    "NovaAutomation",
                    "NovaDeployments",
                    "NovaTesting",
                    "NovaOperations",
                ],
            },
            {
                "id": "product-plane",
                "name": "Product Plane",
                "owner": "NovaProducts",
                "responsibilities": [
                    "Customer value",
                    "Modular product evolution",
                    "Market differentiation",
                    "Industry-specific solutions",
                ],
                "platforms": [
                    "NovaRide",
                    "NovaPay",
                    "NovaHealth",
                    "NovaCommerce",
                    "NovaEducation",
                    "NovaAgriculture",
                    "NovaEnergy",
                    "NovaInsurance",
                    "NovaRealEstate",
                    "NovaFood",
                    "NovaGov",
                    "NovaERP",
                    "NovaCRM",
                    "NovaAnalytics",
                    "NovaLogistics",
                ],
            },
            {
                "id": "infrastructure-plane",
                "name": "Infrastructure Plane",
                "owner": "NovaInfrastructure",
                "responsibilities": [
                    "Cloud",
                    "Gateway",
                    "Events",
                    "API",
                    "Storage",
                    "Network",
                    "Regions",
                    "Observability",
                    "Monitoring",
                    "Recovery",
                ],
                "platforms": [
                    "NovaCloud",
                    "NovaGateway",
                    "NovaEvents",
                    "NovaAPI",
                    "NovaStorage",
                    "NovaNetwork",
                    "NovaRegions",
                    "NovaObservability",
                    "NovaMonitoring",
                    "NovaRecovery",
                ],
            },
        ],
        "interaction_model": [
            "Governance -> Intelligence",
            "Intelligence -> Execution",
            "Execution -> Products",
            "Products -> Infrastructure",
            "Infrastructure -> Governance evidence and telemetry",
        ],
        "enterprise_state_models": [
            "Observed State",
            "Desired State",
            "Predicted State",
            "Simulated State",
            "Approved State",
            "Recovered State",
        ],
        "ai_workforce": [
            "Executive Agents",
            "Architecture Agents",
            "Engineering Agents",
            "QA Agents",
            "Security Agents",
            "Compliance Agents",
            "Finance Agents",
            "Support Agents",
            "Operations Agents",
            "Research Agents",
        ],
        "reasoning_domains": [
            "Strategic Reasoning",
            "Operational Reasoning",
            "Financial Reasoning",
            "Security Reasoning",
            "Compliance Reasoning",
            "Architecture Reasoning",
            "Risk Reasoning",
            "Recovery Reasoning",
            "Executive Reasoning",
        ],
    }


def build_enterprise_technology_model() -> dict[str, Any]:
    return {
        "id": "netm",
        "name": "NovaTech Enterprise Technology Model",
        "version": "2.0",
        "status": "Enterprise Reference Architecture Standard",
        "owner": "Chief Technology Officer",
        "generated_at": _now(),
        "mission": "Define the technology standards, platforms, engineering principles, runtime architecture, infrastructure, integration patterns, and operational technology required to implement NERA.",
        "technology_domains": [
            "Enterprise Platform",
            "Application Platform",
            "AI Platform",
            "Identity Platform",
            "Integration Platform",
            "Data Platform",
            "Knowledge Platform",
            "Digital Twin Platform",
            "Cloud Platform",
            "Infrastructure Platform",
            "Security Platform",
            "Developer Platform",
            "DevSecOps Platform",
            "Observability Platform",
            "Automation Platform",
            "Resilience Platform",
            "Emerging Technology Platform",
        ],
        "approved_stack": {
            "web": ["React", "TypeScript", "Next.js", "Vite", "Tailwind CSS", "Design System"],
            "mobile": ["React Native", "Flutter legacy support", "Native Android", "Native iOS"],
            "backend": ["Python", "FastAPI", "Go", "Java", "Node.js", "Rust"],
            "database": ["PostgreSQL", "Neo4j", "OpenSearch / Elasticsearch", "VictoriaMetrics / TimescaleDB", "S3-compatible object storage", "Redis", "pgvector / Milvus"],
            "infrastructure_as_code": ["Terraform", "Helm", "Kubernetes YAML", "GitOps", "Ansible"],
            "messaging": ["Kafka", "RabbitMQ", "Redis Streams", "Cloud Messaging"],
        },
        "runtime": ["API Runtime", "Event Runtime", "Workflow Runtime", "AI Runtime", "Digital Twin Runtime", "Search Runtime", "Policy Runtime", "Identity Runtime", "Automation Runtime"],
        "principles": ["Platform First", "API First", "Event First", "Cloud Native", "Secure by Design", "AI Native", "Multi Region", "Multi Tenant", "Everything Observable", "Everything Recoverable"],
        "technology_lifecycle": ["Proposed", "Review", "Approved", "Pilot", "Production", "Deprecated", "Retired"],
        "maturity_model": ["Experimental", "Prototype", "Pilot", "Production", "Enterprise Standard", "Strategic Technology"],
        "digital_twins": ["Database Twin", "API Twin", "Service Twin", "Cluster Twin", "Region Twin", "Network Twin", "AI Runtime Twin"],
        "apis": [
            "GET /v1/technology/catalog",
            "GET /v1/technology/standards",
            "GET /v1/technology/platforms",
            "GET /v1/technology/runtimes",
            "GET /v1/technology/health",
            "GET /v1/technology/twins",
            "POST /v1/technology/review",
            "POST /v1/technology/approve",
        ],
        "events": ["technology.registered", "technology.approved", "technology.deprecated", "runtime.started", "runtime.failed", "cluster.scaled", "deployment.completed", "technology.retired"],
        "portal_views": ["Technology Catalog", "Architecture Library", "Reference Architectures", "Runtime Explorer", "Platform Explorer", "Infrastructure Explorer", "Technology Standards", "ADR Library", "Dependency Graph", "Digital Twin Viewer", "Technology Health Dashboard"],
    }


def build_enterprise_governance_model() -> dict[str, Any]:
    return {
        "id": "negm",
        "name": "NovaTech Enterprise Governance Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Board of Directors",
        "executive_owner": "Chief Legal & Compliance Officer",
        "generated_at": _now(),
        "mission": "Define authority, decisions, policy, risk, compliance, audit, ethics, assurance, and accountability for human, software, service, product, and AI actions.",
        "governance_domains": [
            "Corporate Governance",
            "Executive Governance",
            "Enterprise Authority Management",
            "Policy Management",
            "Decision Governance",
            "Risk Management",
            "Compliance Management",
            "Legal and Regulatory Governance",
            "Privacy Governance",
            "Security Governance",
            "Financial Governance",
            "Product Governance",
            "Technology and Architecture Governance",
            "Data and Knowledge Governance",
            "AI and Agent Governance",
            "Operational Governance",
            "Resilience and Continuity Governance",
            "Audit and Assurance",
            "Ethics and Responsible Conduct",
            "Third-Party and Ecosystem Governance",
            "Governance Performance and Improvement",
        ],
        "governance_chain": GOVERNANCE_CHAIN,
        "authority_levels": AUTHORITY_LEVELS,
        "policy_hierarchy": ["Corporate Constitution", "Board Policies", "Enterprise Policies", "Domain Policies", "Standards", "Controls", "Procedures", "Runtime Rules"],
        "policy_decisions": ["PERMIT", "DENY", "PERMIT_WITH_CONDITIONS", "REQUIRE_APPROVAL", "REQUIRE_MFA", "REQUIRE_EVIDENCE", "REQUIRE_REVIEW", "QUARANTINE"],
        "risk_ratings": ["LOW", "MODERATE", "HIGH", "CRITICAL", "EXISTENTIAL"],
        "control_states": ["EFFECTIVE", "PARTIALLY_EFFECTIVE", "INEFFECTIVE", "NOT_TESTED", "NOT_APPLICABLE"],
        "incident_severities": ["SEV0", "SEV1", "SEV2", "SEV3", "SEV4"],
        "governance_twins": ["Policy Twin", "Risk Twin", "Control Twin", "Compliance Twin", "Audit Twin", "Authority Twin"],
        "apis": [
            "GET /v1/governance/policies",
            "POST /v1/governance/policies/{id}/evaluate",
            "GET /v1/governance/authorities",
            "POST /v1/governance/authorities/{id}/delegate",
            "GET /v1/governance/risks",
            "POST /v1/governance/risks/{id}/assess",
            "GET /v1/governance/controls",
            "POST /v1/governance/controls/{id}/test",
            "GET /v1/governance/approvals",
            "GET /v1/governance/evidence",
        ],
        "events": [
            "policy.approved",
            "policy.published",
            "policy.violated",
            "authority.granted",
            "authority.revoked",
            "risk.assessed",
            "control.failed",
            "approval.requested",
            "approval.granted",
            "audit.finding_created",
            "exception.expired",
            "emergency.authority_activated",
        ],
        "portal_views": [
            "Policy Authoring Workspace",
            "Authority Registry",
            "Risk Register",
            "Control Library",
            "Compliance Obligation Register",
            "Approval Workspace",
            "Exception Workspace",
            "Audit Workspace",
            "Evidence Explorer",
            "Certification Center",
            "Executive Governance Dashboard",
        ],
        "portal_states": PORTAL_STATES,
    }


def build_enterprise_ai_architecture() -> dict[str, Any]:
    return {
        "id": "neam",
        "name": "NovaTech Enterprise AI Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Data & AI Officer",
        "generated_at": _now(),
        "mission": "Define how NovaTech designs, approves, operates, evaluates, supervises, secures, and improves AI models, agents, reasoning services, tools, memory, and human-AI collaboration.",
        "operating_planes": [
            "AI Strategy and Portfolio Plane",
            "Model Platform Plane",
            "Agent Platform Plane",
            "Reasoning and Decision Plane",
            "Knowledge and Retrieval Plane",
            "Memory Plane",
            "Tool and Execution Plane",
            "Human-AI Collaboration Plane",
            "Governance and Authority Plane",
            "Safety and Security Plane",
            "Evaluation and Assurance Plane",
            "Observability and FinOps Plane",
            "Learning and Improvement Plane",
            "AI Experience Plane",
        ],
        "stack": [
            "Model Gateway",
            "Model Registry",
            "Model Router",
            "Inference Runtime",
            "Prompt Registry",
            "Agent Registry",
            "Agent Identity",
            "Agent Factory",
            "Agent Runtime",
            "Agent Orchestrator",
            "Agent Tool Gateway",
            "Agent Governance",
            "Agent Evaluation",
            "Agent Monitoring",
            "Agent Marketplace",
        ],
        "risk_classes": ["AI-0 Informational", "AI-1 Low Risk", "AI-2 Moderate Risk", "AI-3 High Risk", "AI-4 Critical"],
        "authority_levels": AUTHORITY_LEVELS,
        "ai_workforce": [
            "Executive Strategy Agent",
            "Enterprise Architect Agent",
            "Developer Agent",
            "QA Agent",
            "Security Agent",
            "Risk Agent",
            "Compliance Agent",
            "Legal Agent",
            "Data Agent",
            "Digital Twin Agent",
            "Recovery Agent",
            "Support Agent",
            "SRE Agent",
        ],
        "memory_scopes": ["Ephemeral Task Memory", "Session Memory", "User Memory", "Workspace Memory", "Project Memory", "Product Memory", "Agent Memory", "Domain Memory", "Enterprise Memory"],
        "evaluation_framework": ["Task quality", "Factuality", "Grounding", "Safety", "Policy compliance", "Tool correctness", "Reliability", "Latency", "Cost", "Fairness", "Robustness", "Business outcome"],
        "safety_controls": ["Input Guardrails", "Context Guardrails", "Reasoning Constraints", "Tool Guardrails", "Output Guardrails", "Execution Guardrails", "Monitoring and Intervention"],
        "governance": [
            "Authenticate through NovaID",
            "Authorize through NovaPolicy",
            "Assign authority per action",
            "Prevent agent self-approval",
            "Require human approval for high-risk actions",
            "Record evidence in NovaAudit",
            "Publish knowledge to NovaKnowledge",
            "Communicate through NovaEvents",
        ],
        "apis": [
            "GET /v1/ai/models",
            "POST /v1/ai/models/{id}/evaluate",
            "POST /v1/ai/models/{id}/approve",
            "GET /v1/ai/agents",
            "POST /v1/ai/agents/{id}/certify",
            "GET /v1/ai/prompts",
            "POST /v1/ai/tasks",
            "POST /v1/ai/reason",
            "POST /v1/ai/retrieve",
            "POST /v1/ai/kill-switch",
        ],
        "events": [
            "ai.model.registered",
            "ai.model.approved",
            "ai.agent.registered",
            "ai.agent.certified",
            "ai.agent.action_requested",
            "ai.agent.action_approved",
            "ai.tool.invoked",
            "ai.evaluation.completed",
            "ai.policy_violated",
            "ai.incident.detected",
            "ai.kill_switch.activated",
        ],
        "portal_views": [
            "AI Portfolio",
            "Model Registry",
            "Agent Registry",
            "Agent Builder",
            "Agent Teams",
            "Prompt Registry",
            "Tool Registry",
            "Knowledge Grounding",
            "Memory Center",
            "AI Evaluation Center",
            "AI Safety Center",
            "AI Governance Center",
            "AI Incident Center",
            "AI Cost Center",
            "Agent Digital Twins",
            "Human Review Queue",
        ],
    }


def build_enterprise_digital_twin_model() -> dict[str, Any]:
    return {
        "id": "nedtm",
        "aliases": ["ndtm"],
        "name": "NovaTech Enterprise Digital Twin Model",
        "version": "2.0",
        "status": "Enterprise Reference Standard",
        "owner": "Chief Data & AI Officer",
        "operational_owner": "Chief Operating Officer",
        "generated_at": _now(),
        "mission": "Maintain a continuously updated, evidence-backed, policy-governed representation of enterprise reality for understanding, prediction, simulation, recovery, optimization, and accountable decision-making.",
        "operating_planes": [
            "Twin Identity Plane",
            "Observation Plane",
            "State Plane",
            "Relationship and Dependency Plane",
            "Temporal and Snapshot Plane",
            "Prediction Plane",
            "Simulation Plane",
            "Decision and Approval Plane",
            "Execution and Recovery Plane",
            "Validation and Evidence Plane",
            "Learning and Optimization Plane",
            "Governance and Security Plane",
            "Experience and Command Plane",
        ],
        "state_views": CANONICAL_STATE_VIEWS,
        "twin_domains": [
            "Enterprise",
            "Corporate Governance",
            "Organization",
            "Business Unit",
            "Capability",
            "Product",
            "Customer Experience",
            "Process",
            "Service",
            "Application",
            "API",
            "Workflow",
            "Data",
            "Knowledge",
            "AI and Agent",
            "Security",
            "Risk and Compliance",
            "Financial",
            "Infrastructure",
            "Region",
            "Ecosystem and Partner",
        ],
        "identity_contract": [
            "twin_id",
            "represented_entity_id",
            "twin_type",
            "canonical_name",
            "owner",
            "tenant_id",
            "organization_id",
            "workspace_id",
            "product_id",
            "region",
            "jurisdiction",
            "environment",
            "classification",
            "criticality",
            "lifecycle_status",
            "schema_version",
        ],
        "relationship_model": [
            "DEPENDS_ON",
            "HOSTED_IN",
            "RUNS_ON",
            "CALLS",
            "PRODUCES",
            "CONSUMES",
            "OWNED_BY",
            "OPERATED_BY",
            "PROTECTED_BY",
            "GOVERNED_BY",
            "STORES_DATA_IN",
            "REPLICATES_TO",
            "FAILS_OVER_TO",
            "ENABLES",
            "IMPLEMENTS",
            "AFFECTS",
            "SERVES",
            "MONITORED_BY",
            "RECOVERED_BY",
            "APPROVED_BY",
        ],
        "lifecycle": ["Proposed", "Registered", "Connected", "Observed", "Validated", "Operational", "Degraded", "Recovering", "Recovered", "Suspended", "Retired"],
        "health_model": ["HEALTHY", "WATCH", "DEGRADED", "AT_RISK", "UNAVAILABLE", "SIMULATING", "RECOVERING", "QUARANTINED", "SUSPENDED", "RETIRED"],
        "criticality": ["TIER_0", "TIER_1", "TIER_2", "TIER_3", "TIER_4"],
        "simulation_types": [
            "Service failure",
            "Database failure",
            "Network partition",
            "Region outage",
            "Storage corruption",
            "Certificate expiry",
            "Capacity exhaustion",
            "Identity compromise",
            "Ransomware",
            "Supplier failure",
            "Financial stress",
            "Regulatory change",
            "Model degradation",
            "Agent misbehavior",
        ],
        "validation_layers": ["Infrastructure", "Application", "Dependency", "Business", "Security and Data", "Evidence"],
        "confidence_scores": ["Twin Fidelity Score", "Dependency Confidence Score", "Simulation Confidence Score", "Recovery Confidence Score", "Enterprise Resilience Score"],
        "capabilities": [
            "Twin registry",
            "Observation ingestion",
            "State reconciliation",
            "Relationship graph",
            "Snapshots",
            "Replay support",
            "Prediction",
            "Scenario simulation",
            "Cascading failure analysis",
            "Decision support",
            "Approved state transition",
            "Recovery planning",
            "Recovery execution",
            "Recovery validation",
            "Evidence capture",
            "RTO/RPO analysis",
            "Model drift detection",
            "Twin calibration",
        ],
        "apis": [
            "GET /v1/novacodepro/digital-twins",
            "POST /v1/novacodepro/digital-twins",
            "GET /v1/novacodepro/digital-twins/{id}/state",
            "GET /v1/novacodepro/digital-twins/{id}/relationships",
            "POST /v1/novacodepro/digital-twins/{id}/observe",
            "POST /v1/novacodepro/digital-twins/{id}/refresh",
            "POST /v1/novacodepro/digital-twins/{id}/predict",
            "POST /v1/novacodepro/digital-twins/{id}/simulate",
            "POST /v1/novacodepro/digital-twins/{id}/compare",
            "POST /v1/novacodepro/digital-twins/{id}/replay",
            "POST /v1/novacodepro/digital-twins/{id}/recovery-plans",
            "POST /v1/novacodepro/digital-twins/{id}/recover",
            "POST /v1/novacodepro/digital-twins/{id}/validate",
            "POST /v1/novacodepro/digital-twins/{id}/approve-state",
        ],
        "events": [
            "digital_twin.registered",
            "digital_twin.observed",
            "digital_twin.state_changed",
            "digital_twin.relationship_created",
            "digital_twin.snapshot_created",
            "digital_twin.predicted",
            "digital_twin.simulated",
            "digital_twin.approved",
            "digital_twin.recovery_planned",
            "digital_twin.recovered",
            "digital_twin.validation_failed",
            "digital_twin.evidence_created",
            "digital_twin.confidence_changed",
            "digital_twin.drift_detected",
        ],
        "portal_views": [
            "Enterprise Twin Center",
            "Twin Registry",
            "Enterprise Map",
            "Product Twin Explorer",
            "Capability Twin Explorer",
            "Service Twin Explorer",
            "Region Twin Explorer",
            "Data Twin Explorer",
            "Governance Twin Explorer",
            "AI Twin Explorer",
            "Relationship Graph",
            "Live State View",
            "Prediction Workspace",
            "Simulation Workspace",
            "Recovery Workspace",
            "Replay Timeline",
            "Evidence Explorer",
            "Resilience Scorecards",
            "Twin Quality Dashboard",
        ],
        "canonical_naming": {"official_acronym": "NEDTM", "compatibility_alias": "NDTM", "normalization": "NDTM -> NEDTM"},
    }


def build_enterprise_architecture_framework() -> dict[str, Any]:
    return {
        "id": "natech-framework",
        "name": "NovaTech AI-Native Enterprise Operating System Framework",
        "version": "2.0",
        "generated_at": _now(),
        "models": {
            "neaf": build_enterprise_plane_model(),
            "nera": build_nera_manifest(),
            "necm": build_enterprise_capability_model(),
            "neom": build_enterprise_operating_model(),
            "nedm": build_enterprise_data_architecture(),
            "nekm": build_enterprise_meta_model(),
            "netm": build_enterprise_technology_model(),
            "negm": build_enterprise_governance_model(),
            "nai": build_enterprise_ai_architecture(),
            "neam": build_enterprise_ai_architecture(),
            "nedtm": build_enterprise_digital_twin_model(),
            "ndtm": {**build_enterprise_digital_twin_model(), "id": "ndtm", "canonical_id": "nedtm", "alias_for": "nedtm"},
            "nerm": build_enterprise_resilience_model(),
        },
        "model_relationships": {
            "NERA": "Defines enterprise structure",
            "NECM": "Defines capabilities",
            "NEOM": "Defines people, AI, and processes",
            "NEDM": "Defines information and authoritative data",
            "NEKM": "Defines knowledge, meaning, decisions, and memory",
            "NETM": "Defines technologies and standards",
            "NEGM": "Defines authority and control",
            "NEAM": "Defines AI, models, agents, and human oversight",
            "NEDTM": "Defines enterprise state",
            "NDTM": "Compatibility alias for NEDTM",
            "NERM": "Defines resilience and recovery",
            "EROS": "Operationalizes resilience through Digital Twins, AI, governance, and NovaCodePro",
        },
    }


__all__ = [
    "build_nera_manifest",
    "build_enterprise_architecture_framework",
    "build_enterprise_plane_model",
    "build_enterprise_capability_model",
    "build_enterprise_operating_model",
    "build_enterprise_meta_model",
    "build_enterprise_data_architecture",
    "build_enterprise_resilience_model",
    "build_enterprise_technology_model",
    "build_enterprise_governance_model",
    "build_enterprise_ai_architecture",
    "build_enterprise_digital_twin_model",
]
