from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def build_nera_manifest() -> dict[str, Any]:
    platform_domains = [
        "NovaWorkspace",
        "NovaProjects",
        "NovaAgents",
        "NovaExecution",
        "NovaReviews",
        "NovaApprovals",
        "NovaGovernance",
        "NovaKnowledge",
        "NovaAutomation",
        "NovaTesting",
        "NovaDeployments",
        "NovaObservability",
        "NovaReporting",
        "NovaAdministration",
    ]
    enterprise_capabilities = [
        "NovaTrust",
        "NovaID",
        "NovaSecure",
        "NovaPolicy",
        "NovaRisk",
        "NovaCompliance",
        "NovaAudit",
        "NovaEvents",
        "NovaWorkflow",
        "NovaAutomation",
        "NovaKnowledge",
        "NovaGraph",
        "NovaMemory",
        "NovaInsights",
        "NovaDecision",
        "NovaDigitalTwin",
    ]
    return {
        "id": "nera",
        "name": "NovaTech Enterprise Reference Architecture",
        "version": "1.1",
        "generated_at": _now(),
        "layers": [
            {
                "id": "corporate-governance",
                "name": "Corporate Governance",
                "purpose": "Board, executive, and enterprise accountability.",
                "stable": True,
            },
            {
                "id": "enterprise-governance",
                "name": "Enterprise Governance",
                "purpose": "Identity, security, policy, risk, compliance, and audit.",
                "stable": True,
            },
            {
                "id": "enterprise-platform",
                "name": "Enterprise Platform",
                "purpose": "Reusable capabilities shared across all products.",
                "stable": True,
            },
            {
                "id": "knowledge-intelligence",
                "name": "Knowledge & Intelligence Layer",
                "purpose": "Memory, reasoning, digital twin, and decision intelligence.",
                "stable": True,
            },
            {
                "id": "business-products",
                "name": "Business Products",
                "purpose": "Customer-facing and partner-facing products.",
                "stable": False,
            },
            {
                "id": "enterprise-operations",
                "name": "Enterprise Operations",
                "purpose": "Run-the-business operations and support functions.",
                "stable": False,
            },
            {
                "id": "shared-enterprise-services",
                "name": "Shared Enterprise Services",
                "purpose": "Common services consumed by every product and platform domain.",
                "stable": True,
            },
            {
                "id": "infrastructure",
                "name": "Infrastructure",
                "purpose": "Cloud, networking, runtime, storage, and edge services.",
                "stable": True,
            },
        ],
        "enterprise_platform": {
            "domains": platform_domains,
            "shared_capabilities": enterprise_capabilities,
            "default_ai_layer": "NovaAI",
        },
        "knowledge_and_intelligence": {
            "services": [
                "NovaKnowledge",
                "NovaGraph",
                "NovaMemory",
                "NovaDecision",
                "NovaInsights",
                "NovaDigitalTwin",
                "NovaSearch",
                "NovaLearning",
            ],
            "graph_relationships": [
                "Project -> Requirement",
                "Requirement -> ADR",
                "ADR -> Architecture",
                "Architecture -> Approval",
                "Approval -> Deployment",
                "Deployment -> Evidence",
            ],
        },
        "governance_chain": ["NovaPolicy", "NovaRisk", "NovaCompliance", "NovaAudit"],
        "default_product_examples": ["NovaRide", "NovaPay", "NovaHealth", "NovaCommerce"],
        "principles": [
            "Governance is persistent",
            "Platform is reusable",
            "Knowledge is cumulative",
            "Products are modular",
            "Operations are observable",
            "AI is governed",
            "Events are the integration backbone",
            "Digital twin is the enterprise intelligence layer",
        ],
        "notes": [
            "Knowledge Graph is a projection, not the source of truth.",
            "Products may be replaced without changing the enterprise platform.",
            "Governance, identity, and audit remain stable across products and regions.",
        ],
    }


def build_enterprise_capability_model() -> dict[str, Any]:
    return {
        "id": "necm",
        "name": "NovaTech Enterprise Capability Model",
        "version": "1.0",
        "generated_at": _now(),
        "capabilities": [
            "Identity",
            "Security",
            "Payments",
            "Mobility",
            "Commerce",
            "Healthcare",
            "Education",
            "Agriculture",
            "Workflow",
            "Approvals",
            "AI",
            "Knowledge",
            "Analytics",
            "Observability",
            "Compliance",
            "Risk",
            "Audit",
        ],
        "capability_groups": [
            {"name": "Customer", "items": ["Payments", "Mobility", "Commerce", "Healthcare", "Education", "Agriculture"]},
            {"name": "Platform", "items": ["Identity", "Security", "Workflow", "AI", "Knowledge", "Analytics"]},
            {"name": "Governance", "items": ["Approvals", "Compliance", "Risk", "Audit", "Observability"]},
        ],
        "product_to_capability_examples": {
            "NovaRide": ["Mobility", "Identity", "Approvals", "Observability"],
            "NovaPay": ["Payments", "Security", "Risk", "Audit"],
            "NovaHealth": ["Healthcare", "Compliance", "Identity"],
            "NovaCommerce": ["Commerce", "Workflow", "Analytics"],
        },
    }


def build_enterprise_operating_model() -> dict[str, Any]:
    return {
        "id": "neom",
        "name": "NovaTech Enterprise Operating Model",
        "version": "1.0",
        "generated_at": _now(),
        "people": ["Executives", "Product Managers", "Engineers", "Analysts", "Operators", "Legal", "Compliance"],
        "roles": ["Owner", "Steward", "Approver", "Operator", "Agent", "Reviewer"],
        "departments": ["Engineering", "Product", "Operations", "Finance", "HR", "Legal", "Security", "Data"],
        "workspaces": ["NovaCodePro", "Customer Platforms", "Partner Platforms", "Enterprise Analytics"],
        "processes": ["Intake", "Review", "Approval", "Execution", "Monitoring", "Learning"],
        "ai_agents": ["Architect Agent", "Developer Agent", "QA Agent", "Security Agent", "Compliance Agent"],
    }


def build_enterprise_meta_model() -> dict[str, Any]:
    return {
        "id": "enterprise-meta-model",
        "name": "NovaTech Enterprise Meta Model",
        "version": "1.0",
        "generated_at": _now(),
        "entities": [
            "Organization",
            "Business Unit",
            "Department",
            "Team",
            "Workspace",
            "Project",
            "Product",
            "Service",
            "Capability",
            "Policy",
            "Risk",
            "Approval",
            "Deployment",
            "Event",
            "Evidence",
            "Knowledge",
            "Agent",
            "User",
            "Identity",
            "Digital Twin",
        ],
        "relationships": [
            "Organization owns Product",
            "Product consumes Capability",
            "Workspace contains Project",
            "Project produces Event",
            "Event updates Digital Twin",
            "Approval governs Deployment",
            "Evidence supports Approval",
            "Knowledge links to Policy",
        ],
    }


def build_enterprise_data_architecture() -> dict[str, Any]:
    return {
        "id": "nedm",
        "name": "NovaTech Enterprise Data Model",
        "version": "1.0",
        "generated_at": _now(),
        "layers": [
            "Operational Database",
            "Event Store",
            "Knowledge Graph",
            "Enterprise Memory",
            "Digital Twin",
        ],
        "flow": [
            "Operational Database -> Event Store",
            "Event Store -> Knowledge Graph",
            "Knowledge Graph -> Enterprise Memory",
            "Enterprise Memory -> Digital Twin",
            "Digital Twin -> AI Reasoning",
        ],
        "notes": [
            "Operational databases remain the source of record.",
            "Knowledge graphs are projections.",
            "Digital twin is the current enterprise state.",
        ],
    }


def build_enterprise_resilience_model() -> dict[str, Any]:
    return {
        "id": "nerm",
        "name": "NovaTech Enterprise Resilience Model",
        "version": "1.0",
        "generated_at": _now(),
        "objects": [
            "Dependency",
            "Recovery Plan",
            "Recovery Workflow",
            "Recovery Test",
            "Resilience Score",
            "Recovery Evidence",
            "Blast Radius",
            "Recovery Confidence",
            "RTO",
            "RPO",
        ],
        "scorecards": [
            "Availability",
            "Recovery Confidence",
            "Dependency Confidence",
            "Simulation Confidence",
            "Control Effectiveness",
            "Evidence Completeness",
        ],
        "lifecycle": ["Observe", "Assess", "Simulate", "Approve", "Execute", "Verify", "Learn"],
    }


def build_enterprise_plane_model() -> dict[str, Any]:
    return {
        "id": "nepm",
        "name": "NovaTech Enterprise Plane Model",
        "version": "1.0",
        "generated_at": _now(),
        "sequence": [
            "Governance Plane",
            "Intelligence Plane",
            "Execution Plane",
            "Product Plane",
            "Infrastructure Plane",
        ],
        "planes": [
            {
                "id": "governance-plane",
                "name": "Governance Plane",
                "owner": "NovaGovernance",
                "responsibilities": [
                    "Trust",
                    "Identity",
                    "Security",
                    "Policy",
                    "Risk",
                    "Compliance",
                    "Audit",
                    "Legal",
                    "Privacy",
                    "Authority",
                ],
                "platforms": [
                    "NovaTrust",
                    "NovaID",
                    "NovaSecure",
                    "NovaPolicy",
                    "NovaRisk",
                    "NovaCompliance",
                    "NovaAudit",
                    "NovaLegal",
                    "NovaPrivacy",
                    "NovaAuthority",
                ],
            },
            {
                "id": "intelligence-plane",
                "name": "Intelligence Plane",
                "owner": "NovaIntelligence",
                "responsibilities": [
                    "Knowledge",
                    "Graph",
                    "Memory",
                    "Decision",
                    "Insights",
                    "Learning",
                    "Digital Twin",
                    "Search",
                    "Reasoning",
                ],
                "platforms": [
                    "NovaKnowledge",
                    "NovaGraph",
                    "NovaMemory",
                    "NovaDecision",
                    "NovaInsights",
                    "NovaLearning",
                    "NovaDigitalTwin",
                    "NovaSearch",
                    "NovaReasoning",
                ],
            },
            {
                "id": "execution-plane",
                "name": "Execution Plane",
                "owner": "NovaExecution",
                "responsibilities": [
                    "Workspace",
                    "Projects",
                    "Reviews",
                    "Approvals",
                    "Workflow",
                    "Automation",
                    "Deployments",
                    "Testing",
                    "Operations",
                ],
                "platforms": [
                    "NovaCodePro",
                    "NovaWorkspace",
                    "NovaProjects",
                    "NovaReviews",
                    "NovaApprovals",
                    "NovaWorkflow",
                    "NovaAutomation",
                    "NovaDeployments",
                    "NovaTesting",
                    "NovaOperations",
                ],
            },
            {
                "id": "product-plane",
                "name": "Product Plane",
                "owner": "NovaProducts",
                "responsibilities": [
                    "Customer value",
                    "Modular product evolution",
                    "Market differentiation",
                    "Industry-specific solutions",
                ],
                "platforms": [
                    "NovaRide",
                    "NovaPay",
                    "NovaHealth",
                    "NovaCommerce",
                    "NovaEducation",
                    "NovaAgriculture",
                    "NovaEnergy",
                    "NovaInsurance",
                    "NovaRealEstate",
                    "NovaFood",
                    "NovaGov",
                    "NovaERP",
                    "NovaCRM",
                    "NovaAnalytics",
                    "NovaLogistics",
                ],
            },
            {
                "id": "infrastructure-plane",
                "name": "Infrastructure Plane",
                "owner": "NovaInfrastructure",
                "responsibilities": [
                    "Cloud",
                    "Gateway",
                    "Events",
                    "API",
                    "Storage",
                    "Network",
                    "Regions",
                    "Observability",
                    "Monitoring",
                    "Recovery",
                ],
                "platforms": [
                    "NovaCloud",
                    "NovaGateway",
                    "NovaEvents",
                    "NovaAPI",
                    "NovaStorage",
                    "NovaNetwork",
                    "NovaRegions",
                    "NovaObservability",
                    "NovaMonitoring",
                    "NovaRecovery",
                ],
            },
        ],
        "interaction_model": [
            "Governance -> Intelligence",
            "Intelligence -> Execution",
            "Execution -> Products",
            "Products -> Infrastructure",
            "Infrastructure -> Governance evidence and telemetry",
        ],
        "enterprise_state_models": [
            "Observed State",
            "Desired State",
            "Predicted State",
            "Simulated State",
            "Approved State",
            "Recovered State",
        ],
        "ai_workforce": [
            "Executive Agents",
            "Architecture Agents",
            "Engineering Agents",
            "QA Agents",
            "Security Agents",
            "Compliance Agents",
            "Finance Agents",
            "Support Agents",
            "Operations Agents",
            "Research Agents",
        ],
        "reasoning_domains": [
            "Strategic Reasoning",
            "Operational Reasoning",
            "Financial Reasoning",
            "Security Reasoning",
            "Compliance Reasoning",
            "Architecture Reasoning",
            "Risk Reasoning",
            "Recovery Reasoning",
            "Executive Reasoning",
        ],
    }


def build_enterprise_ai_architecture() -> dict[str, Any]:
    return {
        "id": "nai",
        "name": "NovaTech Enterprise AI Architecture",
        "version": "1.0",
        "generated_at": _now(),
        "stack": [
            "Agent Registry",
            "Agent Identity",
            "Agent Governance",
            "Agent Marketplace",
            "Agent Memory",
            "Agent Orchestrator",
            "Agent Runtime",
            "Agent Monitoring",
            "Agent Analytics",
            "Agent Learning",
            "Agent SDK",
        ],
        "governance": [
            "Authenticate through NovaID",
            "Authorize through NovaPolicy",
            "Record evidence in NovaAudit",
            "Publish knowledge to NovaKnowledge",
            "Communicate through NovaEvents",
        ],
    }


def build_enterprise_digital_twin_model() -> dict[str, Any]:
    return {
        "id": "ndtm",
        "name": "NovaTech Enterprise Digital Twin Model",
        "version": "1.0",
        "generated_at": _now(),
        "state_views": [
            "Observed State",
            "Desired State",
            "Predicted State",
            "Simulated State",
            "Approved State",
            "Recovered State",
        ],
        "twin_domains": [
            "Organization",
            "People",
            "Product",
            "Service",
            "Infrastructure",
            "Network",
            "Policy",
            "Risk",
            "Security",
            "Financial",
            "Knowledge",
            "Operations",
            "AI",
        ],
        "identity_contract": [
            "id",
            "type",
            "owner",
            "jurisdiction",
            "classification",
            "version",
            "lifecycle_state",
            "trust_state",
        ],
        "relationship_model": [
            "DEPENDS_ON",
            "HOSTED_BY",
            "OPERATED_BY",
            "PROTECTED_BY",
            "GOVERNED_BY",
            "SUPPLIED_BY",
            "CONNECTED_TO",
            "IMPACTS",
            "REQUIRES",
            "RECOVERS_WITH",
            "REPLACES",
        ],
        "capabilities": [
            "Current state",
            "Scenario simulation",
            "Impact analysis",
            "Recovery validation",
            "RTO/RPO analysis",
            "Cascading failure analysis",
            "Evidence capture",
            "Replay support",
        ],
    }


def build_enterprise_architecture_framework() -> dict[str, Any]:
    return {
        "id": "natech-framework",
        "name": "NovaTech AI-Native Enterprise Operating System Framework",
        "version": "2.0",
        "generated_at": _now(),
        "models": {
            "neaf": build_enterprise_plane_model(),
            "nera": build_nera_manifest(),
            "necm": build_enterprise_capability_model(),
            "neom": build_enterprise_operating_model(),
            "nedm": build_enterprise_data_architecture(),
            "nerm": build_enterprise_resilience_model(),
            "nekm": build_enterprise_meta_model(),
            "nai": build_enterprise_ai_architecture(),
            "ndtm": build_enterprise_digital_twin_model(),
        },
    }


__all__ = [
    "build_nera_manifest",
    "build_enterprise_architecture_framework",
    "build_enterprise_plane_model",
    "build_enterprise_capability_model",
    "build_enterprise_operating_model",
    "build_enterprise_meta_model",
    "build_enterprise_data_architecture",
    "build_enterprise_resilience_model",
    "build_enterprise_ai_architecture",
    "build_enterprise_digital_twin_model",
]
