# ============================================================
# AUTO-GENERATED — DO NOT EDIT
# Generated by compile_invariants.py
#
# Canonical deterministic runtime invariant index
# ============================================================

from __future__ import annotations


# ============================================================
# SCHEMA
# ============================================================

SCHEMA_VERSION = (
    "afritech.constitution.invariants.index.v2"
)

RUNTIME_PROJECTION_MODEL = (
    "runtime_subset_projection"
)

DETERMINISTIC = True
REPLAY_SAFE = True
CLOSED_WORLD_ALIGNED = True


# ============================================================
# EXECUTABLE RUNTIME INVARIANTS
# ============================================================

I1_REGISTRY_AUTHORITY = (
    "I1_REGISTRY_AUTHORITY"
)

I2_SEALED_SURFACE = (
    "I2_SEALED_SURFACE"
)

I3_NO_SILENT_MUTATION = (
    "I3_NO_SILENT_MUTATION"
)

I4_DETERMINISTIC_RUNTIME = (
    "I4_DETERMINISTIC_RUNTIME"
)

I5_EPOCH_MONOTONIC = (
    "I5_EPOCH_MONOTONIC"
)

I6_CLOSED_EXECUTION_WORLD = (
    "I6_CLOSED_EXECUTION_WORLD"
)


# ============================================================
# DETERMINISTIC ORDERING
# ============================================================

RUNTIME_INVARIANT_IDS = [

    I1_REGISTRY_AUTHORITY,
    I2_SEALED_SURFACE,
    I3_NO_SILENT_MUTATION,
    I4_DETERMINISTIC_RUNTIME,
    I5_EPOCH_MONOTONIC,
    I6_CLOSED_EXECUTION_WORLD,
]


# ============================================================
# VALIDATION GUARANTEES
# ============================================================

INVARIANT_COUNT = len(
    RUNTIME_INVARIANT_IDS
)

assert INVARIANT_COUNT == 6

assert (
    sorted(RUNTIME_INVARIANT_IDS)
    == RUNTIME_INVARIANT_IDS
)

assert len(
    set(RUNTIME_INVARIANT_IDS)
) == len(RUNTIME_INVARIANT_IDS)


# ============================================================
# CANONICAL EXPORTS
# ============================================================

__all__ = [

    "SCHEMA_VERSION",
    "RUNTIME_PROJECTION_MODEL",

    "DETERMINISTIC",
    "REPLAY_SAFE",
    "CLOSED_WORLD_ALIGNED",

    "INVARIANT_COUNT",
    "RUNTIME_INVARIANT_IDS",

    "I1_REGISTRY_AUTHORITY",
    "I2_SEALED_SURFACE",
    "I3_NO_SILENT_MUTATION",
    "I4_DETERMINISTIC_RUNTIME",
    "I5_EPOCH_MONOTONIC",
    "I6_CLOSED_EXECUTION_WORLD",
]