import { AppConfig } from "./models";

export const appConfig: AppConfig = {
  id: "partner",
  appName: "NovaID Partner",
  packageId: "com.novatech.novaid.partner",
  tagline: "Partner identity, integrations, credentials, compliance, and API trust.",
  trustTheme: "#0f7a8a",
  tabs: [
    { key: "overview", label: "Overview", description: "Partner status, trust score, approved services, and alerts." },
    { key: "partner-verify", label: "Partner Verify", description: "Partner application, representative, and compliance review." },
    { key: "integrations", label: "Integrations", description: "Create integrations, test webhooks, and review API docs." },
    { key: "credentials", label: "Credentials", description: "API keys, client certificates, and OAuth clients." },
    { key: "compliance", label: "Compliance", description: "Security review, AML policy, and incident reporting." },
    { key: "support", label: "Support", description: "Onboarding guidance and partner support requests." },
    { key: "settings", label: "Settings", description: "Partner profile, users, roles, and permissions." },
    { key: "dashboard", label: "Dashboard", description: "Legacy partner trust and usage overview." },
    { key: "clients", label: "Clients", description: "Legacy OAuth clients and secrets." },
    { key: "certificates", label: "Certificates", description: "Legacy partner certificate issuance." },
    { key: "webhooks", label: "Webhooks", description: "Legacy webhook targets and replay logs." },
    { key: "analytics", label: "Analytics", description: "Legacy usage trends and delivery checks." },
    { key: "profile", label: "Profile", description: "Partner support and API identity." },
  ],
  actions: [
    { label: "View partner status", detail: "Open the partner status summary." },
    { label: "View partner trust score", detail: "Show the partner trust and compliance score." },
    { label: "View approved services", detail: "List the services approved for the partner." },
    { label: "View API access status", detail: "Inspect API access and credential health." },
    { label: "View alerts", detail: "Review partner alerts and service notices." },
    { label: "Submit partner application", detail: "Start the partner onboarding workflow." },
    { label: "Upload business registration", detail: "Upload the partner business registration file." },
    { label: "Upload tax certificate", detail: "Upload the partner tax certificate." },
    { label: "Verify representative", detail: "Verify the authorized representative identity." },
    { label: "Submit compliance documents", detail: "Submit the required compliance documents." },
    { label: "Check review status", detail: "Check the current review status." },
    { label: "Create integration", detail: "Create a new integration record." },
    { label: "View integration status", detail: "Open the integration status summary." },
    { label: "Add webhook URL", detail: "Add a webhook target URL for events." },
    { label: "View API docs", detail: "Open the API documentation surface." },
    { label: "Run connection test", detail: "Run a connection test against the current partner integration." },
    { label: "Generate API key", detail: "Generate a new API key for the partner." },
    { label: "Rotate API key", detail: "Rotate the active API key." },
    { label: "Revoke API key", detail: "Revoke an existing API key." },
    { label: "Upload certificate", detail: "Upload a partner certificate or trust file." },
    { label: "Download client credentials", detail: "Export the current client credentials." },
    { label: "Manage OAuth client", detail: "Edit the OAuth client configuration." },
    { label: "View compliance checklist", detail: "Review the partner compliance checklist." },
    { label: "Submit security review", detail: "Submit the security review package." },
    { label: "Submit AML policy", detail: "Upload the AML policy for review." },
    { label: "Submit data protection policy", detail: "Upload the data protection policy." },
    { label: "Download compliance report", detail: "Export the partner compliance report." },
    { label: "Report incident", detail: "Open an incident report for review." },
    { label: "Open support ticket", detail: "Open a partner support ticket." },
    { label: "Contact partner manager", detail: "Contact the partner manager from the app." },
    { label: "Report integration issue", detail: "Report an issue with the partner integration." },
    { label: "View onboarding guide", detail: "Open the partner onboarding guide." },
    { label: "Manage partner profile", detail: "Update the partner profile details." },
    { label: "Manage users", detail: "Manage users with partner access." },
    { label: "Manage roles", detail: "Manage partner roles." },
    { label: "Manage permissions", detail: "Manage partner permissions." },
    { label: "Security settings", detail: "Update partner security settings." },
    { label: "Logout", detail: "End the partner session." },
    { label: "Create OAuth Client", detail: "Provision a new partner OAuth 2.1 client." },
    { label: "Rotate Secret", detail: "Rotate the client secret and update trust state." },
    { label: "Issue Partner Certificate", detail: "Create a partner trust certificate." },
    { label: "View API Usage", detail: "Inspect live request counts and quota status." },
    { label: "Test Webhook", detail: "Send a webhook test against the current client." },
  ],
  primaryFlow: [
    "Client created",
    "Secret rotated",
    "Certificate issued",
    "Webhook tested",
    "Usage observed",
    "Audit package ready",
  ],
  seed: {
    displayName: "Nova Partner Network",
    walletLabel: "Partner trust vault",
    trustLevel: "High",
    identityScore: 95,
    credentialCount: 4,
    trustedDevices: 2,
    governmentIds: 1,
    certificateCount: 4,
    biometricVerified: true,
    passkeyEnabled: true,
    deviceTrustEnabled: true,
    recoveryEnabled: true,
    connectedApps: 5,
    loginHistory: 21,
  },
};
