# Generated by Django 5.2.14 on 2026-06-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfriPayParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("party_id", models.CharField(max_length=120, unique=True)),
                ("country", models.CharField(max_length=8)),
                ("kyc_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FXRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_reference", models.CharField(max_length=120, unique=True)),
                ("base_currency", models.CharField(max_length=8)),
                ("quote_currency", models.CharField(max_length=8)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=24)),
                ("provider", models.CharField(max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=180, unique=True)),
                ("request_hash", models.CharField(max_length=64)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="stored", max_length=24)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("account_type", models.CharField(max_length=40)),
                ("currency", models.CharField(max_length=8)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=120, unique=True)),
                ("event_type", models.CharField(max_length=120)),
                (
                    "aggregate_id",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("hash_chain", models.CharField(max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aggregate_id", "created_at"],
                        name="afripay_event_aggregate_idx",
                    ),
                    models.Index(fields=["event_type"], name="afripay_event_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kyc_profile",
                        to="afripay.afripayparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LiquidityPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pool_id", models.CharField(max_length=120, unique=True)),
                ("provider", models.CharField(max_length=80)),
                ("currency", models.CharField(max_length=8)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=24)),
                (
                    "reserved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
                (
                    "low_watermark",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "currency"), name="afp_unique_provider_pool"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="afp_pool_bal_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reserved__gte", 0)),
                        name="afp_pool_res_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", models.F("reserved"))),
                        name="afp_pool_res_lte_bal",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayoutBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payout_id", models.CharField(max_length=120, unique=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                ("status", models.CharField(default="planned", max_length=24)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_batches",
                        to="afripay.afripayparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                ("reference", models.CharField(max_length=160, unique=True)),
                ("status", models.CharField(default="pending", max_length=24)),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="afripay.payoutbatch",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_items",
                        to="afripay.afripayparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription_id", models.CharField(max_length=120, unique=True)),
                ("plan_name", models.CharField(max_length=120)),
                (
                    "recurring_amount",
                    models.DecimalField(decimal_places=2, max_digits=24),
                ),
                ("currency", models.CharField(max_length=8)),
                ("status", models.CharField(default="active", max_length=24)),
                ("next_billing_at", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="afripay.afripayparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_id", models.CharField(max_length=120, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                ("status", models.CharField(default="open", max_length=24)),
                ("due_at", models.DateTimeField()),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="afripay.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=120, unique=True)),
                ("reference", models.CharField(max_length=160, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                ("transaction_type", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("routed", "Routed"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="afripay.afripayparty",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="afripay.afripayparty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=80)),
                ("external_reference", models.CharField(max_length=180)),
                ("status", models.CharField(max_length=40)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_transactions",
                        to="afripay.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_id", models.CharField(max_length=120, unique=True)),
                ("provider", models.CharField(max_length=80)),
                ("rail", models.CharField(max_length=40)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
                ("status", models.CharField(default="planned", max_length=24)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="afripay.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("journal_id", models.CharField(max_length=120, unique=True)),
                ("reference", models.CharField(max_length=160, unique=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="afripay.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FXConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conversion_id", models.CharField(max_length=120, unique=True)),
                ("amount_in", models.DecimalField(decimal_places=2, max_digits=24)),
                ("amount_out", models.DecimalField(decimal_places=2, max_digits=24)),
                ("from_currency", models.CharField(max_length=8)),
                ("to_currency", models.CharField(max_length=8)),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions",
                        to="afripay.fxrate",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_conversions",
                        to="afripay.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("escrow_id", models.CharField(max_length=120, unique=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                ("release_condition", models.CharField(max_length=240)),
                ("status", models.CharField(default="locked", max_length=24)),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows_received",
                        to="afripay.afripayparty",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows_paid",
                        to="afripay.afripayparty",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows",
                        to="afripay.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TreasuryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reservation_id", models.CharField(max_length=160, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=24)),
                ("currency", models.CharField(max_length=8)),
                ("status", models.CharField(default="reserved", max_length=24)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="afripay.liquiditypool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wallet_id", models.CharField(max_length=120, unique=True)),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("business", "Business"),
                            ("community", "Community"),
                            ("savings", "Savings"),
                        ],
                        max_length=24,
                    ),
                ),
                ("home_country", models.CharField(max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to="afripay.afripayparty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(max_length=120, unique=True)),
                ("currency", models.CharField(max_length=8)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
                (
                    "locked_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currency_accounts",
                        to="afripay.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=24),
                ),
                ("currency", models.CharField(max_length=8)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="afripay.journalentry",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_lines",
                        to="afripay.ledgeraccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("debit__gte", 0)),
                        name="afp_entry_debit_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("credit__gte", 0)),
                        name="afp_entry_credit_nonneg",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["reference"], name="afripay_tx_reference_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["payer", "status"], name="afripay_tx_payer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["payee", "status"], name="afripay_tx_payee_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="afripay_tx_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="providertransaction",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_reference"),
                name="afp_unique_provider_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentroute",
            index=models.Index(
                fields=["provider", "status"], name="afp_route_provider_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyaccount",
            constraint=models.UniqueConstraint(
                fields=("wallet", "currency"), name="afripay_unique_wallet_currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)), name="afp_cur_bal_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("locked_balance__gte", 0)),
                name="afp_cur_locked_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", models.F("locked_balance"))),
                name="afripay_locked_lte_balance",
            ),
        ),
    ]
