# Generated by Django 5.2.14 on 2026-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afripay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idempotencykey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payoutitem",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="providertransaction",
            name="internal_reference",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="grace_period_days",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
