# Generated by Django 5.2.14 on 2026-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afripay", "0002_escrow_expires_at_idempotencykey_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKeyCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_id", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("prefix", models.CharField(max_length=12)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("suspended_until", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key_hash"], name="afp_apikey_hash_idx"),
                    models.Index(fields=["is_active"], name="afp_apikey_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("secret_hash", models.CharField(max_length=64)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("suspended_until", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["client_id"], name="afp_oauth_client_idx"),
                    models.Index(fields=["is_active"], name="afp_oauth_active_idx"),
                ],
            },
        ),
    ]
